<?php
  include 'funkcje.php';
  include 'conf.php';
    $podroze1 = '<p class="p3">Jezioro Bodeńskie, czyli kwiaty, Alpy i niemieckie autostrady<br>';
//Jezioro Badeńskie 20150524
$podroze1.='<p class="p1">Obudził mnie śpiew ptaków za oknem…';
$podroze1.='<p class="p1">Ćwierkały i ćwierkały, coraz głośniej i głośniej, aż w końcu dotarło do mnie, że to nie ptaki za oknem śpiewają z okazji ładnej pogody, a mój budzik. Wyłączyłem go więc starając się wycelować palcem w odpowiednią część ekranu w smartfonie i zwlokłem się z łóżka.';
$podroze1.='<p class="p1">Najtrudniej rano jest mi odpalić silnik. Czterdziestojednoletni organizm broni się jak może przed rozruchem po zaledwie kilku godzinach snu, dopiero kilkanaście minut biegania i kilkadziesiąt pompek i brzuszków doprowadzają mnie do stanu jakiej takiej sprawności fizycznej sprzed dziesięciu lat. Prysznic, jajecznica na bekonie, kawa, szklanka soku i kolejne 5 lat ubywa z życiorysu. Można zacząć funkcjonować normalnie.';
$podroze1.='<p class="p1">Przez niemieckie autostrady jedzie się bardzo przyjemnie, aczkolwiek nie jest to tak jak słyszałem od wielu znajomych, że nie ma żadnych ograniczeń prędkości. Ograniczenia są, w większości do 120 km/h, przynajmniej tutaj, w okolicach Stuttgartu. Ale mimo wszystko jedzie się przyjemnie, bo drogi są równe i miejscami mają po trzy pasy w jednym kierunku. Droga nad Jezioro Bodeńskie prowadzi kilkoma bardzo wysokimi wiaduktami, z najwyższym na wysokości około 800 m n.p.m.  i jezdnią około 90 metrów nad ziemią. Niedużo widać w dole, bo auto osobowe jest niskie i barierki zasłaniają widok, ale kierowcy TIR-ów mają pewnie niezłą frajdę z jazdy tą trasą.';
$podroze1.= foto_line('niemcy2015/jezioro_bodenskie/konst',3,4,'_s');
$podroze1.='<p class="p2"><b>Konstanz</b>';
$podroze1.='<p class="p1">Konstancja to największe miasto niemieckie nad Jeziorem Bodeńskim. Zostawiliśmy auto na parkingu (o dziwo darmowym w niedzielę i święta), po czym przez pustą jeszcze przed południem starówkę przeszliśmy na deptak nad samym jeziorem. Niemcy mają długi weekend, więc nikomu nie chce się wychodzić z domu przed południem. Zapewne już w południe wszystkie kawiarnie na starym mieście będą zapełnione jak łódzki tramwaj w godzinach szczytu. Widoki na jezioro pocztówkowe, więc zrobiłem kilkanaście zdjęć i trzeba było ruszać dalej, bo do zwiedzenia było jeszcze kilka atrakcji poza Konstancją. Przespacerowaliśmy się mostem nad Renem w miejscu, gdzie ten wypływa z jeziora, przeszliśmy się deptakiem wzdłuż nabrzeża, po czym wolnym krokiem już przez miasto wróciliśmy do samochodu i pojechaliśmy na Mainau.';
$podroze1.= foto_line('niemcy2015/jezioro_bodenskie/konst_a',3,4,'_s');
$podroze1.='<p class="p2"><b>Wyspa Kwiatów</b>';
$podroze1.='<p class="p1">Mainau nazywana jest Wyspą Kwiatów i jest jedną z największych atrakcji turystycznych nad Jeziorem Bodeńskim. Niby wiedziałem o tym, ale mimo wszystko nie spodziewałem się, że przez prawie pół godziny będziemy szukać parkingu, a następne piętnaście będziemy stać w kolejce do kasy. Jak się okazało, zwiedzanie wyspy jest płatne i kosztuje 19 euro od osoby, a ponieważ jak już wspominałem w Niemczech jest długi weekend, wszyscy wpadli na pomysł, że właśnie to najlepsza pora do weekendowego spędzenia czasu.';
$podroze1.='<p class="p1">Na wyspie kwiatów - wiadomo - mnóstwo kwiatów. Poza tym oczywiście znów piękne na jezioro (i na Alpy, które niestety tego dnia widać było ledwo-ledwo), więc znowu można było zabawić się w Japończyka, a przy okazji potestować kilka filtrów fotograficznych. Nie tylko ja bawiłem się w Japończyka, robili to też Niemcy i... sami Japończycy. Jednemu z nich aparat wypadł z ręki wprost na beton rozsypując się na kawałki i aż żal było patrzeć jak kilka tysięcy złotych właśnie zmienia się w kupę nie nadającego się do niczego złomu. W niespełna trzy godziny obeszliśmy całą wyspę wraz ze zwiedzeniem stojącego w najwyższym punkcie pałacu. Nie za wiele w środku było do oglądania, zaledwie kilka pokoi z widokiem na wodę, galeria obrazów takich sobie, sklep z pamiątkami i kawiarnia urządzona w stylu "palmiarnianym", gdzie można było posiedzieć w szklarnianych warunkach w cieniu palm i posłuchać skrzeczących w dużych klatkach papug. Na koniec stanęliśmy w potężnej kolejce do kolejnej szklarni, gdzie w tropikalnych warunkach można obejrzeć kilka gatunków motyli, których nie zobaczymy na polskich łąkach. Prawdę mówiąc nie zdawałam sobie sprawy, że niektóre mogą dorosnąć do tak wielkich rozmiarów.';
$podroze1.= foto_line('niemcy2015/jezioro_bodenskie/mainau',3,4,'_s');
$podroze1.='<p class="p1">Na Mainau można się dostać z dwóch stron: jedna jest od strony lądu, którą przyjechaliśmy, oraz druga od strony jeziora, gdzie można przypłynąć statkiem wycieczkowym od strony szwajcarskich i austriackich miast. Stateczki kursują bardzo często, a  z tego co zaobserwowałem, za każdym razem mają pełną obsadę. Może to dlatego, że to długi weekend. ';
$podroze1.='<p class="p1">Jak się okazało - jest jeszcze trzecia strona: wyspę jak i całe jezioro można oglądać z góry podczas lotu wycieczkowego sterowcem Graf Zeppelin, których fabryka znajduje się również w tych okolicach, w Friedrichshafen.';
$podroze1.='<p class="p2"><b>Überlingen</b>';
$podroze1.='<p class="p1">To ostatnie miasto które byliśmy w stanie zwiedzić jednego dnia. Można byłoby się spiąć i objechać całe jezioro dookoła szukając jeszcze lepszych widoków na panoramę Alp i zwiedzając średniowieczne fortece położone nad jeziorem, ale nie było sensu. Nie jestem zwolennikiem napiętych planów podczas wycieczek, wolę na spokojnie pospacerować, robiąc przerwy na spokojne posiedzenie w ciekawych miejscach. Tak też zrobiliśmy w Überlingen: najpierw bez pośpiechu poszukaliśmy miejsca, gdzie możemy zjeść obiad serwowany przez rodowitych Niemców z dalekiego wschodu, przy okazji szerokim łukiem omijając wszystkie nadbrzeżne kawiarnio-restauracje pełne ludzi siedzących nad filiżankami z obrzydliwie drogą kawą i lodami i z nosami w smartfonach, a potem znów spokojny spacer po promenadzie nad jeziorem, starówce i na koniec kilka zdjęć z wysokiej baszty murów obronnych, skąd bardzo jest bardzo ciekawy widok miasto i jezioro.';
$podroze1.= foto_line('niemcy2015/jezioro_bodenskie/uber',3,4,'_s');
$podroze1.='<p class="p2"><b>I do domu...</b>';
$podroze1.='<p class="p1">Powrót bez historii - po niespełna dwóch godzinach jazdy autostradą byliśmy w Stuttgarcie. My jechaliśmy samochodem, ale jezioro otoczone jest też ścieżkami rowerowymi, w większości asfaltowymi, więc jak ktoś ma ochotę i możliwość na dłuższą wycieczkę rowerową, to myślę że jest warto poświęcić kilka dni na bezstresowe zwiedzanie tych okolic. <i><font size=-4>rs, Stuttgart, maj 2015</font></i>';
//  $podroze1.= foto_line('ochodzita2007/karczma',3,9,'_s');
include 'podr_sma.php';
//require_once("funkcje.php");
//data_index($podroze1,'meta data próbne ąśćŚ');
?>
