<?php
  include 'funkcje.php';
  include 'conf.php';

$podroze1 = '<p class="p3">Tam, gdzie słońce nie zachodzi<br>';
//Hoga Kusten 20120622-24
$podroze1.='<p class="p1">Dobiega końca mój drugi dzień na Höga Kusten*. Chciałbym napisać jakiś banał, na przykład że Zatoka Botnicka mieni się w zachodzącym słońcu, ale... Nie mogę, bo słońce w ogóle tutaj nie chce zajść. Chowa się za horyzont co prawda, ale ciągle jest widno jak w dzień. Wystarczy poczekać godzinę czy dwie i jego promienna tarcza znowu staje się widoczna. Takie są uroki przebywania na Dalekiej Północy w Midsommar, czyli w dniu przesilenia letniego.';
$podroze1.='<p class="p1">Dzisiejszy dzień miał być lekki i przeznaczony na odpoczynek. Łowienie ryb, leżenie, pisanie, czytanie, ale widząc krajobraz dookoła siebie trudno usiedzieć w miejscu. Chce się wędrować i wędrować, napawać się tym widokiem i ładować baterie, aby starczyły na długie tygodnie pracy. Zebraliśmy się więc w sobie koło południa, założyliśmy plecaki i zeszliśmy kilka kilometrów w dół góry aż do kolejnego drewnianego domku - naszego kolejnego miejsca noclegowego. A potem jeszcze na krótki “trzykilometrowy”** spacer, aby uzupełnić w strumyku wodę do picia. Ale zacznijmy od początku.';
$podroze1.='<p class="p1"><b>Dzień pierwszy</b>';
$podroze1.='<p class="p1">Wyjechaliśmy ze Sztokholmu koło siódmej rano - godzinę później niż zaplanowaliśmy. Ale to wolny dzień przecież, a dnia nam nie braknie na pewno. Auto sprawnie połykało kilometry szwedzkiej E4, tylko od czasu do czasu zatrzymywaliśmy się dla rozprostowania kości, czy uzupełnienia zapasów żywieniowych przy okazji zwiedzając opustoszałe w ten dzień miasto Sundsvall. Jeszcze sto kilometrów i naszym oczom ukazał się potężny most Höga Kusten. Högakustenbron, bo tak nazywa się po szwedzku, to drugi najdłuższy most w Skandynawii (najdłuższy jest duński Storebæltsforbindelsen), ma długość 1867 metrów, a kolumny są wysokie na 180 metrów. To jest nasza brama do kilkudniowej wolności od miejskiego zgiełku i hałasu. Jeszcze trochę, a wyczerpią się baterie w smartfonach i zostaniemy tylko my i dzika przyroda, gdzie człowiek po kilku godzinach pobytu myśli tylko, aby z piętnastokilowym plecakiem na plecach stawiać jedną nogę przed drugą po kamienistych górskich wertepach, zapominając nawet o tym, że pospiesznie się pakując zostawił bałagan w mieszkaniu, a samochód w “najsłynniejszej” sztokholmskiej dzielnicy Rinkeby dwieście kilometrów od Linköping. Na marginesie mówiąc - samochód przetrwał w nienaruszonym stanie, więc dzielnica nie jest taka zła, jakie ma opinie. A i mój Samsung Solid wytrzyma miesiąc bez ładowania, ale przy tutejszym zasięgu telefonii komórkowej to złudne poczucie bezpieczeństwa. No pomoc innych ludzi też za bardzo liczyć nie można, bo... Szlaki są puste. Nie wiem, czy tak jest tylko w Midsommar, czy po prostu szwedzkie parki narodowe cieszą się tak malą popularnością wśród turystów. Na pewno jest to miła odmiana od zatłoczonego Kasprowego Wierchu. A dla nas tym lepiej, bo jest duża szansa, że nie będziemy spać pod gołym niebem i wykorzystamy jeden z czterech dostępnych na trasie domków traperskich.';
$podroze1.= foto_line('szwecja2012/hoga_kusten/hka',3,8,'_s');
$podroze1.='<p class="p1">Kilka zdjęć na pamiątkę i mkniemy w kierunku parku narodowego Skuleskogen z jego najwyższą górą Skuleberget. Góra jest wysoka na 295 metrów i jest najwyżej położonym punktem szwedzkiego wybrzeża. Niby 295 metrów to niedużo, ale... Wyobraźmy sobie, że stoimy na poziomie morza, a góra rośnie prawie pionowo przed nami. Wtedy te metry naprawdę robią wrażenie. Ale nie na nas. Zostawiliśmy plecaki w samochodzie, wzięliśmy zapasy wody do picia i w górę. Oczywiście z tej stromej strony. Wejście jest trudne, cała ścieżka po ostrych kamieniach i korzeniach, a miejscami trzeba posiłkować się łańcuchami, drewnianymi trapami i metalowymi drabinkami, żeby dostać się na kolejną półkę skalną. Ale trasa jest świetnie przygotowana i nawet dzieci sobie z nią radzą wyśmienicie. Natomiast na pewno nie polecam jej kobietom na szpilkach, mimo że podobno w ten sposób mozna wejść na polski Giewont.';
$podroze1.='<p class="p1">Niedaleko przed samym szczytem ścieżka się rozwidla i drugą odnogą można dojść do sporej groty, widocznej już od podnóża góry, gdzie podobno ukrywała się kiedyś banda rabusi. Ich herszt nazywał się Skule.';
$podroze1.='<p class="p1">Pogoda nas rozpieszczała. Chwilę spędziliśmy na szczycie podziwiając jak Zatoka Botnicka wcina się pomiędzy zalesione góry, słuchamy absolutnej ciszy. Tu w Midsommar nawet samoloty nie latają. Schodzimy z góry tą samą drogą, a zakupiony w restauracji u podnóża naszej góry wyśmienity smażony łosoś z młodymi ziemniakami - to ostatni nasz “komercyjny” posiłek na kolejne dni. Potem co ugotujemy to zjemy.';
$podroze1.= foto_line('szwecja2012/hoga_kusten/hkb',3,8,'_s');
$podroze1.='<p class="p1">Zostawiliśmy samochód na parkingu przy południowym wejściu do parku i już z ciężkimi plecakami na plecach (a co niektórzy nawet z wędkami w dłoni) wyruszyliśmy w drogę przez góry. Droga była ciężka. Lżejsze trasy Daniel, który był już tutaj kilka razy, zostawił na dalsze dni. Widoki zapierały dech w piersiach, a pot lał się po plecach mimo że nie było bardzo gorąco. Komary i meszki atakowały zaciekle, ale... Nie mnie. To aż dziwne, bo nad polską rzeką (a nawet tutaj w Szwecji, nad Stångan w Linköping) tylko chwilę się zatrzymam, żeby zmienić przynętę, a już te małe paskudne pasożyty chcą mnie zjeść żywcem. Wbijają swoje krwiożercze ryjki w co tylko popadnie, nieważne czy przykryte ubraniem, czy nie. A tu -  chmara komarów krążyła mi nad głową, ale nie atakowały, mimo że nie wspomagałem się żadną chemią pryskaną. Może komary z Höga Kusten nie lubią mojej krwi i niech tak zostanie jak najdłużej.';
$podroze1.='<p class="p1">Wspięliśmy się na górę nieco mniejszą niż Skuleberget, dorzucilimy swoje kamyki do usypanych już górek, i maszerując grzbietem w iście księżycowym krajobrazie doszliśmy do wąwozu Slåtdalsskrevan, długiego na 100 metrów, szerokiego na siedem, a głębokiego na czterdzieści. Mimo największych chęci nie zdołałem się podczołgać na jego skraj, żeby spojrzeć z góry na dno jaru. Gładka skalna półka pochylona była lekko w dół, a wyrastające z niej słabe z braku możliwości wbicia korzeni w podłoże drzewka nie dawały tyle pewności, żeby można było trzymając się ich pni czuć się bezpiecznym. Wąwóz z dołu również robił niesamowite wrażenie. Pionowe nagie skały powodowały, że wewnątrz panował chłód i półmrok.';
$podroze1.='<p class="p1">Zeszliśmy wąwozem w dół i już po jakichś kolejnych “trzech kilometrach” doszliśmy do pierwszej chatki, w której planowaliśmy zostać na noc. Położona malowniczo nad jeziorem miała klimat wprost z traperskich opowieści o kanadyjskich łowcach bobrowych skórek. A co najważniejsze - miała cztery łóżka i była wolna.';
$podroze1.='<p class="p1">Z jednej strony, w głębi, była część mieszkalna, a z drugiej - tuż przy wejściu - palenisko i stół z dwoma ławami do siedzenia. Na zewnątrz - zapasy drewna, siekiera i miejsce na ognisko. Przesiedzieliśmy rozmawiając przy ognisku kilka godzin, a na dworze wciąż było widno. Łuna za horyzontem przez całą noc była widoczna, jak przy zachodzie słońca nad naszym Bałtykiem. Taki to już urok tej północnej krainy latem. Gdy kładliśmy się spać, słońce powoli wznosiło się nad horyzont.';
$podroze1.='<p class="p1"><b>Dzień drugi</b>';
$podroze1.='<p class="p1">Dzień drugi, jak już pisałem wczesniej, miał być lekki i przyjemny. Przyjemny oczywiście był, ale nie lekki. Jak wspominałem, najpierw przenieśliśmy nasz cały dobytek do drugiej chatki. Po zeszłodniowej wędrówce nogi już nie chciały tak pewnie stąpać po kamieniach, a zejście znad jeziorka położonego dość wysoko nad sam brzeg Zatoki Botnickiej prowadziło kamienistym i miejscami bardzo stromym wąwozem. Kolejne “trzy kilometry” połknęliśmy jednak w niecałe dwie godziny i mogliśmy zjeść drugie śniadanie w naszym nowym lokum.';
$podroze1.= foto_line('szwecja2012/hoga_kusten/hkc',3,8,'_s');
$podroze1.='<p class="p1">Ten domek nie był już taki klimatyczny jak poprzedni, bardziej przypominał daczę letniskową niż traperską chatę. Ale za to mieliśmy więcej miejsca. Gdyby dziś przyszli kolejni podróżni zainteresowani noclegiem, spokojnie mogliby się rozgościć na obszernej podłodze. Poprzednio takiego luksusu nie mieliśmy. W domku - standardowo: cztery łóżka, duży stół tym razem z krzesłami, palenisko i... Część kuchenna ze zlewozmywakiem i piecem. Ale aby uruchomić zlew należało wcześniej napełnić dwa pięćdziesięciolitrowe baniaki wodą. A do słodkiej wody trzeba było kawałek się przespacerować.';
$podroze1.='<p class="p1">Co musieliśmy zrobić, ale łatwiej było zabrać ze sobą tylko kilka plastikowych butelek zamiast potężnego kanistra. Z pieca staraliśmy się nie korzystać, bo przy takiej pogodzie podusilibyśmy się z gorąca, a okien nie można było otwierać ze względu na komary. Było za to miejsce na ognisko i zapasy drzewa wraz z piłą i siekierą, a zupę czy wodę na herbatę przy odrobinie dobrych chęci można ugotować również na wolnym powietrzu. Smak jest niepowtarzalny. Mimo że starałem się doszorować garnek po przyjeździe do domu, jeszcze wczoraj jak przygotowując posiłek poczułem zapach ogniska, od razu zatęskniłem za zielonymi lasami i czystymi jeziorami parku Skuleskogen.';
$podroze1.='<p class="p1">W międzyczasie trochę napiszę o tutejszej roślinności i zwierzynie. Wart wspomnienia jest na pewno fakt, że nie ma kleszczy. Przynajmniej ja nie zauważyłem żadnego usiłującego sfrunąć z drzew na mnie. Z roślin przeważają sosny i świerki, niektóre bardzo stare, gdyż pożaru lasu nie było tu od bardzo dawna. Na starych świerkach można zauważyć brodaczkę najdłuższą, dziwną roślinę przypominającą starą grubą pajęczynę, która jest wrażliwa na najmniejsze zanieczyszczenie środowiska. Oprócz tego spotkamy modrzyk górski, firletkę slpejską, a z traw i porostów kostrzewę i paprotnik koczysty znany również z naszych terenów. No i zaczynają kwitnąć jagody. Ze zwierząt -  mnóstwo ptaków i ssaków z królem tych terenów łosiem na czele. Skały to przede wszystkim granit, łącznie z rzadką odmianą rapakiwi.';
$podroze1.='<p class="p1">Ale wracajmy do obozowej rzeczywistości. Po lekkiej przekąsce wybraliśmy się na spacer (“trzykilometrowy” oczywiście, jakżeby inaczej) do północnego wyjścia z parku. Wyjście powstało stosunkowo niedawno, bo trzy lata temu, i Danielowi ubzduralo się, że na zdjęciach widział, że można zaopatrzyć się tam w wodę pitną, a nawet że są sklepy, gdzie można uzupełnić zapasy. Złudne marzenia, a wędrowiec na pustyni zawsze widzi fatamorganę. Spacer jednak nie był ciężki, a przy okazji odwiedziliśmy kilka ciekawych miejsc, między innymi piękną piaszczystą plażę nad zatoką (oczywiście zupełnie pustą) i opuszczone siedlisko bobrów. W drodze powrotnej nabraliśmy wody we wszystkie nasze pojemniki. Woda ze strumyków miała lekko brązowy kolor, ale była czysta. Dla pewności woleliśmy ją jeszcze przegotować przed użyciem.';
$podroze1.='<p class="p1">Wcześniej jednak postanowiłem wykąpać się w zatoce. Pomny doświadczeń z poprzedniego dnia z kąpielą w jeziorku, po której żeby się rozgrzać ubrałem na siebie praktycznie wszystko co miałem z wyjątkiem kurtki przeciwdeszczowej, teraz chciałem to zrobić gdy słońce było w najwyższym punkcie na niebie. Wody zatoki w tym rejonie, mimo że czyste, do najcieplekszych nie należą i długo się w nich nie popływa.';
$podroze1.='<p class="p1">Wieczorem w końcu był czas na odpoczynek, łowienie ryb w zatoce (w jeziorach i rzekach na terenie parku łowienie jest zabronione), pisanie, czytanie, rozmowy przy ognisku i przy stole. W pewnym momencie trzeba było spojrzeć na zegarek i położyć się spać. Plan na niedzielę był napięty jak struna.';
$podroze1.='<p class="p1"><b>Dzień trzeci</b>';
$podroze1.='<p class="p1">Ostatnie śniadanie w plenerze, zwijanie manatek, poranna toaleta i w drogę. Dosyć łagodną tym razem co prawda, ale długą i wyczerpującą. Szczególnie ostatnie, kilometrowe podejście do wyjścia z parku po niewygodnej drodze usypanej z drobniutkich kamieni dawało w kość. Idąc wzdłuż jednej z odnóg zatoki koło południa dotarliśmy do samochodu, z ulgą pozbyliśmy się przyniesionych w reklamówkach śmieci i wrzuciliśmy plecaki do bagażnika. Nie były już tak ciężkie jak na początku, ale i tak miło było pozbyć się balastu. Teraz zwiedzanie miało być już typowo rekreacyjne.';
$podroze1.= foto_line('szwecja2012/hoga_kusten/hkd',3,8,'_s');
$podroze1.='<p class="p1">Pojechaliśmy do wioski rybackiej Skagshamn, gdzie zobaczyliśmy latarnię morską Skagsudde, muzeum Surströmming (historia szwedzkiego kiszonego śledzia zaczęła się właśnie na Höga Kusten), i kupiliśmy wędzone ryby na powrotną podróż. Drewniane domki w większości stoją tuż nad brzegiem wody. Z jednej strony dotykają lądu łacząc się z przydomowym ogrodem (bardzo zadbanym), a z drugiej drewnianymi pomostami wystają ponad poziom wody. Każdy z nich jest zaprojektowany tak, aby od strony wody można było wpłynąć do niego łodzią - ot taki wodny garaż. Ciekawy jest również system sprzedaży ryb, ponieważ w sklepie nie ma obsługi. Wchodzimy do sklepu, z zamrażarek wybieramy te ryby, które chcemy wziąć, po czym odliczamy kwotę według cennika i wrzucamy pieniądze do metalowego sejfu. Zaufanie w uczciwość ludzką jest tutaj przeogromne. Główną ulicą można dojść do latarni morskiej, skąd rozciąga się wspaniały widok na morze i... Skalną pustynię. Tak sobie pomyślałem, że jak w Polsce na plażę kupuje się dzieciom wiadereczka i łopatki do piasku, tak tutaj najlepiej powinny się sprzedawać malutkie kilofki i laseczki dynamitku. Dzieci z mojej ironii jednak nic sobie nie robiły i bawiły się w najlepsze na tej specyficznej plaży ze skał, a rodzice w tym czasie piknikowali na kocach. Zupełnie jak nad polskim morzem, tylko ludzi mniej i nie ma tego towarzyszącego wszędzie hałasu. Tutaj słuchamy tylko szumu wiatru i śpiewu ptaków, a nie RMF FM czy nawoływań do kupienia lodów i piwa. Jedna smutna rzecz - w tej wiosce nie ma w ogóle młodych ludzi. Przynajmniej ja ich tu nie widziałem.';
$podroze1.='<p class="p1">Na koniec wypiliśmy kawę w restauracji przy muzeum i wyruszyliśmy w drogę powrotną. Zatrzymaliśmy się jeszcze raz spojrzeć na żegnający nas olbrzymi most, zjedliśmy drugie śniadanie z zakupionej wcześniej wędzonej siei i pożegnaliśmy gościnne Wysokie Wybrzeże. Czy na zawsze? W moim wypadku na pewno nie. Jeżeli będę miał okazję, na pewno będę tu wracał.';
$podroze1.='<p class="p1"><i>* Höga Kusten - część szwedzkiego wybrzeża nad Zatoką Botnicką, 100 km na północ od Sundsvall. W 2000 roku wpisane na listę UNESCO jako jeden z najbardziej interesujących obszarów na Ziemi. Najciekawsze jest to, że wybrzeże wciąż rośnie. Góry się wypiętrzają o okooło 1,8 mm na rok.</i>';
$podroze1.='<p class="p1"><i>** Tak Daniel zwykł mówić na każdy odcinek drogi do przejścia, nieważne czy miał trzy, czy pięć kilometrów. Łącznie zebrało nam się około 30 kilometrów marszu. Dane są szacunkowe, bo nie używaliśmy ani miernika kroków, ani odbiorników GPS.</i>';
$podroze1.='<p class="p1"><i><font size=-4>rs, Hoga Kusten, czerwiec 2012</font></i>';

//  $podroze1.= foto_line('ochodzita2007/karczma',3,9,'_s');
include 'podr_sma.php';
//require_once("funkcje.php");
//data_index($podroze1,'meta data próbne ąśćŚ');
?>
