<?php
  include 'funkcje.php';
  include 'conf.php';

$podroze1 = '<p class="p3">Klawo jak cholera, chłopaki!<br>';
//Kopenhaga 20120908
$podroze1.='<p class="p1">Volvo S90 Executive z szumem opon połykało kolejne kilometry szwedzkiej E4, a za oknem rozpościerał się widok na wielki narciarski wyciąg... Zaraz zaraz, jaki wyciąg narciarski - czytelnik mógłby zapytać. - Na równinie?';
$podroze1.='<p class="p1">Tak wygląda okolica Forsby, które mijaliśmy właśnie po drodze do Helsingborg, gdzie mieliśmy zaokrętować się na prom do duńskiego Helsingør, a mijany właśnie przez nas wyciąg nie był narciarski, tylko służył kiedys do transportu wapnia, z którego słynęła tutejsza okolica. Wyciąg miał długość prawie 42 kilometry, a wyglądał jak zwykła kolejka linowa, gdzie zamiast wagoników wisiały wiadra. Swoją drogą mieliśmy niespotykane szczęście jeszcze zobaczyć tę dziwną konstrukcję, gdyż właśnie w bieżącym roku przeznaczona została do rozbiórki i prace właśnie się zaczęły.';
$podroze1.='<p class="p2"><b>Helsingborg</b>';
$podroze1.='<p class="p1">Korzystając z ostatnich dni szwedzkiej pięknej, ale bardzo krótkiej jesieni, wybraliśmy się na zwiedzanie Kopenhagi. Miasto reklamowane mi przez wiele osób, jako warte zobaczenia, słynące z architektury portowej, wielu zabytków związanych z monarchią duńską oraz... Syrenki. Obiektu westchnień wszystkich turystów przyjeżdżających do Danii. No i polecane ze względu na dwie legendy: słynnego z serialu telewizyjnego szefa duńskiego gangu - Olsena, oraz krainy wolności - Christianii. Wszystko to powodowało, że zerwaliśmy się z łóżek skoro świt wczesnym sobotnim rankiem i wyruszyliśmy w prawie 500-kilometrową trasę. A w zasadzie 1000-kilometrową, bo planowaliśmy wrócić do Linköping tego samego dnia.';
$podroze1.='<p class="p1">O tym, że na szwedzkich autostradach nuda jest niemiłosierna - pisałem już wiele razy. Jeżeli dołożyć do tego szwedzkie auto w wersji luksusowej - jest jeszcze gorzej. Auto z potężnym silnikiem mogące rozpędzać się za pomocą swojej automatycznej skrzyni do grubo przeszło 200 km/h, toczyło się dostojnie z dopuszczalną tutaj prędkością 110 km/h, pochłaniając przy tym przeszło 10 litrów benzyny na 100 kilometrów, a my w środku czuliśmy się jakbyśmy stali w miejscu. Tylko przesuwający się za oknami krajobraz przypominał nam że jedziemy. Ale po trzech godzinach byliśmy w Helsinborg, zaparkowaliśmy samochód na promie i pobiegliśmy na górny pokład napić się kawy i obfotografować okolicę.';
$podroze1.= foto_line('szwecja2012/kopenhaga/kopenhagaa',2,1,'_s');
$podroze1.='<p class="p1">Na górnym pokładzie - pierwsza oznaka, że płyniemy do Danii: wiało “jak cholera”. Nadużywam może tego słowa, ale właśnie pod hasłem “Olsen, klawo jak cholera” upłynęła nam cała wycieczka, a humory dopisywały wyśmienicie, więc myślę, że wybaczycie mi to słownictwo. W Szwecji wieje, owszem. Nawet mogę powiedzieć, że dni bez wiatru zdarzają się sporadycznie, ale tutaj to była wichura taka, że nie można było ustać na nogach, czy utrzymać stabilnie  aparat, a pełny kubek z kawą postawiony na stoliku czy podłodze przewracał się jak domek z kart pod wpływem dmuchnięcia... I to nie był wyjątek, co poświadczyli moi koledzy płynąc tędy kilka tygodni później i poświadcza również duńskie społeczeństwo stawiając wiatraki gdzie popadnie.';
$podroze1.='<p class="p2"><b>Zamek Kronborg</b>';
$podroze1.='<p class="p1">Prom płynie tylko 20 minut, a zbliżający się Hesingør powitał nas zabudowaniami portowymi i potężnymi murami zamku Kronborg, fortecy spełniającej tu niegdyś takie samo zadanie jak nasz Kamieniec na kresach wschodnich. Szwedzi próbując atakować Duńczyków nie mieli lekko: najpierw cieśnina, którą trzeba przepłynąć, a jak już przepłynęli to nadziewali się wprost na ogień z kilkudziesięciu ustawionych na szańcach potężnych duńskich armat. Oczywiście Duńczycy mieli podobnie - Szwecję broniła nie tylko dzika natura, ale także twierdza Helsingborg. Niestety została z niej tylko jedna wieża. Ale historia wojen szwedzko-duńkich jest bardzo bogata, a Szwedzi nie zawsze byli tak pokojowym narodem, na jaki kreują się od dwustu lat.';
$podroze1.= foto_line('szwecja2012/kopenhaga/kopenhagab',2,1,'_s');
$podroze1.='<p class="p1">Zatrzymaliśmy się na chwilę pod zamkiem, zwiedziliśmy dziedziniec, pospacerowaliśmy po murach i po plaży nad brzegiem cieśniny Sund, po czym wsiedliśmy do samochodu i pojechaliśmy w dalszą drogę do Kopenhagi, tym razem po duńskiej E20 i... W zupełnej ciszy. O ile szwedzki asfalt jest bardzo głośny (ale i bardziej wytrzymały na warunki klimatyczne i powszechnie używane opony z kolcami), o tyle duński jest typowo europejski (pojawiają się dziury) i bezgłośny. W samochodzie zrobiło się cichutko jak makiem zasiał.';
$podroze1.='<p class="p2"><b>Kopenhaga</b>';
$podroze1.='<p class="p1">Po niespełna godzinie drogi zaparkowaliśmy w centrum miasta płacąc niemałą sumę 300 DEK za całodzienny parking (jeżeli ktoś uważał, że parkowanie w Szwecji jest drogie, to się grubo mylił) i wyruszyliśmy na całodzienny spacer po mieście. Zaczęliśmy od zwiedzania królewskiej rezydencji Rosenborg.';
$podroze1.='<p class="p1">Pałac jest niewielki w porównaniu do austriackiego Hoffburg czy Schönbrunn, ale i tak jest wiele do zwiedzania. Na każdym piętrze wystawa dedykowana osobnej epoce, a w podziemiach skarbiec z drzwiami jak do sejfu centralnego w banku szwajcarskim. Tak na moje oko były grubości zamkowej kamiennej ściany. A za tymi drzwiami ochrona, szklane gabloty, a w nich pamiątki jednej z niegdyś najbogatszych monarchii w Europie wraz z pięknie i przebogato zdobionymi relikwiami koronacyjnymi.';
$podroze1.= foto_line('szwecja2012/kopenhaga/kopenhagac',2,1,'_s');
$podroze1.='<p class="p1">Przed zamkiem - piękny ogród, w którym dominowały róże. Może dlatego zamek nazywa się Rosenborg? W parku przypałacowym przeważała zieleń. Niby nic szczególnego, jak na wrzesień, ale... My przyjechaliśmy ze Szwecji. I uwierzcie mi, że poza głośnością opon na asfalcie to była druga rzecz, którą natychmiast się tu zauważa. Zieleń. Było jej mnóstwo. Drzewa były wręcz puszyste od liści, trawa gęsta i ciemnozielona, a kwiaty w pełni korzystały z wczesnojesiennego słońca. Wciągając głęboko powietrze wchłaniałem tą zieleń całym sobą, wiedząc że wieczorem z powrotem będę już w szwedzkiej szarej rzeczywistości. Czy rzeczywiście aż taka jest różnica pomiędzy tymi rejonami? Ano jest. We wschodniej Szwecji okres wegetacji roślin jest bardzo krótki: kiedy w Danii pod koniec kwietnia jest już zielono i biało od kwitnących drzew - w Östergötland wypuszczają one zaledwie pąki. Kiedy we wrześniu w Kopenhadze cieszymy się ciepłymi dniami i słońcem - w Szwecji ciągle pada. Ot tak subtelna różnica: niby to tylko niespełna pięćset kilometrów, a jednak widać ją gołym okiem.';
$podroze1.='<p class="p2"><b>Mała Syrenka</b>';
$podroze1.='<p class="p1">Spacerkiem przeszliśmy do portu, mijając po drodze twierdzę Kastellet, jedną z najlepiej zachowanych twierdz obronnych w Europie. Zbudowana na planie pentagramu i mieszcząca na swoim terenie zeszłowieczne koszary wojskowe, w naszych czasach zupełnie straciła znaczenie strategiczne. O ile niegdyś takie twierdze łatwo było ukryć wśród otaczających ją wzgórz i lasów, o tyle w naszych czasach, gdy można można robić zdjęcia z powietrza tego rodzaju twierdze mogą służyć jedynie jako pamiątki dla potomnych. I do tego służą.';
$podroze1.='<p class="p1">W porcie napotkaliśmy grupę ludzi fotografującą coś, czego z daleka nie było widać. Podeszliśmy bliżej i naszym oczom ukazała się słynna kopenhaska syrenka, postać wzięta z baśni “Mała Syrena” Hansa Christiana Anderssena. Syrenka rzeczywiście jest mała i poza tym, że jest to sławny kawałek metalu, nic więcej nie mogę o niej powiedzieć. Doskonałą kopię chętni mogą sobie obejrzeć w kraju - w Łodzi w pasażu Rubinsteina. Dla Duńczyków jednak ma duże znaczenie: oblewają ją na przykład farbami na znak protestu, czy nawet był przypadek, że odcięto jej głowę, no i jest jedną z największych atrakcji turystycznych Kopenhagi, więc i nam nie wypadało jej pominąć.';
$podroze1.='<p class="p2"><b>Centrum</b>';
$podroze1.='<p class="p1">Zrobiliśmy się nieco głodni, więc skierowaliśmy się w kierunku centrum, tym razem mijając po drodze piękną fontannę Gefion Fountain, przedstawiającą gromadę zwierząt poganianych prze legendarną boginię ze skandynawskiej mitologii - Gefjon. Kilka zdjęć na tle fontanny w rytmie burczących brzuchów i dalej w drogę na poszukiwanie jedzenia.';
$podroze1.='<p class="p1">W centrum ludzi jak mrówek. Trafiliśmy akurat na mecz eliminacji Mistrzostw Świata w Piłce Nożnej pomiędzy Danią a Czechami. Kibice jednej i drugiej drużyny zajęli cały deptak restauracyjny przy kanale portowym, włączając w to wszystkie restauracje i wypijając chyba wszystkie beczki piwa w mieście. Przez najbardziej turystyczną część miasta ciężko było się przecisnąć, a co dopiero gdzieś usiąść i zamówić jedzenie. Przeszliśmy zatem do realizacji planu B (ach ten Olsen), i poszukaliśmy mniejszej knajpki w jednej z bocznych uliczek. Całe szczęście udało nam się jedną znaleźć niedaleko od głównego deptaka. Jedzenie w takich restauracyjkach zawsze jest podszyte ryzykiem, czy aby na pewno zdąży się znaleźć toaletę na czas, ale ma też swój urok:
<p class="p1">- Hallo my friends! - zagaił właściciel zajmując posturą całą przestrzeń za ladą.
<p class="p1">- Głodni jesteśmy - odpowiedzieliśmy chórem.
<p class="p1">- No to nie mogliście lepiej trafić. Proponuję pizzę, albo... Pizzę. A w promocji dodaję półtoralitrową Coca-Colę gratis do dwóch sztuk pizzy. Pasi?
<p class="p1">- Pasi - odpowiedzieliśmy ponownie chórem. - Chcielibyśmy zapłacić kartą. Można?
<p class="p1">- Można, ale nie dziś, bo terminal się zepsuł - odpowiedział właściciel z taką miną, jakby ten terminal kiedykolwiek był czynny, gdy tuż obok bawi się kilka tysięcy osób. Płacenie kartą nigdy nie sprzyja dawaniu napiwków.
<p class="p1">- A to my nie mamy duńskich koron - odpowiedzieliśmy w rytmie marsza naszych kiszek.
<p class="p1">- A jakie pieniądze macie?
<p class="p1">- No polskie złote, szwedzkie korony...
<p class="p1">- Szwedzkie korony? Mogą być - ucieszył się nasz dobroczyńca i przyszły karmiciel. - Pieniądz jest pieniądz - zakończył z szerokim uśmiechem.
<p class="p1">Już po chwili delektowaliśmy się skomponowanymi przez nas osobiście pizzami popijając dużymi ilościami Coca-Coli na tak zwany “wszelki wypadek”. “Wszelkiego wypadku” jednak nie było, a my z pełnymi brzuchami wytoczyliśmy się na dalsze zwiedzanie miasta. A następnym punktem programu była';
$podroze1.='<p class="p2"><b>Christiania</b>';
$podroze1.='<p class="p1">Przez jednych uznawana za krainę wolności, przez innych - miejsce gdzie legalnie mogą uzupełnić swoje zapasy narkotyków. Na pewno i jedno i drugie jest prawdą. Ale prawdą także jest to, że przez tą dzielnicę codziennie przechodzą tysiące turystów, niewiele robiących sobie z obowiązującego tam zakazu fotografowania, a samochody stojące na ulicach skutecznie zaprzeczają zakazowi ruchu drogowego. Rzędy straganów, na których można było kupić różnego rodzaju pamiątki, od “rasta” wisiorków poprzez flagi tej niezależnej niby dzielnicy, potęgowały tylko komercyjny charakter tego miejsca. Wystarczyło jednak zejść z głównej uliczki, a płynące z okien i otwartych na oścież drzwi squatów dźwięki bluesa przeniosły nas do czasów Jimiego Hendrixa i innych artystów dawnej hippisowskiej Ameryki. Christiania pokazywała swoje drugie, prawdziwe oblicze.';
$podroze1.='<p class="p2"><b>Kościół Najświętszego Zbawiciela</b>';
$podroze1.='<p class="p1">Po drodze do Christianii minęliśmy kościół z charakterystyczną szpiczastą wieżą w kształcie spirali. To znaczy wieża nie była w kształcie spirali, ale wrażenie to tworzyły okalające wieżę schody prowadzące na sam czubek wieży, o czym przekonaliśmy się naocznie później, kiedy to już wracaliśmy w stronę miasta. Konsultacje na temat tego, czy wchodzimy na dziewięćdziesięciometrową wieżę solidarnie potrząść spodniami ze strachu, czy też nie, trwały dość długo, ale po burzliwych naradach na temat braku czasu i podsumowaniu pozostałej nam duńskiej waluty okazało się, że starczy jej na bilety dla trzech osób. Na moje nieszczęście Piotrek uparł się, że on tam na górę wejdzie podobnie jak były premier, to znaczy jak wróci z Radomia, a ponieważ do Radomia się w najbliższym czasie nie wybiera, nie pozostało mi nic innego jak iść za Zbyszkiem i Markiem walczyć z moim lękiem wysokości na szczycie jednego z dwóch najwyższych kopenhaskich kościołów..';
$podroze1.= foto_line('szwecja2012/kopenhaga/kopenhagad',2,1,'_s');
$podroze1.='<p class="p1">Widok z tarasu był niesamowity, ale nie mógł równać się z tym z samego szczytu wieży. Jak już wspominałem wcześniej, schody zwężające się coraz bardziej prowadziły aż do samego wierzchołka, a na samym końcu były tak wąskie, że trzeba było przeciskać się bokiem. Znam to z opowiadań moich kolegów, gdyż ja aż tak wysoko nie doszedłem. Wysokość, średnio solidnie wyglądająca barierka sięgająca tylko do pasa oraz bardzo silny wiatr spowodowały, że udało mi się wejść tylko jeszcze dwa okrążenia w stronę szczytu powyżej balkonu widokowego. Pewnie wchodziłbym jeszcze tak stopień po stopniu wyżej i wyżej, ale dwóch rozbawionych i pijanych jak bela przedstawicieli wschodnich krajów zbiegających z góry jak rącze jelenie i potrącających wszystkich przechodniów po kolei, skutecznie mi ten pomysł wybiło z głowy. Ale już stąd można było zobaczyć słynny most łączący Danię ze Szwecją, którym już niedługo mieliśmy wracać do domu.  Najtrwalsze wspomnienie z wieży? - Wiało jak cholera, panie Olsen!';
$podroze1.='<p class="p2"><b>Centrum po raz drugi</b>';
$podroze1.='<p class="p1">Piotrek miał pewien plan. Co prawda spis zabytków był konkretny, ale było ich tak dużo, że trudno mi je wszystkie wymienić z pamięci i nawet stwierdzić, czy koło wszystkich przeszliśmy. Zwiedzając zawsze mam dylemat, czy robić “sposobem japońskim” mnóstwo zdjęć, a potem je w domu oglądać, czy skupić się na oglądaniu. I coraz częściej skłaniam się ku temu drugiemu. Zdjęcia leżą zarchiwizowane na dysku i nie wiem, czy poza albumami udostępnionymi na adventure.pl czy na Facebooku, jeszcze kiedykolwiek do nich zajrzę. Mam wrażenie, że częściej wracam do opisów miejsc, w których byłem, niż do setek zdjęć, które wtedy zostały zrobione, czy to przeze mnie, czy przez inne osoby. Nawet czytając książki wielkich podróżników, takich jak Tony Halik czy Ferdynand Ossendowski, skupiam się na tekście, a te kilka zdjęć dołączonych do książek przyciąga mój wzrok na zaledwie kilka sekund, utrwalając jedynie obraz opisany słowami. Wracając do tematu - Kopenhaga jest inna niż myślałem. Zawsze wyobrażałem ją sobie jako stare zabytkowe portowe miasto, z mnóstwem tawern, gdzie życie skupione jest w pobliżu portu, ale wyobraźnia to jedno, a rzeczywistość drugie. A rzeczywistość jest taka, że stolica Danii podobnie jak większość starych miast ulegała w przeszłości pożarom, a co za tym idzie nowa zabudowa powoli zastępowała starą. W Kopenhadze możemy więc zobaczyć elementy różnych architektonicznych stylów, zarówno tych charakterystycznych dla państw skandynawskich, jak i tych zachodniej i wschodniej Europy. Nie znaczy to, że Kopenhaga mi się nie podoba, ale nie znaczy to też, że wracałbym tam równie chętnie jak do Wiednia czy Lwowa.';
$podroze1.='<p class="p2"><b>Powrót do domu</b>';
$podroze1.='<p class="p1">We wrześniu dni są coraz krótsze i ciemno robi się już przed dwudziestą, więc przy zachodzącym słońcu przeszliśmy przez główny turystyczny deptak odwiedzając po drodze liczne sklepy z pamiątkami, po czym wybraliśmy się na poszukiwanie naszego Volvo. Przed nami była jeszcze jedna atrakcja do zobaczenia: blisko piętnastokilometrowy most łączący Kopenhagę z Malmö. Przeprawa zaczyna się ponadtrzykilometrowym tunelem, potem przejeżdża się cztery kilometry po sztucznej wyspie, a na koniec prawie osiem kilometrów pędzimy autostradą po morzu. Wokół nas po cieśninie Sund pływają statki, a w oddali widać światła szwedzkiej metropolii. Co dziwne, kontrola celna i zakup biletów na przejazd mostem odbywa się na samym końcu mostu - już w Malmö. Ciekawe co by było, gdyby nie działała któraś z naszych kart kredytowych, bo nie mogłem dopatrzyć się miejsca do zawrócenie w stronę Kopenhagi. Ale jak znam tutejsze rejony Skandynawowie na pewno mają na to jakąś procedurę.';
$podroze1.='<p class="p1">Nasze karty jednak nie zawiodły i już po chwili mknęliśmy ponownie z zawrotną prędkością 110 km/h po głośnej szwedzkiej autostradzie w kierunku domu. Linköping przywitało nas już po północy...  <i><font size=-4>rs, Kopenhaga, wrzesień 2012</font></i>';
$podroze1.='<p class="p2">Więcej zdjęć znaleźć można pod <a href="http://www.facebook.com/media/set/?set=a.4720982300612.189291.1176186605&type=1&l=7295644058">adresem</a>';

//  $podroze1.= foto_line('ochodzita2007/karczma',3,9,'_s');
include 'podr_sma.php';
//require_once("funkcje.php");
//data_index($podroze1,'meta data próbne ąśćŚ');
?>
