<?php
  include 'funkcje.php';
  include 'conf.php';

	$podroze1 = '<p class="p4">Lwów, 12-30 stycznia 2010';
    $podroze1.= '<p class="p3">Część I';
    $podroze1.= '<p class="p1">No i jestem we Lwowie po raz kolejny. Tym razem zimą. Tym razem z  bratem, więc będę miał okazję jeszcze raz obejrzeć prawie cały Lwów przy okazji pokazując mu co fajniejsze miejsca.
    <p class="p1">Kiedy malutki 40-miejscowy śmigłowy ATR dotknął kołami pasa startowego na miejskim lotnisku nieliczni pasażerowie, w tym ja i Marcel, odetchnęli z ulgą. Pogoda nie nastrajała do lądowania zbyt optymistycznie, jak to określił pilot - byliśmy na granicy możliwości wylądowania. Ciekawe jaką inną opcję mieliśmy przy maksymalnym zasięgu 1000 km, chyba tylko powrót do Warszawy. Potem już tradycyjnie: wypełnianie kartek wjazdowych, pieczątki w paszporcie, czekający pan Jarosław i niedługo potem byliśmy w swoim mieszkaniu w śródmieściu.
    <p class="p1">Lwów nie zmienił się nic od czasu mojego ostatniego pobytu. No może przesadziłem oczekując zmian, bo to przecież nie Bangkok, żeby mieszkańcy uczyli się swojego miasta od nowa co miesiąc. W związku ze zbliżającymi się wyborami gdzieniegdzie pojawiły się plakaty z twarzami Julii i Wiktora, ale było ich okrutnie mało w porównaniu z oplakatowaniem całych miast przed wyborami w Polsce. Wybory też przebiegły spokojnie, wbrew oczekiwaniom i chyba nadziejom niektórych naszych dziennikarzy i polityków, którzy zadowoleni byliby gdyby coś było nie tak. Podobnie pewnie zadowoleni byliby, gdyby UEFA zabrała Ukrainie EURO 2012, a my byśmy je zrobili "z Niemcami" jak to określił pewien niedawno wybrany prezes Polskiego Związku Piłki Kopanej. Ale nic z tego. I dobrze, bo co niektórzy już zapomnieli, że te mistrzostwa, to my w zasadzie dzięki Ukrainie dostaliśmy. Czasem grupki ludzi, przeważnie starszych, spotykają się w umówionym miejscu, np. pod pomnikiem Szewczenki na Prospekcie Swobody i dyskutują zawzięcie kto będzie lepszym prezydentem.';
    $podroze1.= foto_line('lviv2010/srod',3,4,'_s');
    $podroze1.= '<p class="p1">Jeżeli już jesteśmy na Prospekcie Swobody, przed operą stoi potężna choinka, pięknie ubrana i oświetlona, a wzdłuż deptaka mnóstwo drewnianych budek, gdzie można kupić lokalne wyroby spożywcze, zjeść kiełbaski lub napić się grzanego wina.
    <p class="p1">Kiermaszowe budki stoją również na rynku. Oprócz tego ustawiono tam w miejscu, gdzie latem był ogródek piwny, pełnowymiarowe lodowisko. Rynek bez komercyjnych i użytkowych rozmaiceń udało mi się zobaczyć tylko w październiku, podczas poprzedniego pobytu we Lwowie.';
    $podroze1.= foto_line('lviv2010/gora',3,3,'_s');
    $podroze1.= '<p class="p1">Żeby wejść na Wysoki Zamek trzeba "upolować" pogodę. Próbowaliśmy z Marcelem dwa razy. Raz weszliśmy akurat w chmurę, więc nie było widać kompletnie nic. Czekaliśmy jakiś czas, a gdy już zdecydowaliśmy się zejść, wyszło słońce. Ale powiedziałem, że w tym samym dniu to ja za Chiny Ludowe tam drugi raz nie wejdę. Poszliśmy więc na spacer na Cmentarz Łyczakowski zostawiając sobie górę na lepsze czasy.
    <p class="p1">Lepsze czasy jak się okazało nastały nazajutrz. Widok z góry jest  naprawdę niesamowity, a zimą chyba jeszcze lepszy, bo o tej porze roku na zbyt wielu turystów. Latem jest tutaj tłum. Marcel nawet zastanawiał się, ile to możnaby zarobić stawiając na szczycie automat z napojami. Nie powiem, bo sam pewnie bym skorzystał z przyjemnością.
    <p class="p1">Żeby uzupełnić widok Lwowa z góry weszliśmy na ratuszową wieżę, która, o dziwo, zimą też jest czynna. Tutaj już jest więcej chętnych do oglądania niż na Wielkiej Górze, poza tym trzeba bardzo uważać, bo jest okrutnie ślisko.';
    $podroze1.= foto_line('lviv2010/skansen',3,6,'_s');
    $podroze1.= '<p class="p1">Lwowski skansen, czyli po tutejszemu Gaj Szewczenki, zimą jest również otwarty, a przynajmniej w niedzielę. A w śnieżnej scenerii prezentuje się zupełnie inaczej niż latem - tak jakoś dostojniej i... Chyba groźniej. Można się zmęczyć chodząc po zaśnieżonych dróżkach, a żeby przejść cały ten bałagan trzeba poświęcić od dwóch do trzech godzin. Niestety w porównaniu do letniej pory otwartych jest tylko kilka nielicznych chatek i jedna cerkiew.
    <p class="p1">Z dnia na dzień robi się coraz zimniej, a na weekend synoptycy tutejsi zapowiadają do 26 stopni mrozu. Norweska strona pogodowa - nieco mniej, bo tylko 20. Ja osobiście poniżej -20 stopni różnicy już nie odczuwam - trzeba po prostu dać myślom zamarznąć i polubić to zimno. Ciepłe mieszkanie wtedy wydaje się jeszcze bardziej przytulne.';
    $podroze1.= '<p class="p3">Część II';
    $podroze1.= '<p class="p1">W weekend zgodnie z zapowiedziami synoptyków było tak, zimno, że myśli zamarzały. Temperatura spadła do około -20 stopni Celsjusza, więc plany wyjazdu poza Lwów przełożyłem na inną, bardziej przyjazną dla organizmu porę roku, a teraz, korzystając z bliskiego położenia, odwiedziłem dwa muzea. Pierwsze z nich to Muzeum Etnografii i Przemysłu Artystycznego, "gdzie można obejrzeć wiele strojów ludowych ze wszystkich części Ukrainy oraz wystawy przedstawiające zajęcia gospodarskie, produkcję tkanin i wyposażenie domów", jak zapowiada przewodnik Pascala.
    <p class="p1">Miałem wrażenie, że chyba pomyliłem muzea, bo najciekawsze, co zobaczyłem, to... Sam budynek, a w zasadzie potężna pałacokamienica, w której niegdyś mieściła się Galicyjska Kasa Oszczędności. W holu przed schodami zmieściła się wielka kareta, a i tak sporo miejsca zostało na kasę i sklepik z pamiątkami. Muzeum obejmuje dwa piętra. Sale są piękne, a to co w salach nie. Na drugim piętrze obejrzałem kilka strojów, parę mebli, wystawę porcelany i dość sporą, trzeba przyznać, kolekcję zabytkowych zegarów z różnej części Europy, ale bynajmniej nie z Ukrainy. Na trzecim - wystawkę naszyjników koralikowych tak charakterystycznych dla ukraińskich strojów ludowych i dwa pokoje ikon i innych obrazków o tematyce religijnej. Po muzeum etnografii spodziewałem się nieco więcej, a jest ono tak mizernie wyposażone, że turysta może pomyśleć, że Ukraina nie ma tradycji sięgających głębiej niż początek XIX stulecia. A i te eksponaty tak trochę na siłę szukane. Bez żalu poszedłem więc do następnego muzeum.';
    $podroze1.= foto_line('lviv2010/rynek',3,4,'_s');
    $podroze1.= '<p class="p1">Lwowska Galeria Sztuki mieści się w dawnym pałacu Izabeli Dzieduszyckiej na ulicy Stefanyka, naprzeciwko Ossolineum. Zbiór jest rzeczywiście potężny, aczkolwiek kilku znaczniejszych tytułów wymienionych w wyżej wspomnianym przewodniku również nie znalazłem. Wybitnym znawcą malarstwa europejskiego nie jestem, ale żaluzje w oknach znacznie ułatwiłyby oglądanie tej sztuki w niektórych salach. Mimo wszystko uważam tę galerię za wartą odwiedzenia, jeżeli ktoś będzie miał trochę zbędnego czasu podczas pobytu we Lwowie. No i oczywiście warto zwrócić uwagę na budynek. Nowe instalacje, takie jak centralne ogrzewanie i elektryczne oświetlenie jarzeniowe nie są w stanie do końca ukryć potęgi i piękna ówczesnego budownictwa lwowskiego.';
    $podroze1.= '<p class="p3">Część III';
    $podroze1.= '<p class="p1">Trochę o kulinariach.
    <p class="p1">Jedzenie bardzo podobne do naszego w Polsce, pomijając oczywiście tradycyjne polskie "chińczyki" i "kebab bary". Niesamowicie popularna tutaj restauracja - Puzata Chata - serwuje teoretycznie ukraińskie jedzenie, ale jest ono przygotowane raczej pod turystów i okraszone łyżką śmietany do każdego dania. Z zup polecam "solankę" i zupę rybną. No i barszcz z "pampuszką". Jest tanio. Restauracje na Starym Mieście, już nie są tak tanie, ale bez przesady. Obfitują w dobre dania, każdy z pewnością coś dla siebie znajdzie. Jak nie, to pozostają jeszcze pizzernie, w których trzeba jednak na wstępie powiedzieć, że tych dodatków tam na pizzy to chcemy odrobinę więcej. Oczywiście przyjdzie nam za to dodatkowo zapłacić, ale otrzymamy pizzę, do jakiej jesteśmy przyzwyczajeni. Oczywiście wszystko ma odpowiednią do wschodniego stylu życia zawartość tłuszczu. Wszędzie można napić się piwa bądź kwasu chlebowego.
    <p class="p1">Piwo jest dobre - szczególnie żywe. W zasadzie każda szanująca się restauracja ma jakieś żywe piwo, czasem robione u siebie. Wzorowana na kulturze żydowskiej restauracja "Złota Róża" serwuje wyśmienite piwo własnej produkcji w dwulitrowych butelkach. Co do wódek: oczywiście w restauracjach warto spróbować "miedowuchy" robionej według lokalnych przepisów. W sklepach to już nie to samo. No i czarny Niemiroff. Nie, nie, w Polsce nie jest taki sam. Z mocniejszych alkoholi polecam jeszcze koniak "Zakarpacki". Ale musi na nim pisać "Zakarpacki". W takiej samej butelce są sprzedawane koniaki z trzema gwiazdkami zamiast napisu "Zakarpacki", ale to już nie to samo. Spotkałem się nawet ze stwierdzeniem, że na Ukrainie słowo "koniak" równa się słowu "Zakarpacki". Przynajmiej w jej zachodniej części.
    <p class="p1">Podobnie tłuste jak jedzenie w restauracjach są wędliny w sklepach, które są smaczne, aczkolwiek z łatwością można znaleźć w nich kawałki słoniny. Z "lokalnych" smakołyków - McDonald oferuje delikatnie zmodyfikowane menu. Coca-Cola ma tutaj wersję o smaku waniliowym, krówki w czekoladzie (koniecznie w białym papierku z narysowaną krową - reszta to podróby) - są wyśmienite i jest to rzecz najczęściej przywożona do Polski jako upominek dla znajomych. Musztarda... Jak ktoś myśli, że jadł rosyjską musztardę w Polsce, to... Myśli, że jadł rosyjską musztardę. Tutaj po odrobinie musztardy posiadającej w nazwie słowo "rosyjska", traci się oddech na jakiś czas. Widać nie dotarły tu jeszcze normy unijne. No i teraz to może nie, ale jak tylko jest odpowiednia pora, to zawsze są świeże owoce i warzywa. I jesienią arbuzy. Całe ciężarówki arbuzów.';
    $podroze1.= foto_line('lviv2010/ryby',3,3,'_s');
    $podroze1.= '<p class="p1">Miałem okazję być z tutejszymi kolegami na "gruzińskim szaszłyku". Jedzenia był cały stół,  około 15 osób, szaszłyków 5 rodzajów, o ilości ich nie wspomnę, zakąski, sery, poza tym niemała ilość butelek wódki i soków, która pozwoliła na posiedzenie do późnej nocy lub, jak kto woli, wczesnego rana. Wszystko to za cenę poniżej dwóch tys. UAH. Tak, tak, jak ktoś chce się porządnie najeść, to musi przyjechać na Ukrainę. A po czarnym Niemiroff-ie i po Perłowej głowa nie boli. Nawet po dużych ilościach.';
//  $podroze1.= foto_line('ochodzita2007/karczma',3,9,'_s');
include 'podr_sma.php';
?>

