<?php
  include 'funkcje.php';
  include 'conf.php';

  $podroze1 = '<p class="p3">Pijana wiśnia, czyli Lwów po latach<br>';
//Lwów, grudzień 2018
$podroze1.='<p class="p1">Podróżowanie zimą ma jedną wielką zaletę: brak tłumów. O ile oczywiście nie wybierasz się do jakichś narciarskich kurortów, bo te zimą oblegane są jak plaże Miami.';
$podroze1.='<p class="p1">Kiedy nadarzyła się okazja, żeby odwiedzić Lwów, nie zastanawialiśmy się z Ulą długo. Spędziłem w tym mieście z przerwami prawie pół roku w latach 2009-2010 i ciekaw byłem bardzo, co się od tego czasu zmieniło.
Tuż przed wyjazdem prezydent Poroszenko (prywatnie właściciel fabryki wszędobylskich we Lwowie słodyczy firmy „Roshen”) ogłosił stan wojenny dla Ukrainy. Całe szczęście tylko dla wschodniej części, więc nie musieliśmy rezygnować z naszej podróży.';
$podroze1.='<p class="p1">Pierwsze co mnie zaskoczyło, to nowe lotnisko. Wybudowany specjalnie z okazji Mistrzostw Europy w piłce kopanej w 2012 roku terminal jest ogromny. Niestety ludzi w nim tylu, co na nowym Dworcu Fabrycznym w Łodzi. Mówiąc bardziej malowniczo – przeciągi hulają, a wiatr trzaska okiennicami. Co ciekawe stary terminal, który opisywałem <a href=|http://adventurewrites.000webhostapp.com/lviv2009.php">w 2009 roku</a> nadal jest czynny i obsługuje loty czarterowe. Po wyjściu z lotniska już standardowo: trolejbus pamiętający czasy ZSRR, kasowniki jak te z bajki o wilku i zającu i ten Lwów, który pamiętam: kostka brukowa wszędzie, gdzie to tylko możliwe i niesamowite korki. Wszyscy trąbią na wszystkich, a zielone światlo na przejściu dla pieszych w żaden sposób nie gwarantuje bezpiecznego przejścia na drugą stronę ulicy. Stare miasto też jest jakie było: urokliwe uliczki, malowniczy rynek z ratuszem na środku, mnóstwo kościołów, przepyszne jedzenie (po którym obiecałem sobie, że już nigdy nie wrócę do staropolskiego tadycyjnego kebaba), i kioski z „pijaną wiśnią” okupowane przez grupy turystów chcących skosztować tego lokalnego napitku. Trzeba przyznać, że trunek wyborny i pozamiatał nam zupełnie piątkowy wieczór. Oczywiście w przyjemny sposób, bo było to powiązane ze spotkaniem ze starymi znajomymi sprzed lat. Co do trunków, to grzane wino serwowane na świątecznym jarmarku również było niczego sobie. Chociaż jak mówili tamtejsi koledzy, tylko dlatego, że to początek jarmarku. Pod koniec już takie dobre nie jest.';
$podroze1.='<p class="p1">Druga większa różnica to taka, że na Wysokim Zamku (taka wielka góra w centrum miasta z kolorową wieżą telewizyjną, gdzie stoją pozostałości średniowiecznego zamku ufundowanego przez Kazimierza Wielkiego – a w zasadzie kawałek jego ściany) można się napić kawy, herbaty i zjeść coś ciepłego. Pamiętam jak staliśmy tam z bratem dziewięć lat wcześniej w 20-stopniowym mrozie i marzyliśmy o kubku czegoś ciepłego do picia. Marzenie się spełniło. A warto tam się wdrapać, bo widok na miasto jest super.';
$podroze1.='<p class="p1">Super widok na miasto jest również z wieży ratuszowej – jezeli ktoś ma siłę włazić po schodach aż nad zegar – polecam. Polecam też wziąć czapkę, bo wieje tam na górze strasznie.';
$podroze1.='<p class="p1">To było tylko pięć dni, ale bardzo intensywne pięć dni. Pogoda była jaka była: deszcz, śnieg wiatr, naprzemian mróz i ocieplenie. Czasami przychodziliśmy do hotelu przemoczeni do suchej nitki, ale zadowoleni. To kolejny przykład na to, że w podróży ważniejsze jest dobre towarzystwo niż pogoda.';
$podroze1.='<p class="p1"><br>Zdjęcia można obejrzeć klikając <a href="https://www.facebook.com/media/set/?set=a.4087449302683.174530.1176186605&type=1&l=af9084f568">tutaj</a>';
$podroze1.= foto_line('lviv2018_',3,17,'_s');
$podroze1.='<p class="p1"><i><font size=-4>rs, Lwów, grudzień 2018</font></i>';
include 'podr_sma.php';


$podroze1.='<p class="p1"> Mistrz rozwałkował masę cukrową na płaski cieniutki placek, tak jakby chciał robić pierogi. Wziął następną porcję cukrowego ciasta, tym razem w kolorze czerwonym. Rozwałkował ponownie i nałożył ją na tą pierwszą. Spojrzał przed siebie. Zobaczył przyklejone do oddzielającej go od sklepu szyby rozpłaszczone twarze dzieciaków, uśmiechnął się i mrugnął do nich okiem. Co mniejsze oderwały się od wystawy w popłochu i wtuliły w ramiona swoich mam. Niedługo jednak ciekawość wzięła ponownie górę i przywarły z powrotem buziami do szyby.';
$podroze1.='<p class="p1">A mistrz pracował. Zwinął połączone ciasta w rulonik, tak jakby teraz miał przygotować kopytka. Nałożone kolory pięknie ułożyły się w biało czerwone skośne paski. Gdy już wałek osiągnął odpowiednią grubość, cukiernik wziął nóż i zaczął kroić go na malutkie plasterki. Po chwili zgarnął wszystko z blatu metalowego stołu, wrzucił do stojącej nieopodal przygotowanej na ten cel miski, wyprostował plecy aż trzasnęły stawy, spojrzał ponownie z uśmiechem na obserwujące go dzieci, po czym wziął wcześniej przygotowane naczynie i wszedł do sklepu. Cukierki były gotowe. Uciechom i piskom nie było końca.';
$podroze1.='<p class="p1">Wytwarzane ręcznie cukierki to specjalność małego szwedzkiego miasteczka Gränna, położonego niedaleko Jönköping w hrabstwie Småland, tuż nad drugim co do wielkości szwedzkim jeziorem Vättern. Większość sklepów położonych przy głównej ulicy miasta to właśnie sklepy z wytwarzanymi ręcznie cukierkami. Każdy z nich zbudowany tak, aby klienci mogli na bieżąco obserwować jak się robi ręcznie słodycze. Mamy więc tradycyjny sklep z ladą i półkami, gdzie stoją już gotowe posegregowane w szczelnych słoiczkach wyroby w różnych smakach - od smaku koli, poprzez owocowe, anyżkowe, a nawet słone. Ta część sklepu zazwyczaj oddzielona jest drugą szybą wystawową od zaplecza, gdzie znajduje się mini fabryka z jednym lub kilkoma stanowiskami pracy dla cukierników. W ten sposób Gränna walczy swoimi specjalnościami o turystów.';
$podroze1.='<p class="p1">Kiedy zwiedzałem to typowe dla Szwecji, zabudowane drewnianymi domami kolorowe miasteczko, był środek czerwca, więc sezon letni w Szwecji jeszcze się na dobre nie rozpoczął. Mimo to turystów było już wielu. W większości właśnie dzięki wytwarzanym ręcznie słodyczom, ale to nie jest jedyna atrakcja tego miejsca. Przechodząc wzdłuż głównej ulicy, tuż za kościołem znajdziemy ścieżkę wiodącą na pobliską górę, gdzie znajduje się punkt widokowy i mały skansen z kilkoma wiejskimi zabudowaniami z XIX i XX wieku. Z góry mamy obszerny widok na jezioro Vättern. Skłamałbym, gdybym napisał, że na całe jezioro. Jest ono potężne, wydłużone jak wrzeciono, jego obwód to około 300 km, a Gränna położona  jest na jego południowo-zachodnim końcu. Z góry widać więc doskonale ten koniec jeziora z malowniczo położonymi na brzegach miastami Huskvarna i Jönköping, wcinającę się w wodę pozostałości zamku Brahehus oraz malowniczą wyspę Visingsö, do której można dopłynąć kursującym z Gränny promem. Prawego brzegu jeziora nie byłem w stanie dojrzeć, mimo że pogoda była piękna i słoneczna. Widać było za to jak na dłoni jak dużo miejsc kempingowych jest po tej stronie wody, pustych niemalże jeszcze zupełnie w tym czasie i można tylko podejrzewać, że turystów za miesiąc w tym miasteczku będzie zdecydowanie więcej.';
$podroze1.='<p class="p1">Jak wspomniałem wcześniej, na górze nieopodal punktu widokowego znajduje się również skansen. Domki są otwarte do zwiedzania, a ich wyposażenie niewiele różni się od tych oglądanych w skansenach w Polsce. Mamy część kuchenną, gdzie zwykle jest piec, oraz część mieszkalną, wyposażoną w łóżko, stół i narzędzie do pracy, takie jak na przykład tkalnia, gdzie panie domu mogły spędzać długie białe noce. Co dziwne - piece zbudowane były podobnie jak piece chlebowe, więc chyba kiedyś w Szwecji chleb był bardziej popularny niż teraz. Teraz niby jest w sklepach, ale w niczym nie przypomina naszego polskiego chleba. Bardziej słodkie bułki. Ale co kraj to obyczaj i inne jedzenie. Zauważyłem, że ściany części mieszkalnych w niektórych chatach ozdobione są pięknymi malowanymi wprost na bielonych balach wzorami. Przeważają motywy kwiatowe, ale nie tylko. Można zauważyć rybaków w łodziach ciągnących sieci z rybami, czy łosie, których w tych rejonach zatrzęsienie.';
$podroze1.='<p class="p1"><center>***</center>';
$podroze1.='<p class="p1">Gränna jednak nie była głównym celem mojej podróży tego dnia. Stała się nim... Przez przypadek. Planowałem zobaczyć największy w tym rejonie Szwecji, wysoki na 20 metrów wodospad Stalpet. Wodospad (a w zasadzie dwa wodospady położone tuż koło siebie) nie jest jednak tak wysoki jak sobie wyobrażałem. Położony co prawda malowniczo wśród otaczającej go zieleni niestety nie wywarł na mnie dużego wrażenia. Po kilku chwilach zacząłem się zastanawiać, czy nie umilić sobie dzisiejszej wycieczki jakąś jeszcze jedną atrakcją turystyczną.';
$podroze1.='<p class="p1"><center>***</center>';
$podroze1.='<p class="p1">Pojechałem więc do Gränny. Po drodze, przejeżdżając przez miejscowość Husqvarna, znaną u nas w Polsce przede wszystkim z napisów na różnego rodzaju sprzętach ogrodniczych, zahaczyłem o kolejny punkt widokowy. Swoją drogą jest ich tutaj mnóstwo, ale nie ma co się dziwić, bo widoki na jezioro Vättern są przepiękne. O ile później w Grännie miałem piękną słoneczną pogodę, akurat teraz przed południem niebo było pochmurne, a z nieba siąpił zimny i nieprzyjemny deszcz. To też wizytówka letnich miesięcy w tych rejonach. Czasem jest tak, że mamy rano piękną pogodę, natomiast po południu chmurzy się i pada już do nocy. I tak może być kilka kolejnych dni, po czym pogoda zmienia się i rano jest deszczowo, natomiast po południu niebo się klaruje i jest pięknie i słonecznie. I tak znowu kolejny tydzień. Jak mamy cały słoneczny i ciepły dzień bez deszczu - można powiedzieć, że mamy szczęście. No i jeszcze wiatr. Wiosną wciąż jeszcze chłodny, a gdy zawieje z północy - wręcz mroźny. Dlatego zawsze warto mieć ze sobą jakąś lekką kurtkę przeciwdeszczową, które byłaby w stanie również ochronić od wiatru. Ale taka to już jest skandynawska aura i trzeba się do niej przyzwyczaić. Zimą zimno potrafi dać w kość, wiosna jest późno, jesień wcześnie, a lato bywa gorące tylko sporadycznie. Jak ktoś polubi taką pogodę - polubi również Skandynawię i będzie chciał tu wracać przy każdej nadarzającej się okazji. Zupełnie jak ja.';
$podroze1.='<p class="p1"><center>***</center>';
$podroze1.='<p class="p1">Jadąc autostradą A4 od Husqvarny w kierunku Sztokholmu do Gränny mamy około 30 kilometrów. Trasa wiedzie tuż przy jeziorze, więc widoki są również wspaniałe z samochodu. Szczególnie dla pasażerów, gdyż droga jest kręta i szybka, więc kierowca nie może sobie pozwolić na zbyt częste odrywanie od niej wzroku. Dlatego polecam jeżdżenie po Szwecji transportem lokalnym, szczególnie gdy jedziemy sami. Ceny paliwa są wysokie, a za autobus zapłacimy niewiele więcej niż gdybyśmy jechali własnym samochodem. Autobusy są duże i wygodne, a pociągi, nawet te lokalne, szybkie i klimatyzowane. A krajobraz możemy podziwiać wtedy do woli.';


include 'podr_sma.php';
//require_once("funkcje.php");
//data_index($podroze1,'meta data próbne ąśćŚ');
?>
