<?php
  include 'funkcje.php';
  include 'conf.php';

$podroze1 = '<p class="p3">Tam gdzie słońce nie zachodzi II<br>';
//Norwegia, 20160622
$podroze1.='<p class="p1">Ciężko się zebrać po pracy. Człowiek zmęczony, ma ochotę zadzwonić i powiedzieć, że nigdzie nie jedzie. W domu zawsze znajdzie się przecież coś ciekawszego do zrobienia. Na przykład można się położyć na kanapie i oglądać Mistrzostwa Europy w wielkiej kopanej. Ale potem w podróży wszystko jest inaczej. Jak już się człowiek zapakuje do samochodu i wyjedzie za miasto, świat robi się bardziej kolorowy. Pachnie przygodą.';

$podroze1.='<p class="p1">Droga do norweskiego parku narodowego Femundsmarka wiodła przez malowniczą Dalarnę. Ten region środkowej Szwecji znany jest w Polsce głównie z drewnianego konika, sprzedawanego na wszystkich lotniskach i promach jako pożegnalna pamiątka regionalna ze Skandynawii. Ciężko jest wybrać inną rzecz, która kojarzyłaby się tak jednoznacznie ze Szwecją, jak ten koń. Oczywiście produkt oryginalny jest wielki. Żeby zrobić sobie przy nim zdjęcie, trzeba się nieźle nakombinować. Stolicą Dalarny jest Falun z górującymi nad okolicą skoczniami narciarskimi. Oglądaliśmy je tylko z okna samochodu, bo czas gonił, a potem pojechaliśmy w stronę Mory, ze słynną fabryką szwedzkich noży. Mora to dla tubylców tak uznana marka dla noży jak Stihl i Husqvarna dla pił łańcuchowych, albo Fiskars lub Hultafors dla siekier. Szkoda jednak, że się nie zatrzymaliśmy choć na chwilę, bo - wiadomo - jak postoju nie zrobi się od razu, to potem już w drodze powrotnej tym bardziej nie chce się zatrzymywać, kiedy wszystko boli po trzydniowej włóczędze z prawie dwudziesto-kilogramowym ekwipunkiem na plecach. W drodze powrotnej zatrzymaliśmy się za to w Ratvik, małym miasteczku z najdłuższym molem w Szwecji: 693 metry pomostu sięgającego do środka jeziora. Nie ma co się rozpisywać jednak na ten temat, bo zwiedzanie Dalarny przejazdem nie ma moim zdaniem większego sensu. Trzeba tu przyjechać na dłuższy czas.';

$podroze1.='<p class="p1">Rozbiliśmy się około drugiej w nocy w lesie nieopodal kempingu w norweskim Elga. Zimno, tylko cztery stopnie na plusie, jak na koniec czerwca bez rewelacji. Całe szczęście pogoda miała w nosie wszelkie prognozy i nie padało. Dziwnie myśleć o nocy w środku polarnego dnia, ale żeby jakoś funkcjonować, trzeba byłoby się chociaż kilka godzin zdrzemnąć. Szybko zagotowaliśmy więc wodę na herbatę, wrzuciliśmy coś na ząb i do namiotu. Do snu kołysało nas wycie wilków, których tu na pograniczu norwesko szwedzkim jest około setki. Niby wiadomo, że u nas w Polsce jest ich więcej, że nie atakują człowieka, ale po wielogodzinnej podróży, w cienkim letnim namiocie, gdy na zewnątrz zimno jak diabli, odbiera się to trochę inaczej. A góry jeszcze potęgowały wrażenie.';

$podroze1.= foto_line('midsommar2016/dzien1_',3,12,'s');

$podroze1.='<p class="p1">Drugiego dnia rano odwiedziliśmy kemping Elga w poszukiwaniu mapy. Było ciężko, bo z okazji Midsommar (taka północna odmiana polskiej nocy świętojańskiej) w Norwegii, podobnie jak w Szwecji, wszystko jest pozamykane. Udało nam się sfotografować ukradkiem jakąś lokalną mapę za milion koron na stacji benzynowej i ruszyliśmy w kierunku góry Elgahogna - najwyższego szczytu tego pasma. Droga wiodła najpierw przez las, a potem roślinność stawała się coraz niższa. Na wysokości około 800 m npm rosły już tylko karłowate brzozy, z których “pożyczyłem” trochę kory na rozpałke, bo na szczycie góry planowaliśmy obiad. Oprócz tego karłowate krzewy i mnóstwo strumyków z krystalicznie czystą wodą, zimną jak diabli. Potem już było coraz gorzej, coraz zimniej i coraz bardziej kamieniście. Ostatnie 200 metrów to strome podejście po dużych kamieniach, które usuwały się spod butów. Myślę, że to ostatni raz, kiedy wybrałem się w góry bez kijków trekkingowych. Warto jednak było się pomęczyć, bo widok z góry nie do opisania. Można tylko popatrzeć na zdjęcia, ale one też nie są w stanie oddać piękna tej krainy. Ale można obejrzeć film poniżej :)';

$podroze1.='<p class="p1"><iframe width="280" height="157" src="https://www.youtube.com/embed/cvngSEQnapI" frameborder="0" allowfullscreen></iframe>'; 

$podroze1.='<p class="p1">Obiad - jak wiemy - fajna sprawa. Jak zjemy coś na ciepło i napijemy się gorącej herbaty lub kawy, to humor poprawia się od razu i nawet  w strzelającym mrozie można na rybach siedzieć cały dzień. Dlatego sprytnie zaplanowaliśmy sobie posiłek dopiero, jak już wejdziemy na sam szczyt. Ale żeby dodatkowo nie dźwigać Prymusa, wzięliśmy ze sobą na górę tylko kuchenkę survivalową na patyki. Tylko że... na szczycie były same kamienie. Całe szczęście zostały jakieś resztki połamanej skrzynki, więc porąbałem ją nożem na patyki i korzystając z rozpałki z kory brzozowej rozpaliliśmy ogień. Niestety drewno było mokre, wiało jakby chciało głowę urwać, więc rozpalenie ognia graniczyło z cudem. W końcu jednak po kilkunastu minutach mogliśmy delektować się obiadem z torebek podróżniczych (Travellunch) i gorącą kawą.';

$podroze1.='<p class="p1">Zwykle wolę wchodzić na górę niż z niej schodzić, ale zawsze kiedyś przychodzi taki czas, że zejść trzeba. Jedną z zalet schodzenia jest jednak to, że widzi się cały krajobraz przed sobą kiedy nie zasłaniają go góry. Widok surowych szczytów z leżącymi w dolinach płatami śniegu wynagradza wszelkie niedogodności.';

$podroze1.= foto_line('midsommar2016/dzien2_',3,12,'s');

$podroze1.='<p class="p1">Jak już zeszliśmy na sam dół, to okazało się że pogoda posłuchała a jednak prognozy meteorologów i rozpadało się na całego. Dalsze przewidywania również nie były optymistyczne, zapakowaliśmy się więc do samochodu i przejechaliśmy przez granicę na szwedzka strone do parku Fulufjället.';

$podroze1.='<p class="p1">Tam po godzinie deszczowej wspinaczki na płaskowyż dotarliśmy do pierwszej na naszej drodze chatki traperskiej. Co prawda była już częściowo zajęta przez innych podróżników - mamę z dwojgiem około dziesięcioletnich chłopców, ale dwa lóżka się znalazły. Najważniejsze, że było ciepło, sucho i można było wysuszyć ciuchy i ekwipunek. Zawsze to lepsze niż cienki namiot, kiedy na dworze leje jak z cebra. Towarzystwo odpoczywało tam już od dwóch dni. Głównie spacerowali po górach i łowili ryby. Za długo jednak nie pogawędziliśmy - trzeba było iść spać, żeby rano ruszyć w dalszą drogę.';

$podroze1.='<p class="p1">My też próbowaliśmy łowić ryby, ale bez większych sukcesów. W tutejszych jeziorach było mnóstwo pstrągów, ale małych. Po norweskiej stronie podobno jest ich więcej i większych, lecz jak już wspomniałem pogoda pokrzyżowała nam plany i nie mieliśmy okazji sprawdzić. Cóż, będzie powód, aby wybrać się w norweskie góry jeszcze raz.';

$podroze1.='<p class="p1">Trzeciego dnia rano zorganizowaliśmy sobie event “Janusze Survivalu”. Przepakowaliśmy wszystko, co wydawało nam się już niepotrzebne, z plecaków do reklamówek i zostawiliśmy resztę dobytku w plecakach w chatce, skąd mieliśmy po południu wyruszyć w dalszą drogę. Z reklamówkami z System Bolagetu (szwedzka sieć sklepów monopolowych) jak Janusze Survivalu zeszliśmy z góry z powrotem na parking. Potem wyposażeni już w mniejsze plecaki, które mieliśmy nadzieję, że później po zjedzeniu zapasów zmieszczą się w większe, zostawione w chatce na górze, wyruszyliśmy do wodospadu Njupeskär, który jest największą atrakcją parku tego rezerwatu i zarazem najwyższym wodospadem w Szwecji (93 m spadu). Widok z dołu super, mam nadzieję, że na zdjęciach chociaż częściowo to udało się zaprezentować. Potem, nie korzystając już ze standardowego szlaku turystycznego okupowanego przez niemieckich i japońskich turystów-emerytow, ruszyliśmy tam, gdzie wodospad się zaczyna, czyli na samą górę, po drodze mijając naszych zeszłonocnych współlokatorów. Mam wielki szacunek dla tych małych piechurów - i wielki podziw dla ich mamy - że od najmłodszych lat pokazuje im to, co w życiu najpiękniejsze - czyli surowa naturę. Na pewno tego nie zapomną i będą pokazywać to samo później swoim dzieciom.';

$podroze1.='<p class="p1">Z góry wodospad wyglądał zdecydowanie groźniej niż z dołu, szczególnie jak się ma lęk wysokości. A ja mam straszny. Walczę z tym jak mogę, ale wspinaczem wysokogórskim raczej nie zostanę. Na skoki na bungee również nie dam się namówić.';

$podroze1.='<p class="p1">Po obejrzeniu wodospadu zarówno z dołu jak i z góry wróciliśmy do chatki, gdzie zostawiliśmy plecaki, zatrzymując się po drodze nad jeziorem, żeby się trochę upodobnić do ludzi (wykorzystując super pogodę, bo właśnie przestało padać i wyszło słońce) i połowić ryby. Strasznie kamieniste i płytkie te tutejsze jeziora. Do wody trzeba było wchodzić na czworaka, a i to nie jest najbezpieczniejsze. Całe szczęście woda zdecydowanie cieplejsza niż w “leśnym kranie”, czyli górskich strumykach. Szału nie było, ale chociaż do 15 stopni wydawało się, że jest przy brzegu nagrzana.';

$podroze1.= foto_line('midsommar2016/dzien3_',3,8,'s');

$podroze1.='<p class="p1">W chatce zjedliśmy wykwintny jak na obozowe warunki obiad przy normalnym stole, jeszcze troszkę czasu spędziliśmy na niespiesznym łowieniu ryb i w trasę. Planowaliśmy przejść jeszcze tego dnia około dziesięciu kilometrów. Plan planem, a wyszło jak zwykle. Przeszliśmy dwadzieścia. Wszystko przez niezachodzące słońce i własny (mój) brak wyobraźni i zbytnią ufność w łączność komórkową.';

$podroze1.='<p class="p1">Droga wiodła przez niekończący się płaskowyż. Szliśmy na wysokości około 900 m npm jak po pustyni Llano Estacado. Drogę wytyczały nam tylko słupki dla skuterów śnieżnych. Ścieżka miejscami zanikała w kamieniach, więc tylko te znaki zapewniały nam jako taką orientację w terenie. Oczywiście, w razie czego mieliśmy jeszcze GPS-a, kompas i mapę, ale z tymi słupkami opis brzmi bardziej malowniczo ;) Pierwszy postój zrobiliśmy po około czterech kilometrach, przy kolejnej chatce traperskiej. Była zajęta przez innych wędrowników, ale i tak nie planowaliśmy się tam zatrzymywać, jeżeli okoliczności nas nie zmuszą. Chcieliśmy iść dalej, żeby na kolejny dzień zostawić sobie tylko około 15 kilometrów pieszej wędrówki. Połowiliśmy więc znów w ramach odpoczynku ryby, zakąsiliśmy suszonymi plastrami z wołowiny i dalej na pustynię. Po pięciu kilometrach pojawil sie bialy dach "naszej chatki". Nie spodziewaliśmy się tutaj zastać nikogo, bo tak daleko w głąb parku o tej porze roku tylko nieliczni się zapuszczają na piechotę. Co innego zimą. Wycieczki na skuterach śnieżnych to tutaj chleb powszedni.';

$podroze1.='<p class="p1">Na miejscu był strumyk i pełna wygoda: piec na drewno, materace i koce. Mając już w nogach przeszło dwadzieścia kilometrów w kamienistym terenie nie zamieniłbym wtedy tego miejsca na żaden hotel. Tylko... Zasięgu brak, a ja musiałem zadzwonić do domu, żeby dać znak życia. W ramach rozluźnienia mięśni po marszu przespacerowałem się więc rekreacyjnie na najwyższą widoczną górę w okolicy (około 3 km od chatki), ale żadna z rodzimych ani roamingowych sieci nie chciała mi wysłać nawet sms-a. Wróciłem więc do chaty i zdecydowałem, że pójdę jeszcze z plecakiem - tym razem już sam - do kolejnej budki traperskiej. Jednak chociaż na zewnątrz wciąż widno, bo dzień polarny, to mimo wszystko nie uśmiechało mi się spacerować samemu przez kolejne siedem kilometrów. W następnej chacie nie było wygodnych łóżek, a tylko ławy do spania, więc nie byłoby już tak wygodnie jak tutaj. Szczególnie że karimaty “Janusze Survivalu” odnieśli rano do samochodu, jako zbędne. No i tam też nie miałem gwarancji zasięgu jakiejkolwiek sieci. Zdecydowałem więc, że lepiej wrócić się w znanym kierunku, maksymalnie o pięć kilometrów (na poprzednim postoju mieliśmy elementarny zasięg), niż iść z pełnym ekwipunkiem po nocy (co prawda białej) przez następne siedem. I to była bardzo dobra decyzja. Szczególnie, że można było dreptać bez plecaków, a na taki spacer udało mi się namówić jeszcze Daniela. Po trzech kilometrach złapaliśmy sieć, zadzwoniłem więc do domu, pokrzyczeliśmy z radości po awansie Polski do ćwierćfinału Mistrzostw Europy i już bezstresowo wróciliśmy do chatki. Jeszcze tylko herbata, łyk “naleweczki wujka Stacha” na rozgrzewkę i do spania. Rano o szóstej pobudka, żeby zdążyć na południe do samochodu. 
Ale jak tu spać, kiedy zniżające się do horyzontu słońce świeciło przez okno i malowało ściany niesamowitymi barwami. Kilka chwil później kolory zachodzącego słońca zmieniły się na barwy wschodzącego słońca.';

$podroze1.= foto_line('midsommar2016/dzien4_',3,8,'s');

$podroze1.='<p class="p1">Czwartego dnia wczesnym rankiem pobudka, ostatnia kawa z widokiem na góry, szybkie śniadanie - i w drogę. Tak jak się spodziewaliśmy, po około siedmiu kilometrach spaceru w pustynnej scenerii ujrzeliśmy kolejną traperską szopkę. Była zajęta. Ojciec z synem zostali tu na noc, po tym jak chłopak odparzył sobie nogi w nowych butach i trzeba było interwencji szpilkowo-opatrunkowej na bąble na stopach. Dobrze, że nie wybrałem się tutaj w nocy, bo spałbym pewnie przy ognisku na zewnątrz. Pogawędziliśmy chwilę i ruszyliśmy na ostatni ośmio-kilometrowy odcinek. Tuż przed południem siedzieliśmy już w samochodzie, a góry żegnały nas piękną pogodą. Aż żal było odjeżdżać. Daniel, korzystając z jednego dnia urlopu więcej, mógł jeszcze zjechać z drogi i pobiwakować gdzieś nad rybnym jeziorem w Dalarnie, ale ja niestety następnego dnia musiałem już być w pracy. A tu do domu w Linköping jeszcze 700 kilometrów przed maską...

<i><font size=-4>rs, Linköping, czerwiec 2016</font></i>';


//  $podroze1.= foto_line('ochodzita2007/karczma',3,9,'_s');
include 'podr_sma.php';
//require_once("funkcje.php");
//data_index($podroze1,'meta data próbne ąśćŚ');
?>
