<?php
  require("funkcje.php");
$podroze1='<p class="p4">Niesulice 2006<br>
<p class="p3"><b>Jezioro Niesłysz</b>
<p class="p1">Jest duże. Największe na Pojezierzu Lubuskim. I czyściutkie. Siedząc w wodzie można było spokojnie obserwować pływające uklejki.
<p class="p1">Wokół jeziora teren zagospodarowano ośrodkami wypoczynkowymi. Większość z nich to ośrodki biwakowe, bez dyskotek, nagłośnienia i innych takichtam pierdółek, które skutecznie przeszkadzają w wypoczynku.
<p class="p1">Po prostu busz: ptaki, owady, pełzacze, a wieczorami świersze. Jak ktoś lubi obcować z przyrodą - polecam lubuskie jeziorka.
<p class="p1">Niestety nie zdążyliśmy zwiedzić atrakcji przyjeziornych opisanych bardzo szczegółowo w przewodniku wydanym przez Urząd Gminy Skąpe. Linia brzegowa to przeszło dwadzieścia kilometrów, wycieczka piesza w upale to raczej udręka niż przyjemność, a dużym samochodem osobowym bardzo ciężko się przedostać piaskowymi dróżkami wokół jeziora.
<p class="p1">Najlepszym rozwiązaniem jest wypożyczenie na parę godzin rowerów.
<p class="p1">Według mapy turystyczno-administracyjnej gminy Skąpe oznakowana kolorem niebieskim rowerowa trasa prowadzi tuż przy linii brzegowej leśnymi gruntowymi drogami. Jadąc w kierunku zachodnim, najpierw można zobaczyć żeremie bobrów, następnie odwiedzić wieś Przełazy z zabytkowym XIX wiecznym pałacem i kościołem o ciekawej budowli, a z wysokiego brzegu, tuż przy osiedlu domków letniskowych mamy wspaniały widok na jezioro z trzema malowniczymi wyspami. Przed miejscowością Mostki (tam można uciec na krajową "dwójkę" samochodem, jak tylko uda nam się nim do Mostków dotrzeć) trzeba zboczyć z trasy i jechać w kierunku wieży Bismarcka, która jest ciekawym tłem do pamiątkowej fotografii. We wsi Mostki miłośnicy zabytków architektury obronnej mogą zobaczyć pozostałości i częściowo zachowane panzerwerki zespołu umocnień oraz zabytkowy kościół i XIX wieczny pałac.
<p class="p1">Panzerwerk to schron bojowy o wielu pomieszczeniach przeznaczonych do prowadzenia walki oraz odpoczynku i kwaterunku załogi. Wyposażony w pancerne kopuły o grubości kilkudziesięciu centymetrów, ściany i stropy do dwóch metrów grubości i posiadały jedna lub dwie kondygnacje. Były w latach 1934 do 1945 nowocześnie wyposażone do prowadzenia obrony. Obecnie w większości ruiny - na skutek demontażu stalowych pancerzy i wysadzenia w powietrze pomieszczeń dla załogi.
<p class="p1">Następnie jest do pokonania krótki odcinek drogi o poboczach gęsto zarośniętych krzewami i podjazd do drogi w kierunku Krzeczkowa. To już połowa trasy. Od zabudować letniskowych Krzeczkowa droga prowadzi po wysokim brzegu moreny, z której widać wciąż zmieniającą się panoramę jeziora. Szczególnie ładna jest ta, która roztacza się z wyznaczonego na odpoczynek miejsca - tuż przed grodziskiem. Po odpoczynku idziemy oglądać kopiec i obwałowania grodziska, w którym, według legendy, mieli siedzibę rycerze-rabusie. Wielkość grodziska można odczuć spacerując po zewnętrznych obwałowaniach. Jadąc dalej mijamy letnią bazę harcerską, droga obniża się i zbliżamy się do leśnego pola biwakowego. Zaraz za nim należy skręcić w prawo i czeka nas ostatni odcinek szlaku, który wiedzie dróżką o stromych podjazdach i zjazdach. Zanim miniemy Kanał Ołobłocki, po prawej stronie widzimy ogrodzoną plażę z dużą zjeżdżalnią i jesteśmy w Niesulicach, skąd zaczynaliśmy wycieczkę.';
$podroze1.=foto_line('niesulice2006/niesulice',3,20,'_s');
$podroze1.='<p class="p3"><b>Ryby</b>
<p class="p1">Pozwolenia można wykupić we wsi. Przyjechałem oczywiście przygotowany na łowienie, ale w tym upale nawet nie przyszło mi do głowy wyciągać wędki... Szkoda trochę. Może przyjadę tu na ryby jesienią.
<p class="p1">Dno jeziora jest zarośnięte, więc albo trzeba mieć łódź, albo zastosować "pater-noster" bądź zestaw odległościowy ze spławikiem.
<p class="p1">Codzień rano przy umywalkach mozna było spotkać ludzi "oprawiających" swoją zdobycz. W większości były to płotki, a w zasadzie... same płotki. Pewnie łapane wczesnym rankiem z pomostu spacerowego.
<p class="p3"><b>Upał</b>
<p class="p1">Był okrutny. Temperatura rano osiągała dwadzieścia pięć stopni  i rosła w zastraszającym tempie, by w godzinach popołudniowych osiągać trzydzieści sześć stopni w cieniu. Jedynym rozwiązaniem było siedzenie w ciepłej jak zupa wodzie po uszy i to najlepiej w cieniu. Siedzenie w wodzie miało jeszcze jedną wielką zaletę - pozwalało na chwilę zapomnieć o wszędobylskich osach... Komarów za to nie było. Nie wiem, czy było to wynikiem użycia przez gminę środków owadobójczych czy skutkiem upału.
<p class="p1">Komfortowo za to pływało się wieczorami, wręcz po zachodzie słońca.
<p class="p3"><b>Motocykle</b>
<p class="p1">Wieczorami przyjeżdżali dwaj motocykliści. Co dzień ta sama procedura. Zostawiali motocykle, piękne, turystyczne, stylizowane na Goldwingi maszyny, rozbierali się, zostawiali ubrania koło motocykli, zabezpieczali i uruchamiali alarm, wchodzili na pomost, schodzili do kąpieliska, po czym mijali ostatnie barierki i płynęli w kierunku środka jeziora w świetle zachodzącego słońca. Kiedy wracali - nigdy nie doczekaliśmy.
<p class="p1">Widać polskie czyste jeziora i chęć obcowania z naturą przyciągają również bogatych niemieckich turystów.
<p class="p1">Obecność Niemców nie była nachalna. Powiedziałbym, że nad jeziorem w ogóle nie dawali o sobie znać. Czasem było słychać tylko nieliczne rozmowy w obcym języku. Inaczej sprawa przedstawiała się w samych Niesulicach - mijało nas mnóstwo samochodów na niemieckich blachach.';
$podroze1.=foto_line('niesulice2006/motor',3,2,'_s');
$podroze1.='<p class="p3"><a name="frankfurt"><b>Frankfurt</b></a>
<p class="p1">Upał nie malał nawet na chwilę, mimo to zdecydowaliśmy się na wycieczkę do Słubic i Frankfurtu nad Odrą. Rankiem objechaliśmy brukową dróżką jezioro i wyjechaliśmy z niemałym trudem na krajową "dwójkę" w kierunku granicy.
<p class="p1">Skoro już zacząłem pisać o brukowej dróżce dookoła jeziora muszę wspomnieć trochę o lokalnych drogach Pojezierza Lubuskiego. Otóż drogi te mają zawsze jeden pas ruchu - drugi jest usypany z piasku bądź wybrukowany. Bruk to zapewne pozostałości z poniemieckich okolicznych dróg. Aby minąć się z samochodem z przeciwka należy albo delikatnie zwolnić, gdy jedziemy pasem asfaltowym, albo zwolnić "na maxa"  i zjechać na prawą niedobudowaną stronę jezdni. Ruch na tych drogach jest duży - spowodowane jest to bardzo dużym zagęszczeniem samochodów, szczególnie tirów, na jednopasmowej "dwójce" i miejscowi kierowcy wolą męczyć się po dziurach niż stać w czasem wielokilometrowych korkach.
<p class="p1">W Słubicach zaskoczyło nas, że każda ekspedientka, czy to na stacji benzynowej, czy w supermarkecie, biegle rozmawia po niemiecku, natomiast nie doświadczyliśmy tego po stronie niemieckiej. Żadnych obcojęzycznych napisów - jedyny polski napis jaki zauważyłem to tablica kierunkowa do Muzeum Sportu -  i żadnej nawet próby porozumienia się w polskim języku. Nawet w McDonaldzie sto metrów od przejścia granicznego. Wychodzi na to, że Polacy mają zdecydowanie więcej korzyści z handlu z niemieckimi sąsiadami niż oni z nami. Ale my przecież dopiero raczkujemy w europejskiej unii... Zaskoczyły nas również bardzo wysokie ceny paliw, a mimo to Niemcom opłaca się przyjeżdżać tankować w Słubicach.
<p class="p1">Frankfurt, jak przystało na niemieckie miasto, wydał mi się o wiele czystszy i bardziej wyciszony niż Słubice. Taki... bardziej poukładany. Co dziwne takie samo odczucie miałem w czeskim Cieszynie i niemieckich miasteczkach nadbałtyckich.';
$podroze1.=foto_line('niesulice2006/frankfurt',3,9,'_s');
$podroze1.='<p class="p3"><b>Koniec</b>
<p class="p1">To niestety tylko tydzień i trzeba było wracać do domu odwiedzając po drodze opisany już przeze mnie w zeszłym roku Sulechów.
<p class="p1">Jezioro okupują w większości turyści lokalni - z Zielonej Góry, Sulechowa i pobliskiego Świebodzina. Nasze auto z częstochowską rejestracją budziło zdziwienie u biwakujących, jak komuś z tak daleka chciało się przyjechać do takiego buszu?.';
$podroze1.=foto_line('niesulice2006/kamper',3,2,'_s');
$podroze1.='<p class="p1">Ludzie przyjeżdżają tam na całe wakacje: wyprowadzają się z miasta, zabierają kamping, namioty i budują nad jeziorem tymczasowe letnie mieszkania. Stamtąd jeżdżą do pracy, a po powrocie kontynuują wypoczynek. Ciekawa koncepcja życia.';
include 'podr_sma.php';
?>
