<?php
  include 'funkcje.php';
  include 'conf.php';

  $podroze1 = '<p class="p3">Okolice Przedborza<br>';
//Radomsko, czerwiec 2020
$podroze1.='<p class="p2"><a href="#przedborz">Przedbórz</a>
<br><a href="#wola">Wola Przedborska - Bąkowa Góra - Ręczno - (Majkowice)</a>
<br><a href="#chelmo">Góra Chełmo</a>
<br><a href="#wielgomlyny">Wielgomłyny (i Niedośpielin)</a>
<br><a href="#kobiele">Kobiele Wielkie</a>
<br><a href="#kruszyna">Kruszyna</a>';
$podroze1.='<p class="p1"><br><b>Wstęp</b>';
$podroze1.='<p class="p1">Postępująca pandemia (bądź wygasająca, według oficjalnych źródeł) zmusiła nas do ograniczenia dalszych podróży, przynajmniej zagranicznych. Trzeba więc wykorzystać sytuację i zwiedzać najbliższe okolice, o których mimo mieszkania już tutaj od ponad dwudziestu lat, nadal niewiele wiem. Zwiedzaniu sprzyja również hobby motocyklowe. Ale o tym napiszę w innym artykule. A teraz czas na wycieczki po najbliższej okolicy!';
$podroze1.='<p class="p1"><b>Droga</b>';
$podroze1.='<p class="p1">Z Ciężkowic do Przedborza jest około 35 kilometrów. Wybraliśmy się samochodem korzystając z pięknej pogody w Boże Ciało, pośrednio sprawdzić jakość dróg, czy można bezstresowo i bez strachu o kręgosłup wybrać się tam na wycieczkę motocyklową.';
$podroze1.='<p class="p1">Droga jest bardzo dobra z Ciężkowic do Żytna (świeżo naprawiona, a nawet wybudowana od nowa, z przepustami dla zwierząt itd), Potem do Silnicy jest taka sobie, a od Silnicy do Wielgomłyn wyboista i mało komfortowa nawet dla samochodu. Od Wielgomłyn do Trzebców niezła, a potem do samego Przedborza już taka sobie. Harleyem ciężko byłoby jechać - bardzo kręgosłup boli po takich wybojach. Winna jest po części pozycja, w jakiej się jedzie, ale i twardość zawieszenia. Może powinienem jeszcze je zmiękczyć - zostało jedno, najniższe ustawienie. Ale małym Rometem K125 można już przejechać w miarę komfortowo. Prędkości wielkich się tu nie rozwija, bo przez większość czasu jedzie się przez wioski bądź przez lasy z ewentualną zwierzyną, więc sprytna 125-ka wydaje się tu niezłym rozwiązaniem. Muszę tylko pomyśleć nad jakimś kuferkiem na bagażnik, bądź na bak, żeby można było wrzucić mapę, butelkę wody i podstawowe narzędzia, tak w razie czego. Z plecakiem na plecach nie uśmiecha mi się jeździć na rekreacyjne wycieczki.';
$podroze1.='<p class="p1">Z powrotem wracaliśmy kierując się na Radomsko z zamiarem skręcenia w Kodrębie na Kobiele Wielkie i potem na Żytno. Tą drogę już znam z wycieczek nad zalew do Cieszanowic i wiem, że jest równa jak stół. Główną wadą dla jazdy motocyklem jest duży ruch samochodów na odcinku pomiędzy Przedborzem a Kodrębem, bo to droga wojewódzka. Nawierzchnia za to jest doskonała.';
$podroze1.='<p class="p1">Do Kodręba nie dojechaliśmy, skręciliśmy na Kobiele Wielkie w Rzejowicach, co z punktu widzenia jazdy motocyklem to również nie jest dobry wybór. Chociaż wyjeżdża się w Kobielach malowniczo koło parku pałacowego.';
$podroze1.='<p class="p1"><span id=przedborz></span>';
//----------------------------------------------Przedborz------------------------------------
$podroze1.='<p class="p1"><b>Przedbórz</b>';
$podroze1.='<p class="p1">W Przedborzu zaparkowaliśmy bezpośrednio na rynku (darmowe parkowanie w soboty, niedziele i święta) i w pierwszej kolejności obejrzeliśmy kościół Św. Aleksego z wieżą obronną ufundowaną przez Kazimierza Wielkiego. Kościół został odbudowany po spaleniu w 1683 roku. Niestety wejść można było tylko do przedsionka - główna nawa była zamknięta.';
$podroze1.='<p class="p1">Tuż obok kościoła znajduje się Muzeum Ziemi Przedborskiej. Niestety w Boże Ciało 2020 również zamknięte. Moża uda się wejść do środka następnym razem, bo zamierzamy w tych okolicach częściej bywać - nie byliśmy jeszcze w parku krajobrazowym - a okolica jest przepiękna.';
$podroze1.='<p class="p1">Na rynku jest zabytkowa studnia, ale też nie było okazji jest obejrzeć z bliska - mnóstwo dzieciaków bawiło się koło niej, a w dobie społecznej izolacji lepiej unikać zbytecznych kontaktów z nadmiarem ludzi. Zjedliśmy za to lody z lodziarni na rynku i pojechaliśmy zobaczyć pobliski zalew i kąpielisko. Nad zalewem w restauracji mnóstwo ludzi, na pobliskich brzegach stada łabędzi, a na dalszym brzegu wędkarze. Nad kąpielisko już nie podeszliśmy.';
$podroze1.= foto_line('okolice_radomska/okolice_przedborza/przedborz',3,6,'_s');
$podroze1.='<p class="p1"><span id=wola></span>';
//-----------------------------------Wola Przedborska i Bąkowa Góra i Majkowice-----------------------
$podroze1.='<p class="p1"><b>Wola Przedborska - Bąkowa Góra - Ręczno - (Majkowice)</b>';
$podroze1.='<p class="p1">Po spacerze nad zalewem pojechaliśmy na północ w kierunku Ręczna, które miało być celem mojej kolejnej wycieczki motocyklowej. Z Przedborza do Bąkowej Góry droga jest taka sobie, ale można przejechać w miarę komfortowo również Harleyem. W Bąkowej Górze warto się zatrzymać przy kościele na wzgórzu (pw Świętej Trójcy, XV-XVII wiek), przejść się w stronę cmentarza aleją wierzb i podziwiać panoramę Przedborskiego Parku Krajobrazowego.';
$podroze1.='<p class="p1">Wjeżdżając drogą w lewo jeszcze wyżej, można zatrzymać się na parkingu i obejrzeć ruiny zamku z XV wieku. Zamek (a raczej dwór obronny) jest w rękach prywatnych i niestety trzeba umówić się z właścicielem, aby móc obejrzeć ruiny z bliska. Za daleka co nieco też widać, a idąc dróżką wokół ogrodzenia można obejrzeć również dworek szlachecki z XVII wieku.';
$podroze1.='<p class="p1">Z Bąkowej Góry do Ręczna droga jest już doskonała, a w Ręcznie można zatrzymać się koło kościoła parafialnego z XVII wieku (pw Stanisława Biskupa i Męczennika).';
$podroze1.='<p class="p1">Ruiny zamku są także w Majkowicach, ale tam nie udało nam się dotrzeć. Po prostu nie wiedzieliśmy o ich istnieniu. Trzeba koniecznie to nadrobić następnym razem.';
$podroze1.= foto_line('okolice_radomska/okolice_przedborza/bakowa_gora',3,2,'_s');
$podroze1.='<p class="p1"><span id=chelmo></span>';
//---------------------------------Góra Chełmo-------------------------------------------------
$podroze1.='<p class="p1"><b>Góra Chełmo</b>';
$podroze1.='<p class="p1">Góra Chełmo (323 m npm) to następny odcinek naszej wycieczki po Ziemi Radomszczańskiej i największe wzniesienie po tej stronie Pilicy. Drugie największe - Fajna Ryba (347 m npm), znajduje się już w Przedborskim Parku Krajobrazowym kilkanaście kilometrów dalej.';
$podroze1.='<p class="p1">Droga z Ciężkowic prowadzi tak, jakbyśmy jechali do Przedborza, ale mając w głowie nie najlepszą nawierzchnię, pojechaliśmy z Żytna przez Kodrąb, skręcając tam na Przedbórz, a potem w Granicach na Chełmo. Nakłada się niewiele drogi, a nawierzchnia wyśmienita. Z powrotem pojechaliśmy przez Wielgomłyny i Niedośpielin do Kobiel Wielkich - i tutaj droga również nadaje się na twarde motocykle. Wygląda na to, że najgorzej pod kątem komfortu jest przez Silnicę, a potem od Wielgomłyn do Przedborza. Lepiej pojechać na Chełmo, Granice i dopiero wtedy skręcić na Przedbórz.';
$podroze1.= foto_line('okolice_radomska/okolice_przedborza/chelmo',3,8,'_s');
$podroze1.='<p class="p1">Szczytowy fragment Góry Chełmo objęty jest rezerwatem przyrody. Rezerwat rezerwatem, a śmieci niestety i jak zwykle mnóstwo. Miłośnicy Żywca i Harnasia znajdą się wszędzie, ale czemu nie zabiorą ze sobą puszek z powrotem do domu - tego już nie jestem w stanie zrozumieć. Grodziska prehistorycznego nie widzieliśmy (bo nie wchodziliśmy na szczyt - będzie okazja do następnej wycieczki), za to skalne urwiska z piaskowca, wydobywanego tutaj już od średniowiecza, prezentują się niesamowicie. Niektóre ściany mają nawet 10 metrów wysokości. Kamieniołomy są już oczywiście nieczynne, ale nadal spotkać można aktualne odkrywki piasku u zbocza góry od strony Wielgomłyn.';
$podroze1.='<p class="p1">Legenda głosi, że na górze spotykały się czarownice przylatujące z pobliskiej Sokolej Góry.';
//--------------------------Wielgomłyny i Niedośpielin-------------------------------------------------
$podroze1.='<p class="p1"><span id=wielgomlyny></span>';
$podroze1.='<p class="p1"><b>Wielgomłyny (i Niedośpielin)</b>';
$podroze1.='<p class="p1">Kościół klasztorny Paulinów z XV wieku (Sanktuarium Matki Boskiej Bolesnej - Bolesnej Pani Wielgomłyńskiej) z racji niedzielnego popołudnia był zamknięty, a wioska trochę opustoszała, za to robiła wrażenie czystej i zadbanej. Warto zwrócić uwagę na kamienną dzwonnicę przy klasztorze oraz ciekawy drogowskaz na ryneczku.';
$podroze1.= foto_line('okolice_radomska/okolice_przedborza/wielgomlyny',3,6,'_s');
$podroze1.='<p class="p1">Z Wielgomłyn drogą przez Niedośpielin, Kobiele Wielkie i Żytno wróciliśmy do Ciężkowic.
Okolice Przedborza znane były w średniowieczu jako wspaniałe tereny polowań. Z najbardziej znanych myśliwych polował tu Kazimierz Wielki, a potem też i Władysław Jagiełło. Podobno Kazimierz Wielki zgubił się w okolicach Wielgomłyn w czasie polowania, zapadła noc, a on krążył tak i krążył po okolicy. Aż zobaczył w oddali słabe światło i udał się w jego kierunku. Okazało się, że to była chata kmiecia, gdzie król mógł się zatrzymać i zapytać o drogę. Kmieć szczęśliwie jeszcze nie spał, co uratowało króla przed biwakiem w lesie do rana, a pewnie nie miał ze sobą ani śpiwora, ani kuchenki turystycznej, ani krzesiwa, ani latarki, ani nic z tak zwanego EDC. No może poza nożem, bo noże czy inne elementy ostre nosili wtedy wszyscy. No i stąd właśnie nazwa Niedośpielin :)';
//-----------------------------Kobiele Wielkie ---------------------------------------
$podroze1.='<p class="p1"><span id=kobiele></span>';
$podroze1.='<p class="p1"><b>Kobiele Wielkie</b>';
$podroze1.='<p class="p1">Mój leciwy "Sport" gulgotał leniwie na piątym biegu połykając kolejne kilometry. Jechałem wsłuchując się w jednostajny dźwięk silnika, podziwiając kolorowe niekończące się połacie pól po obu stronach drogi i wielką burzową chmurę nadciągającą od północy...';
$podroze1.='<p class="p1">- Wracać, czy jechać dalej? - myśli jak błyskawice przelatywały mi przez głowę. - No nie! Nie po to tydzień czekałem, aż przestanie padać, żeby teraz wracać z podkulonym ogonem do domu! - Co prawda wykorzystałem ten czas solennie na zaległy przegląd i serwis przedniego zawieszenia w Romecie, ale jednak to nie to samo co beztroska jazda wywiewająca z głowy wszystkie problemy zeszłych dni.';
$podroze1.='<p class="p1">Obserwując coraz szybciej napływające czarne chmury, zweryfikowałem jednak plany i zamiast dojechać do Kamieńska, zdecydowałem się zawrócić już Kobielach Wielkich. Co prawda wożę ze sobą w bocznej torbie dużą pelerynę przeciwdeszczową i mógłbym schować się pod nią (wraz z motorem) i przeczekać deszcz na poboczu, bądź przy odrobinie szczęścia pod wiatą przystankową, ale zawsze to lepiej nie musieć z niej korzystać. A wybiegając w przyszłość, po powrocie do domu (suchym kołem na szczęście), spadła z nieba taka ściana wody, jakiej nie widziałem w Ciężkowicach chyba od dziesięciu lat. Nawet namiot wojskowy chyba nawet by w tej sytuacji nie pomógł.';
$podroze1.='<p class="p1">Drogę do Kobiel już opisywałem wielokrotnie: od samych Ciężkowic równa jak stół, ruch znikomy, terenów zabudowanych mało, mogłoby się wydawać, że wymarzona dla kawalerskiej jazdy motocyklem. Jednak duża ilość ślepych zakrętów (zboża są już wysokie i nigdy nie wiadomo, czy jakaś maszyna rolnicza nie wyjedzie z polnej drogi), a także dość długie odcinki przez lasy obfitujące w sarny, dziki i inne większe bądź mniejsze stworzenia, skutecznie leczą z ambicji sportowych. Do jazdy rekreacyjnej za to droga ta nadaje się wspaniale.';
$podroze1.='<p class="p1">A gdy już dojedziemy do Kobiel... ';
$podroze1.='<p class="p1">Nie wszyscy wiedzą, że w tej wsi urodził się Władysław Reymont, którego ojciec był organistą w tutejszym kościele. W 75 rocznicę śmierci pisarza, w miejscu domu, jest teraz pamiątkowy pomnik. Na obelisku znajduje się napis, którego fragmentem jest cytat: "Kto ino wyrzeka się zła nie czyniąc dobra ten gorsze zło rodzi – S.W. Reymont".';
$podroze1.= foto_line('okolice_radomska/okolice_przedborza/kobiele',3,8,'_s');
$podroze1.='<p class="p1">Tuż za Urzędem Gminy znajduje się klasycystyczny dwór, ukończony w 1905 roku, o czym świadczy data na fasadzie. Zbudowany był dla Kazimierza Tymowskiego, potem po 1937 roku był własnością Marii Teresy Sobańskiej. Po II wojnie światowej we dworze mieściły się ośrodek zdrowia, izba porodowa i przedszkole. W skład przedwojennego majątku wchodziły również stajnia wyścigowa (przebudowana potem na łaźnię), młyn, wiatrak, kuźnia, majsternia, spichlerz i ślusarnia oraz lodownia w parku. Z dawnej świetności nie zostało jednak zbyt wiele. Patrząc z bliska na jego ruinę można zobaczyć ślady pożaru, które trawiły budynek w ostatnich latach.';
$podroze1.='<p class="p1">Ciekawszy niż sam budynek jest przypałacowy park. Panuje tu chłodny półmrok, a wielkie, stare modrzewie nadal budzą podziw i szacunek. Spacerując po wytyczonych przed wielu laty ścieżkach można wyobrazić sobie, jak ten park wyglądał w czasach świetności. Zachowały się nawet stare, kute ze stali, ławeczki. W stawach coś pluska - nie wiadomo, czy to ryby, czy tylko żaby. Następnym razem przyjadę z wędką i sprawdzę.';
$podroze1.='<p class="p1">A teraz już czas wskoczyć na siodło i szybko zwiewać przed burzą.';

//-----------------------------Kruszyna 20210514 ---------------------------------------
$podroze1.='<p class="p1"><span id=kruszyna></span>';
$podroze1.='<p class="p1"><b>Kruszyna</b>';
$podroze1.='<p class="p1">Dziwna budowla wyłoniła się powoli spośród przydrożnych drzew. Wyglądała jak samotny komin, pozostałość po starym domu mieszkalnym. Ale skąd pojedynczy dom w samym środku pola z daleka od jakiejkolwiek wsi? Zwolniłem, żeby przepuścić wszystkie samochody, przycupnąć gdzieś na poboczu i podejść zobaczyć co to takiego. Im bliżej podjeżdżałem, tym szerzej oczy otwierałem ze zdumienia. Zostawiłem motocykl i podszedłem z bliska obejrzeć obiekt mojego zainteresowania.';
$podroze1.='<p class="p1">To coś, co z daleka wydawało się pozostałością jakiegoś budynku mieszkalnego, okazało się wolnostojącą koryncką kolumną. Podobną do kolumny Zygmunta, ale… bez Zygmunta. Ani bez nikogo. Po prostu sama kolumna. Bez żadnej tabliczki, opisu, ryciny, nic. Zrobiłem kilka zdjęć i pojechałem dalej w kierunku Kruszyny.';
$podroze1.='<p class="p1">W końcu nastała wiosna i w końcu znów można pojeździć motocyklem po okolicy. A ponieważ okolicę planowałem zwiedzić bliską, to i motorek wziąłem na przejażdżkę mały i zwinny, który pozwoliłby dość sprawnie przemieszczać się po wąskich i dziurawych po zimie lokalnych drogach. A i przejazd wąską ścieżką przez las czy nad rzeką okazuje się o wiele przyjemniejszy niż na ciężkim motocyklu. A celem wycieczki była, jak już napisałem wcześniej, Kruszyna.';
$podroze1.='<p class="p1">W Wikipedii można wyczytać, że...';
$podroze1.='<p class="p1"><i>...to jedna z najstarszych miejscowości regionu, wymieniana w źródłach w 1337 r. jako parafia, mająca własny kościół. Z tego roku pochodzi akt darowizny, w którym Lutold Wierusz występuje jako m.in. właściciel Kruszyny. W 1520 r. wieś należała do hetmańskiej rodziny Koniecpolskich, a ściślej do Zygmunta Koniecpolskiego, starosty przemyskiego. Potem Kruszynę otrzymała jako wiano Aleksandra Koniecpolska i jej mąż Kacper Denhoff, uznany polityk za króla Zygmunta III, wojewoda sieradzki, przybyły z Estonii w ucieczce przed Szwedami. W 1616 r. Denhoff otrzymał od Rzeczypospolitej dwa bardzo intratne starostwa – wieluńskie i radomszczańskie. Na jego zlecenie znakomity włoski architekt, Tomasz Poncino w 1630 r. przystąpił do budowy renesansowego pałacu, w którym 3 lata później odbyło się wesele jego córki z podkanclerzym koronnym Bogusławem Leszczyńskim. Czasy, gdy Kruszyna należała do Denhoffów, to okres jej największej świetności. Po Denhoffach Kruszyna należała kolejno do Butlerów, Potockich, Walewskich, hrabiny von Schoenaich, Chruckich, Martinich, Podczackich i Lubomirskich.</i>';
$podroze1.= foto_line('okolice_radomska/okolice_przedborza/kruszyna',3,8,'_s');
$podroze1.='<p class="p1">W książce "Świat, który odszedł", Cezarego Jana Lisa przeczytałem, że w czasie wojny pałac był okupowany przez Niemców, a w 1945 roku został przejęty przez czerwonoarmistów. W poszukiwaniu alkoholu i złota zdewastowali go zupełnie, łącznie z wyposażeniem, zabytkowymi meblami i cennymi obrazami. Po wojnie był tu Państwowy Dom Dziecka, a po 1968 roku działała tu administracja spółdzielni rolniczej. Co za tym idzie nadal postępowało rozkradanie i degradacja pałacu wraz z XIX-wiecznym parkiem o powierzchni 17 ha.';
$podroze1.='<p class="p1">W 1990 roku pałac wrócił do rodziny Lubomirskich, a następnie w 2005 roku został sprzedany rodzinie "polonusów" z Nowego Jorku - Elżbiecie i Wojciechowi Pałkom. Teren został ogrodzony i poddany ścisłej ochronie. Z której strony nie podjechałbym pod siatkę, wszędzie widać tabliczki "Uwaga zły pies". Psa osobiście nie widziałem. Prawdopodobnie zdechł już ze starości.';
$podroze1.='<p class="p1">W każdym razie do pałacu wejść nie można. Frontowa brama wjazdowa jest tak zabita szczelnie deskami, że nawet malutki obiektyw aparatu w komórce nie jest w stanie się przecisnąć. Wysoka również odpowiednio - bez jakiegoś stołka ani drabiny zobaczyć nic nie można. Podjechałem więc wąską szutrową dróżką od tyłu parku i stamtąd zobaczyłem poprzez drzewa bramę na dziedziniec i mostek nad rzeczką, a może fosą, ciężko mi jest to z całą pewnością stwierdzić. I wydawałoby się, że to tyle na temat zaplanowanego zwiedzania pałacu.';
$podroze1.='<p class="p1">Ale od czego są kościoły. Pomyślałem, że podjadę, poczytam ogłoszenia, może kogoś zapytam, a nuż widelec dowiem się czegoś o pałacu. Napisane nie było nic, ale wjechałem sobie spokojnie na tyły kościoła i okazało się, że graniczy on z parkiem pałacowym. I że stąd widok na pałac jest… No jakiś jest w ogóle. Rozłożyłem się na pół godziny, odpocząłem i pojechałem z powrotem do domu, mając nadzieję, że kiedyś może uda się zwiedzić to miejsce w jakiś bardziej cywilizowany sposób.';
$podroze1.='<p class="p1">Wracając znów mijałem dziwną kolumnę. Dopiero w domu przeczytałem o niej w Wikipedii:';
$podroze1.='<p class="p1"><i>Między Kruszyną a Borownem stoi w polu obelisk dla upamiętnienia samobójczej śmierci syna Kacpra Denhoffa, któremu nie pozwolił się żenić z Barbarą Szafraniec (w podaniach występują różne imiona: Anna, Barbara,Hanna), córką dzierżawcy pobliskich Bogusławic. Denhoff spoił parobków, każąc im spalić dworek Szafrańców wraz z uwięzioną w nim rodziną. Syn, zobaczywszy łunę wskoczył na konia, jednak było już za późno. Oszalały z bólu po śmierci ukochanej strzelił sobie w głowę. Załamany samobójstwem syna Kasper Denhoff wybudował w parku pałacowym samotnię, w której później zamieszkał. Inne przekazy mówią, że z samotni wiódł tajny, podziemny korytarz do pałacu, gdzie Denhoff bawił się nocami.</i>';
$podroze1.='<p class="p1">Samotni również nie widziałem. Może kiedyś będzie jeszcze okazja.';

$podroze1.='<p class="p1"><i><font size=-4>rs, Ciężkowice, luty 2020 - maj 2021</font></i>';
include 'podr_sma.php';


//require_once("funkcje.php");
//data_index($podroze1,'meta data próbne ąśćŚ');
?>
