<?php
  include 'funkcje.php';
  include 'conf.php';

  $podroze1 = '<p class="p3">Czekając na wiosnę<br>';
//Szwecja, luty 2019
//linkoping
$podroze1.='<p class="p1"><b>Linköping</b>';
$podroze1.='<p class="p1">Samolot leci w przepięknym słońcu, a pod skrzydłami chmury układają się w puszystą pierzynę. Piję kawę i piszę ostatnie zdania podsumowujące mój ostatni pobyt w Szwecji. Sporo czasu spędziłem na Północy ale, jak dobrze pamiętam, to dopiero moja czwarta zima. Zwykle starałem się unikać zimy - latem północny wiatr nie przeszywa do kości mimo puchowej kurtki, a temperatura w niezliczonych tutejszych jeziorach jest bardziej odpowiednia do kąpieli.';
$podroze1.='<p class="p1">Pod koniec lutego dzień już jest na tyle długi, że mogłem powrócić do moich ulubionych popołudniowych wycieczek rowerowych po okolicy. Nie za długich co prawda, bo od wyjścia z pracy do zachodu słońca jest około półtorej godziny, ale tutaj słońce zachodzi trochę inaczej niż u nas. Ściemnia się bardzo powoli i jeszcze długo po zachodzie nad horyzontem widać jasne kolorowe smugi światła. Szczególnie lubię ten zachód słońca latem, kiedy te smugi stają się coraz bardziej kolorowe aż do północy, aby zaledwie dwie godziny później przeobrazić się w nowy dzień.';
$podroze1.='<p class="p1">Jezioro Roxen jest wielkości mniej więcej polskich Śniardw i uchodzi w Szwecji za średnie. Ma wiele zalet: jest płytkie, szybko się nagrzewa, a latem temperatura wody dochodzi nawet do dwudziestu stopni. I jest blisko miasta. Szwedzi nie lubią się w nim kąpać, bo podobno przez to że jest "ciepłe", to kwitnie i jest brudne. Jeden z moich tutejszych znajomych powiedział (z bardzo poważną miną), że kiedyś jego pies napił się tam wody i potem zdechł. Ja też po kilku latach (nie, nie po tej rozmowie) do kąpieli wybierałem głębsze i czystsze jeziora, a do temperatury wody poniżej 20 stopni… No cóż, można się przyzwyczaić. Amatorzy wczasów na polskim wybrzeżu mogą to potwierdzić.';
$podroze1.='<p class="p1">Do jeziora można dojechać z kilku stron. Objechałem je na rowerze dookoła, więc znam jego linię brzegową. Z jednej strony są podmokłe łąki i kąpieliska, z innej wielkie kamienie wystające nad powierzchnię wody, jeszcze z innej zaś lasy i plaże. Żeby najszybciej dotrzeć nad jezioro z Linköping, najlepiej trzymać się rzeki Stångån i jechać wzdłuż jej brzegu ścieżką rowerową, a później żwirową dróżką, aż do ujścia. Jest tam stanica dla żaglówek i punkt widokowy. Do samej wody raczej się podejść nie ma - broni jej szeroki pas trzcin. Mimo wszystko warto, bo widok jest przepiękny nawet zimą. A po gdzieniegdzie poruszających się zaroślach na brzegu widzę, że i polowanie na szczupaki w rzece przesunęło się na wcześniejsze miesiące. Swoją drogą ciekawe, bo nie udało mi złapać szczupaka na tamtym odcinku rzeki aż do maja.';
$podroze1.='<p class="p1">Jadąc w stronę Bergu (klasztor Vreta i śluzy na kanale Gota w Bergu opisywałem już wiele razy) przejeżdżamy po drodze rzekę Svartan. Tuż przed rzeką jest asfaltówka w prawo, oznaczona jako ślepa. Na pierwszy rzut oka prowadzi do pobliskich zabudowań i nigdzie dalej. Jeżeli pojedziemy jednak tą drogą i nie przestraszymy się znaku, że można ze stromego brzegu wpaść do jeziora, po zjeździe z asfaltu nadal mamy drogę - tym razem żwirową. Prowadzi ona do kolejnej wieży obserwacyjnej na jeziorze, skąd widać zarówno panoramę Linköping, jak i Berg wraz z charakterystyczną bryłą wspomnianego XI-wiecznego klasztoru.';
$podroze1.='<p class="p1">W rezerwacie Tinnero, położonym o około pięć kilometrów od centrum Linköping, ale w przeciwną stronę niż jezioro Roxen, jest górka - punkt widokowy, z którego roztacza się widok na miasto. Nigdy nie mogłem tutaj trafić bez błądzenia po okolicy, czy to jeździłem z gps-em (tak tak, zanotowałem sobie pozycję), czy to z mapą. A jak już chciałem komuś pokazać to miejsce, to jak amen w pacierzu. Górka znikała i już. A dziś (25 lutego) - ponieważ na polnych dróżkach odwilż zostawia coraz więcej błota - jechałem ścieżkami rowerowymi bez robienia sobie skrótów po leśnych ścieżkach i... Trafiłem od razu. Widok na miasto zimą, gdy drzewa nie mają liści, jest jeszcze fajniejszy niż latem.';
$podroze1.='<p class="p1">Znajdujące się w tym samym rezerwacie, ale w innym jego punkcie, jezioro Rosenkällasjön (w wolnym tłumaczeniu "Jezioro Źródła Róży") jest nadal zamarznięte, ale jak pamiętam ono zamarznięte potrafiło być nawet w kwietniu. Biedne łabędzie i inne ptaszki wodne wykorzystują każdą kałużę wody, żeby pomoczyć sobie płetwy. Robi się jednak coraz głośniej - to pierwsze oznaki nadchodzącej wiosny.';
$podroze1.= foto_line('linko2019/linkoping',3,8,'_s');

$podroze1.='<p class="p1">Przesuńmy się jednak na chwilę o miesiąc wstecz.'; 
$podroze1.='<p class="p1">Podczas gdy w Polsce już prawie wiosna, w Linköping początek lutego był mocno śnieżny. Tak śnieżny, że samoloty były poopóźniane, a służby nie nadążały odśnieżać pasa startowego na lokalnym lotnisku Skavsta.';
$podroze1.='<p class="p1">Ale nadążały za to odśnieżać ścieżki rowerowe, więc można było swobodnie poruszać się do pracy i z powrotem moim ulubionym tutaj środkiem transportu. A ponieważ odśnieżały również tory kolejowe, to postanowiłem, że i tym razem pozwiedzam „najbliższą” okolicę. Pierwszy wybór padł na…';
//oslo 
$podroze1.='<p class="p1"><b>Oslo</b>';
$podroze1.='<p class="p1">Pociąg z Linköping do stolicy Norwegii jedzie 6 godzin. Wyszedłem z dworca i rozglądałem się w poszukiwaniu widocznej (podobno) z każdego punktu miasta skoczni Holmenkollen. Zamiast skoczni zobaczyłem las wieżowców rodem z Nowego Jorku. I trochę byłem… No nie wiem. Zaskoczony? Rozczarowany? Nie tego się spodziewałem. Jakoś inaczej wyobrażałem sobie to północne miasto. Może bardziej podobne do Sztokholmu, albo Helsinek... Takie uczucie towarzyszyło mi przez cały wieczór podczas spaceru przez miasto, nabrzeże, czy gdy podziwiałem panoramę Oslo z dachu Opery Narodowej. Można wejść na dach, bo wygląda on jak stok narciarski – i czasem jest tak wykorzystywany. Widok na fiord jest przecudny, nie dziwota że stał się tematem słynnego obrazu Muncha pod tytułem „Krzyk”. A nawet czterech obrazów, bo okazało się, że namalował ich właśnie cztery. Jeden z nich wisi podobno w Muzeum Narodowym, ale było niestety zamknięte, a nowe będzie otwarte w 2020 roku. Dwa są w rękach prywatnych, a jeden w Muzeum Muncha, które zaplanowałem sobie odwiedzić następnego dnia na wypadek zapowiadanej przez meteorologów deszczowej pogody. A’propos pogody: było ciepło, wszystko, co zamarznięte, się topiło i masy śniegu spadały ze stromych dachów na chodniki, które były śliskie jak jasny gwint. Trzeba było spacerować środkiem ulicy, jeżeli nie chciało się zostać zabitym przez lodowy blok spadający z dachu jak grom z pochmurnego nieba, oraz chodzić krokiem marynarza, który niejeden ocean na beczce przepłynął, żeby utrzymać się na nogach na zamarzniętym śniegu przykrytym warstwą wody. Najlepszy widok na miasto i na największy fiord w Norwegii jest ze wspomnianego dachu opery i z murów średniowiecznej twierdzy Akershus. I tam zrozumiałem, patrząc na miasto rozświetlone w zapadającym zmroku, że właśnie tak ma być. Że Oslo właśnie takie jest jakie jest. I że dobrze, że jestem tak krótko, bo za tydzień żal mi byłoby stąd wyjeżdżać. Mimo że słynnej skoczni nadal nigdzie nie mogłem zlokalizować.';
$podroze1.='<p class="p1">Kilka słów na temat hotelu – pierwszy raz w życiu korzystałem z sieci Citibox Hotels: jest to hotel samoobsługowy, z automatyczną rejestracją w „prawie-bankomacie”. Pokoje są spartańskie. Mój, ponieważ jednoosobowy, wyglądał trochę klaustrofobicznie, a na łóżku lepiej było się nie kręcić, żeby nie spaść z jednej albo z drugiej strony. Nie ma telewizora, jest za to darmowy Internet. Nie ma również czajnika (jest w lobby na dole, herbatę trzeba mieć własną), i nie ma w zestawie śniadań. Są czyste ręczniki i gorący prysznic. Jest restauracja, która dla gości hotelowych ma 10% zniżki, jednakże przy norweskich cenach lepiej skorzystać z wyżywienia na mieście. Gastronomia, podobnie jak w Szwecji, w większości prowadzona jest przez przyjezdnych. Wyrejestrowanie się jest jeszcze prostsze: wpisujemy numer pokoju, automat nas wyrejestrowuje, wrzucamy kartę magnetyczną do skrzynki i już biegniemy zwiedzać miasto, bo czas do powrotu mija szybko.';
$podroze1.='<p class="p1">Na niedzielę miałem plan główny - słynny park Vigelanda z 212 rzeźbami przedstawiającymi postacie w różnych pozach - oraz plan rezerwowy w razie deszczu – muzeum Muncha. Padało tylko trochę, więc wybrałem godzinny spacer do parku, szczególnie że chciałem jeszcze po drodze zobaczyć zamek królewski. Zamek można zwiedzać tylko latem, ale i zimą warto obejrzeć go z zewnątrz. Sam park – jak to park. Za to alejka z rzeźbami - niesamowita. Z gigantycznym Monolitem na końcu ścieżki. Mógłbym tu spędzić kilka godzin, gdyby to było lato. I gdyby deszcz nie robił się coraz bardziej uciążliwy. Czas było więc powoli zbierać się na autobus do Karlstadu. A potem jeszcze trzy przesiadki na pociąg – bo taki miałem sprytny plan na podróż powrotną – i już piłem herbatę w wygodnym fotelu mojego mieszkania w Linköping.';
$podroze1.= foto_line('linko2019/oslo',3,4,'_s');
 
$podroze1.='<p class="p1">A potem nagle przyszła wiosna… Nie zastanawiając się długo na kolejną sobotę kupiłem bilety do';
//malmo
$podroze1.='<p class="p1"><b>Malmö</b>';
$podroze1.='<p class="p1">Nigdy nie byłem w Malmö. No, w zasadzie byłem raz, ale oglądałem miasto z samochodu jadącego po słynnym moście przez cieśninę Sund wracając z Kopenhagi do Linköping. Tym razem wsiadłem w superszybki pociąg X-2000 i trzy godziny później jadłem już kanapkę patrząc na cieśninę z nadmorskiego deptaka w obrzydliwie bogatej dzielnicy Västra Hamnen (uznawanej za najbardziej ekologiczną dzielnicę w Szwecji), nad którą góruje futurystyczny wieżowiec Turning Torso. Nawet nie chce mi się myśleć, ile trzeba mieć pieniędzy, żeby kupić sobie mieszkanie z widokiem na cieśninę. Na nabrzeżu mnóstwo spacerowiczów, a biorąc pod uwagę pogodę (prawie 10 stopni), to nawet plażowiczów. Jeden z nich nawet postanowił się wykąpać. No cóż, woda w Morzu Północnym słynie ze swej… Hm... Unikalnej temperatury również zimą.';
$podroze1.='<p class="p1">Z Västra Hamnen przez park pałacowy – jak sama nazwa wskazuje znajdujący się koło zamku zbudowanego za panowania Duńczyków – poszedłem na Stare Miasto. Nie jest może tak malownicze jak w Sztokholmie, ale ma swój urok i bardzo mi się tu podobało. Można po tych uliczkach spacerować godzinami. A godziny lecą szybko, więc musiałem wracać na pociąg.';

$podroze1.= foto_line('linko2019/malmo',3,4,'_s');
$podroze1.='<p class="p1">A pociąg nie przyjeżdżał. Przesunięto odjazd najpierw o 10 minut, potem o kolejne 10 minut, potem dostałem SMS-a od SJ (szwedzka kolej państwowa), że jest zatrzymanie ruchu kolejowego w kierunku Lundu, a potem mój "nabbtåg" odwołano zupełnie. A ja 500 kilometrów od domu bez planu awaryjnego… Pobiegłem do informacji, i kiedy już przyszła moja kolej w olbrzymiej kolejce, dowiedziałem się tylko tyle, że nie wiadomo jak mam się dostać do domu. Sprawdziłem autobusy – najbliższy był za godzinę (to akurat OK) i jechał planowo 8 godzin (to akurat bardzo nie OK). Szybko przejrzałem booking.com w poszukiwaniu hoteli i udało mi się znaleźć pokój za bezcen (za 400 SEK zamiast „normalnych” 900 SEK) w średniej klasy hotelu 400 metrów od dworca. Zadowolony podniosłem się z ławki, rzuciłem jeszcze okiem na tablicę odjazdów, a tam… Nowa godzina odjazdu mojego pociągu o 18:05. Rzut oka na zegarek, a tu… 18:06! Ja biegiem na peron, wskoczyłem do ostatniego wagonu, konduktor zagwizdał i pociąg odjechał. Trzeba mieć jednak trochę farta w życiu. Pozostało jednak pytanie, co zrobić z rezerwacją hotelową, której według booking.com można było co prawda odwołać, ale bez zwrotu pieniędzy. Zadzwoniłem jednak do hotelu i udało się w drodze wyjątku anulować moją opłatę. „Zaoszczędzone” na hotelu pieniądze przeznaczyłem na bilety do';
//sztokholm
$podroze1.='<p class="p1"><b>Sztokholmu</b>';
$podroze1.='<p class="p1">Uwielbiam szybkie pociągi. Pociągi ogólnie mają jedną wielką przewagę nad samolotami: można przyjść na dworzec minutę przed odjazdem. Dodatkowo, wjeżdżają zwykle do samego centrum miasta. Jeżeli do słowa "pociąg" dołożymy słowo "szybki", dostajemy słowo "snabbtåg" - pociąg, który potrafi jeździć grubo ponad 200 km/h (tak jak pisałem, 500-kilometrową odległość z Linköping do Malmö przejechałem w 2 godziny i 50 minut). Pociągi w Szwecji mają również szwedzką kawę: mocną, parzoną w ekspresie przelewowym starego typu (muszę koniecznie przywrócić go do życia w domu). A smak… Niech się schowają wszystkie Costy i Starbucksy! Dla samego smaku tej kawy warto odwiedzić Szwecję.';
$podroze1.='<p class="p1">Z Linköping do Sztokholmu taki szybki pociąg jedzie godzinę i pięćdziesiąt minut. Zatrzymuje się w samym centrum, a piętnaście minut później można już stać w przeogromnej kolejce do Galerii Narodowej. Nigdy w niej nie byłem, bo zwykle były ważniejsze rzeczy do zrobienia (a jak już byliśmy w większej grupie, to nikt nie chciał iść), więc teraz to był mój główny plan. Co można napisać o tym muzeum? Mnóstwo malarstwa słynnych światowych artystów, dużo rzeźby, trochę szwedzkiego wzornictwa i sztuki współczesnej. I trochę pamiątek z Polski przywiezionych w czasie potopu szwedzkiego. Warto zarezerwować sobie 2-3 godziny na spokojne zwiedzanie.';
$podroze1.='<p class="p1">Sztokholm to miasto, do którego zawsze będę wracał z przyjemnością. Czekam z niecierpliwością, aż wyremontują Slusen - moje ulubione miejsce w "Wenecji Północy". Teraz jednak musiałem obejść się smakiem i zdecydowałem nie zapuszczać się ponownie na Wielkie Wykopaliska.';
$podroze1.= foto_line('linko2019/sztokholm',3,4,'_s');
$podroze1.='<p class="p1">Poszedłem natomiast w przeciwnym kierunku, do zapomnianego i stojącego na uboczu obserwatorium astronomicznego. Warto wejść na tą górkę, żeby zobaczyć Sztokholm z innej perspektywy. Z obserwatorium głównym deptakiem przeszedłem przez całe centrum turystyczne, minąłem T-Centralen, budynek parlamentu, zamek królewski i doszedłem z powrotem na Stare Miasto. Tutaj po południu jak zwykle: tłum ludzi, kamienice na rynku w remoncie, moja ulubiona superwąska uliczka pomalowana graffiti (pierwszy raz ją widzę w takim stanie), w sklepach z pamiątkami mnóstwo popierdółek pozornie związanych z tutejszą kulturą, a ceny w restauracjach rodem z Norwegii. Wystarczy jednak zejść trochę z głównej trasy turystycznej i ceny wracają do szwedzkiej normalności.';
$podroze1.='<p class="p1">W kanałach i na jeziorze Mälaren wraca życie. Wielkie płaty lodu odrywają się od siebie i płyną z nurtem rozbijając się gdzieniegdzie o betonowe nabrzeże i filary mostów. Łabędzie i kaczki wykorzystują je jako darmowe tramwaje i wyglądają wiosny.';
$podroze1.='<p class="p1">Jak każdy z nas.';
$podroze1.='<p class="p1"><i><font size=-4>rs, Linkoping, luty 2019</font></i>';
include 'podr_sma.php';


//require_once("funkcje.php");
//data_index($podroze1,'meta data próbne ąśćŚ');
?>
