<?php
  include 'funkcje.php';
  include 'conf.php';

  $podroze1 = '<p class="p4">Szwecja 2011<br>';
//Wzdłuż Kinda Kanal - wycieczka rowerowa 20110618
	$podroze1.='<p class="p3"><a name="WzdluzKindaKanal"></a>Wzdłuż Kanału Kinda';
	$podroze1.='<p class="p1"> Ta wycieczka chodziła za mną od bardzo dawna. W zeszłym roku było już bardzo blisko, ale nie dopisała pogoda. Tym razem też deszcz próbował nam popsuć szyki, ale nie zraziliśmy się letnim kapuśniakiem i wyruszyliśmy w czwórkę w stronę pierwszej śluzy - Nykvarn. Tam dołączył do nas Krzysiek na swoim rowerze własnej konstrukcji i wycieczka została oficjalnie rozpoczęta. Cel: odwiedzenie <a href="http://www.kindakanal.se/kartor.html">wszystkich dziewięciu śluz</a> kanału żeglugowego <a href="http://www.kindakanal.se">Kinda</a> zbudowanego na części rzeki Stangan.';
    $podroze1.= foto_line('szwecja2011/kinda_20110716/kindaa',3,4,'_s');
	$podroze1.='<p class="p1">Popadało trochę, potem niebo się rozpogodziło, a my rozpoczęliśmy swoisty wyścig ze statkiem wycieczkowym "Kisa" płynącym z portu w Linköping kanałem aż do Rimforsy. Dla pasażerów łodzi to też była rozrywka, gdyż ten sposób podróżowania wzdłuż kanału na dłuższą metę może wydawać się nudny. No bo ile razy można przeprawiać się przez śluzy w ten sam sposób: wpłyń, zamknij śluzę, napuść wody, otwórz wrota, przepłyń do kolejnej komory, zamknij śluzę, itd itd... Na trzeciej tamie część pasażerów udała się zatem pod pokład kontemplować specjały przygotowane przez pokładowego kucharza i degustować lokalne trunki. Dotrzymywaliśmy wycieczce kroku (a nawet byliśmy nieco szybsi i czasem na nich czekaliśmy) aż do Sturefors, gdzie nad kąpieliskiem zrobiliśmy sobie długą i zasłużoną przerwę na lunch. Woda jednak była na tyle zimna, że nikt z nas nie zdecydował się na kąpiel.';
    $podroze1.= foto_line('szwecja2011/kinda_20110716/kindab',3,4,'_s');
	$podroze1.='<p class="p1">Do wody weszli za to co niektórzy z nas po przejechaniu całej trasy, czyli już na kąpielisku w Brokind, gdzie woda również nie przypominała ciepłotą tej śródziemnomorskiej. Za to popołudnie było słoneczne, co podnosiło nieco przyjemność zabawy. Taki to już jest specyficzny urok szwedzkich jezior: przeraźliwie zimne, ale za to krystalicznie czyste. Z wyjątkiem Roxen, które jest co prawda dość duże, ale - w porównaniu do innych szwedzkich jezior - stosunkowo płytkie.';
    $podroze1.= foto_line('szwecja2011/kinda_20110716/kindac',3,4,'_s');
	$podroze1.='<p class="p1">Powrót wybraliśmy sobie najkrótszą, lecz za to dość mocno górzystą i - co za tym idzie - malowniczą drogą. Miejscami widoki jak w Tour de France: tu zameczek, tu pole golfowe, tu krowa się pasie, a tu łoś pod lasem trawę skubie... Tylko, jak to słusznie zauważył kolega Michał, komentarza panów Jarońskiego i Wyrzykowskiego z Eurosportu brakuje. I tak wśród rozmów i żartów dojechaliśmy aż do samego Linköping.<font size=-4> (rs, 24.08.2011)</font>';
//Wiosenny spacer po lesie - wycieczka rowerowa 20110618
	$podroze1.='<p class="p3"><a name="WiosennySpacerPoLesie"></a>Wiosenny spacer po lesie';
	$podroze1.='<p class="p1">Tym razem miało być krótko, łatwo i przyjemnie. Pogoda była w sam raz na czerwcową wycieczkę rowerową. Nie za gorąco, ale również nie za zimno. Tak w sam raz. Wyjechaliśmy spod garażu na Drabantgatan punktualnie o trzynastej i pokaźną dziewięcio-osobową grupą pojechaliśmy spotkać się z wcześniej umówionymi znajomymi na Lambohowie. Potem już pojechaliśmy prosto do Malmslätt.
				<p class="p1">Mijając po lewej stronie ścieżki rowerowej wojskowe lotnisko, zajechaliśmy na leśny parking przy Kärna Mösse, spięliśmy rowery w jedną wielką rowerową górę i wyruszyliśmy na wiosenny spacer po rezerwacie. Godzinny spacerek po lesie, gdzie można znaleźć zarówno bagna, jak i bijące źródełko oraz nienaruszone od dłuższego czasu przez człowieka ostępy leśne, zakończyliśmy piknikiem koło Kärna Kyrka w Malmslätt, robiąc sobie przy okazji pamiątkowe zdjęcia przy pozostałościach kamienia runicznego. Pogoda w międzyczasie się trochę zepsuła i miłe piknikowanie zakończył nam... Deszcz.
				<p class="p1">Uciekliśmy więc z powrotem do lasu, gdzie pod ochroną liści przeszliśmy dalszą część szlaku aż do parkingu, gdzie zostawiliśmy nasze rowery. Synchronizację z pogodą mieliśmy idealną - przestało padać właśnie kiedy wyszliśmy z lasu, a w lesie parasol z drzew zaczął przepusczać zebraną podczas deszczu wodę.
				<p class="p1">Następnym etapem naszej wycieczki było znalezienie starej stacji kolejowej, gdzie miała miejsce jedna z największych katastrof kolejowych w Szwecji. Stacji już co prawda w Malmslätt nie ma, a zabytkowy budynek pozostał i mieści się w nim obecnie sklep z lampami.';
    $podroze1.= foto_line('szwecja2011/rowery_20110618/malmslatt',3,4,'_s');
	$podroze1.='<p class="p1">Zahaczając jeszcze o zewnętrzną wystawę starych samolotów w muzeum lotniczym wróciliśmy powolnym spacerowym tempem do Linköping. A dzień, już tradycyjnie, zakończył się wspólnym grillowaniem.<font size=-4> (rs, 03.07.2011)</font>'; 
//Tiry na kajaki - kajakowanie w goteborgu. Spływ kajakowy z Polskt Hem Paradis 20110611-12
	$podroze1.='<p class="p3">Tiry na... kajaki';
	$podroze1.='<p class="p1">Na kajakach już nie pływałem hohohoho-czasu, więc propozycja sobotniego kajakowania na jeziorach w rezerwacie przyrody Vättlefjäll w Göteborgu wyglądała zachęcająco. Jak zwykle więc rozpisałem ogłoszenie i rozesłałem po znajomych, i jak zwykle zainteresowanych było sporo. Zainteresowanie zmalało jednak, gdy okazało się, że trzeba przenocować pod gołym niebem. A tu namiotu nie ma, śpiworów nie ma, koców nie ma, ochoty ani na komary ani na niepewną aurę pogodową nie ma. Z zainteresowanych oprócz mnie pozostał tylko Rysio i to właśnie z nim wczesnym sobotnim rankiem wybraliśmy się moją zieloną strzałą w niemal 300-kilometrową podróż na zachodnie wybrzeże Szwecji. ';
	$podroze1.='<p class="p1">Na miejscu - kajaki!. Można byłoby powiedzieć - kajaki jak kajaki. Pływałem już na różnych: rzecznych, morskich, jedno- i dwuosobowych, ale te były prawdziwymi TIR-ami wśród kajaków. Trzy i czteroosobowe kanadyjki potrafiły pomieścić w sobie oprócz pasażerów jeszcze cały ich dobytek oraz niemałą ilość drewna na ognisko. Piękne łodzie, obładowane po burty wyglądały jak rzeczne barki, tylko... Upędzić je było trudno, szczególnie osobom niewprawionym w kierowaniu kanadyjkami, a przenosić przez progi z racji ciężaru jeszcze trudniej. Ale dzięki temu, mimo że być może nie zrobiliśmy podczas tego spływu zbyt wiele "wodnych" kilometrów, to napływałem się po pachy. Szczególnie że widoki wokół - jak w całej Szwecji - przepiękne.';
    $podroze1.= foto_line('szwecja2011/kajaki_20110611/kajaki',3,8,'_s');
	$podroze1.='<p class="p1">Samo miejsce noclegowe w lesie było już uprzednio wcześniej przygotowane przez organizatorów, można więc było odpocząć po trudach pływania delektując się wytworami kuchni ogniskowej - i tu należy się wielki szacunek dla kucharzy. Jedzenie było super i do tego tyle, że przez dwa dni nie naruszyłem żadnych zapasów, które wziąłem ze sobą.';
	$podroze1.='<p class="p1">Śmiechom, opowiadaniom i zabawie przy wtórze brzęczących komarów nie było końca. Nawet pogoda, mimo hucznych zapowiedzi synoptyków, że "bydzie, Panie, rzucało żabami, oj bydzie", wytrzymała aż do naszego przyjazdu do Linköping. <font size=-4> (rs, 20.06.2011)</font>';
//Nad zakręconą rzeką - wycieczka rowerowa 20110528
	$podroze1.='<p class="p3"><a name="NadZakreconaRzeka"></a>Nad zakręconą rzeką';
	$podroze1.='<p class="p1">Zawsze miałem ochotę tam pojechać. Zobaczyć, czy jest fajnie, czy da się łapać ryby, a jak się da, to jakie, za ile i dlaczego tak drogo. Ale trzy lata minęły i jakoś nie starczyło czasu, żeby się tam wybrać. Pewnej bardzo wietrznej majowej soboty wsiedliśmy więc na rowery i wyruszyliśmy na spotkanie kolejnej wielkiej przygody...
	<p class="p1">A wiało tak, że miejscami rower zatrzymywało w miejscu. Całe szczęście było ciepło i nie padało, jak to miało miejsce podczas niektórych naszych rowerowych wycieczek. I tak pod wiatr, sięgający czasem 8 m/s, przejechaliśmy koło lotniska w Malmslätt i mijając po drodze - jak to często w tej części Szwecji bywa - prastare kurhany i kamienie runiczne, dotarliśmy do Vikingstad.';
    $podroze1.= foto_line('szwecja2011/rowery_20110528/kurhany',3,2,'_s');
	$podroze1.='<p class="p1">Miejscowość sama w sobie nie zachwyciła nas niczym szczególnym, choć miło zobaczyć, że w tak małej mieścinie oprócz stacji kolejowej lokalnej kolejki znalazło się także miejsce dla otwartego kąpieliska i sporego ośrodka sportowego. Jest na tyle duży, że bez przyjezdnych sportowców trudno będzie go zapełnić. My skierowaliśmy się w stronę lasu, gdzie osłonięci przed wiatrem, ale niestety nie przed komarami, spożyliśmy tradycyjne wycieczkowe piwko zagryzając czipsami.
	<p class="p1">Potem już było z górki. To znaczy, może nie do końca z górki, ale z potężnym wiatrem w plecy, dotarliśmy to intrygującej mnie od dawna rzeki. Rzeczywiście, niemało trudu narobił sobie lodowiec idąc przez te tereny, bo rzeka na obrębie kilkuset metrów zakręcona jest niesamowicie, czego może nie widać dobrze na zdjęciu, ale na kawałku załączonej mapy już tak. Czy są tu ryby? Nie wiem, ale przy najbliższej okazji zapytam w sklepie wędkarskim w Linköping. W każdym razie kilku ludzi ze spinningami dyskretnie się miejscami kręciło.';
    $podroze1.= foto_line('szwecja2011/rowery_20110528/rzeka',3,2,'_s');
	$podroze1.='<p class="p1">Mijając po drodze Vikingstad Kyrka oddalony o kilka kilometrów od samej miejscowości, który zauważyliśmy bez problemu - oraz ruiny kaplicy, których mimo usilnych starań nie zauważyliśmy (następnym razem weźmiemy łopaty i szpadle), dotarliśmy spokojnie do domu na wieczornego grilla.
<p class="p1">A wiatr ciągle nie dawał za wygraną...<font size=-4> (rs, 08.06.2011)</font>'; 
//A teraz na południe - wycieczka rowerowa 20110410
	$podroze1.='<p class="p3"><a name="ATerazNaPoludnie"></a>A teraz na południe';
	$podroze1.='<p class="p1">Na północy od Linkoping odwiedziliśmy jezioro Roxen, co opisałem w artykule <a href=#PierwszeRowerowanieZaPloty>Pierwsze ko... Rowerowanie za płoty</a>. Tym razem nasze rowery skierowaliśmy bardziej na południe, nad jezioro Arlangen. 
	<p class="p1">Wyjazd zaplanowaliśmy już tradycyjnie, w samo południe. Troszkę tym razem dla mnie za wcześnie, gdyż mimo że wstałem równo ze świtem, nie starczyło mi czasu, żeby upiec porządnie chleb, przez co muszę przez najbliższych kilka dni raczyć się zakalcem. Już ta poranna przygoda zapowiadała, że nie będzie łatwo. Wrażenie to potęgował wiatr pochylający rosnące za oknami bezlistne jeszcze zupełnie gałęzie drzew. 
	<p class="p2"><b>Z wiatrem w plecy...</b>
	<p class="p1">Zaczęło się przyjemnie: praktycznie całą drogę do Sturefors towarzyszyła nam ścieżka rowerowa i silny wiatr w plecy. Jednym słowem - sielanka. W Sturefors krótki postój, odpoczynek przy moście kolejowym nad Stangan, a potem szybki odcinek już mniej uczęszczaną drogą do pałacu położonego tuż nad brzegiem jeziora.'; 
    $podroze1.= foto_line('szwecja2011/rowery_20110410/sturslu',3,3,'_s');
	$podroze1.='<p class="p1">Do pałacu prowadzi stara żwirowa droga wśród przeszło stuletnich drzew, z lewej strony ciągnie się zabytkowy ogród z zadbanym prostokątnym stawem i ciekawą roślinnością. Po prawej stronie - jezioro Arlangen i wpływającą do niego żeglugową Stangan, a zarazem Kinda Kanal wraz z konserwowanymi przed sezonem drewnianymi dziewiętnastowiecznymi śluzami. Parkowa ławka z widokiem na pałac położona pod potężnym wiekowym dębem wydawała się być idealnym miejscem na "Pierwszą Stację Browarkową". Zresztą sami zobaczcie:';
    $podroze1.= foto_line('szwecja2011/rowery_20110410/sturefors',3,4,'_s');
	$podroze1.='<p class="p2"><b>Potem w twarz...</b>
	<p class="p1">Potem zaczęły się schody: wiatr wiał prosto w twarz, a droga była malownicza. Nie dość, że kręciła piruety przez tereny jak z kartek pocztowych, to wiodła przez pokaźne górki, na których zboczach przysiadły parterowe drewniane domki pomalowane tradycyjną szwedzką farbą w kolorze Falunrot. Górki oprócz malowniczości mają to do siebie, że trzeba pod nie podjechać. A pod wiatr nie jest łatwo. Z ulgą powitaliśmy więc miejsce "Drugiej Stacji Browarkowej" przy śluzach w Slattefors.';
    $podroze1.= foto_line('szwecja2011/rowery_20110410/slattefors',3,2,'_s');
	$podroze1.='<p class="p2"><b>...A na koniec w oczy</b>
	<p class="p1">Szlakiem turystycznym przez pole golfowe, po przejechaniu malowniczego, bardzo wąskiego drewnianego mostu nad Stangan, przy stromym podjeździe pod kościół w Landeryd Ryśkowi urwał się łańcuch. I o ile do tej pory miałem dość dobre zdanie na temat szwedzkich mechanizmów przerzutek rowerowych ukrytych w bębnie tylnego koła, o tyle teraz wiem, że nigdy nie wybiorę się takim rowerem w dalszą drogę. Mimo że wiozłem ze sobą mój standardowy zestaw naprawczy wraz z kluczem do rozpinania łańcucha, o tyle po skróceniu go o zgubione oczko był już niestety za krótki, by założyć go z powrotem na zębatki, a gruba opona skutecznie uniemożliwiała przesunięcie koła bardziej do przodu. W przypadku standardowego roweru z kasetą na zewnątrz, ewentualnie stracilibyśmy tylko dwa lub trzy przełożenia, a tu zostało nam zdjąć łańcuch, zebrać graty i wziąć Rysia na hol, a raczej pchać go przed sobą. Niestety, rowery z torpedem mają to do siebie, że nikt nie zwraca uwagi na sprawność przedniego hamulca. A - jak wiemy - w takim przypadku jak nie ma łańcucha, to nie ma też hamowania. Jak można się domyśleć, było ciężko więc i pod górkę i z górki.
	<p class="p2"><b>Zakończenie</b>
	<p class="p1">Szczęśliwie wróciliśmy do domu. W tej sytuacji, co zrozumiałe, odpuściliśmy już sobie "Trzecią Stację Browarkową". Ale nic straconego. Na następnej wycieczce nadrobimy i zaplanujemy również czwartą. Mimo kłopotów wycieczka była udana: pogoda przyjemna, widoki piękne, a dzień wolny, więc nie było się do czego spieszyć. Teraz przerwa na Święta Wielkanocne i Walpurgię, a potem... Potem będzie Rimforsa ze swoimi punktami widokowymi położonymi na wysokich na kilkadziesiąt metrów urwiskach. Chętnych już teraz zapraszam.<font size=-4> (rs, 11.04.2011)</font>';

//Pierwsze ko... Rowerowanie za płoty - wycieczka rowerowa 20110402
    $podroze1.='<p class="p3"><br><a name="PierwszeRowerowanieZaPloty"></a>Pierwsze ko... Rowerowanie za płoty<br>';
	$podroze1.='<p class="p1">Już budząc się wiedziałem, że prognozy się sprawdziły i będzie ładna pogoda. Pierwszy raz od czasu przyjazdu usłyszałem wrzeszczące za oknem mewy – nieomylny znak, że idzie wiosna. A z wiosną – większy optymizm, chęć do działania i większa ochota do ruchu na świeżym powietrzu.
Planowaliśmy wycieczkę nieco krótszą, około dwudziestokilometrową. Wyszła troszkę dłuższa, bo trasę wydłużyliśmy do trzydziestu kilku. Po prostu szkoda było pięknej, wiosennej pogody na siedzenie w domu i ślęczenie przed Facebookiem czy innym Onetem.
<p class="p1"><b>Pierwszy przystanek – Kaga Kyrka</b>
<p class="p1">Wyjechaliśmy spod Ikei na Tornby zgodnie z ustaleniami w samo południe. Na początku jechało się przyjemnie, z wiatrem i z górki, po skręcie w drogę do Kagi wiatr zrobił się bardziej uciążliwy, a i górki jakieś takie trudniejsze.';
    $podroze1.= foto_line('szwecja2011/rowery_20110402/kaga',3,4,'_s');
	$podroze1.='<p class="p1">Kościół w Kadze jest jednym z najstarszych w Östergotland. Leży na tzw. "Drodze Królewskiej", którym to traktem w średniowieczu podążał każdy nowo koronowany król Szwecji odwiedzając swoje ziemie. W jedną ze ścian kościoła wbudowany jest duży kamień runiczny. Wewnątrz podobno są piękne malunki na scianach – niestety, zamknięty na cztery spusty.
<p class="p1"><b>Drugi przystanek – Ledberg</b>
<p class="p1">Z Kagi pojechaliśmy w kierunku Ledberga – praktycznie całe pięć kilometrów pod górkę i pod wiatr. Ale warto było. Droga wiedzie tuż nad samą rzeką Svartan, częściowo przez jakieś dawne fabryki, przy których stare drewniane i metalowe kładki przełożone przez rzekę są tak zniszczone, że nie zachęcają do przejścia na drugą stronę. Z daleka widać kurhan w Ledbergu – największy w tej części Szwecji. Krótki odpoczynek przy kościele i jedziemy do Vreta Kloster.';
    $podroze1.= foto_line('szwecja2011/rowery_20110402/ledberg',3,3,'_s');
	$podroze1.='<p class="p1"><b>Trzeci przystanek – Berg, Vreta Kloster</b>
<p class="p1">Od tej strony do klasztoru jeszcze nie wjeżdżałem. Droga kręta i pofałdowana, dookoła lasy, pola i płynąca między drzewami Svartan. Niby od rana dość wysoka temperatura, ale śnieg gdzieniegdzie zalega jeszcze dużymi placami. Na niebie ptaków co niemiara: gęsi, kaczki, rybitwy, a nawet skowronek zaczął swoje nawoływanie do wiosennych prac w polu. Ludzie także czują wiosnę. W każdym obejściu jakieś prace porządkowe: wygrabianie starych liści, naprawa dachów czy pierwsze prace ogrodowe. Mimo że tym razem z wiatrem i przez większość siedmiokilometrowego odcinka z górki, ostatni stromy fragment dał mi się we znaki. Brak kondycji po zimie odczuwam dość dotkliwie i muszę chyba poważnie popracować nad sobą przed planowaniem dłuższych rowerowych ekspedycji.';
    $podroze1.= foto_line('szwecja2011/rowery_20110402/vreta',3,2,'_s');
	$podroze1.='<p class="p1"><b>Czwarty i ostatni przystanek – Berg, plaża nad jeziorem Roxen</b>
<p class="p1">Przy Vreta Kloster nie spędziliśmy dużo czasu. Kościół był zamknięty, więc po krótkim spacerze po starych klasztornych budynkach – lub raczej ich pozostałościach – pojechaliśmy do ostatniego punktu naszej wycieczki. Krótka wizyta w sklepie, uzupełnienie zapasów i wkrótce już piliśmy piwo zagryzając ciastkami na wyciągniętym z jeziora pomoście na plaży w Bergu. Śluzy ze spuszczoną wodą (Kanał Gota nie został jeszcze przygotowany do nowego sezonu, pewnie trzeba czekać aż rozmarznie położone wyżej jezioro Boren) wyglądają potężnie i groźnie. Strach podejść nad sam brzeg, żeby przypadkiem nie poślizgnąć się i nie wpaść do pięciometrowej kamiennej dziury. Ciężko byłoby przeżyć bez szwanku taki upadek. ';
    $podroze1.= foto_line('szwecja2011/rowery_20110402/berg',3,4,'_s');
	$podroze1.='<p class="p1">Jezioro jest jeszcze praktycznie w całości zamarznięte. Trudno sobie wyobrazić, że pod koniec maja, jak pogoda dopisze, pełne będzie pływających jachtów i kąpiących się przy brzegach ludzi.
<p class="p1">Ani się nie obejrzeliśmy zrobił się wieczór i trzeba było wracać do domu. Tym razem już całą drogę pod wiatr.<font size=-4> (rs, 03.04.2011)</font>';

//  $podroze1.= foto_line('ochodzita2007/karczma',3,9,'_s');
include 'podr_sma.php';
//require_once("funkcje.php");
//data_index($podroze1,'meta data próbne ąśćŚ');
?>