<?php
  include 'funkcje.php';
  include 'conf.php';
    $podroze1 = '<p class="p3">Tallin, wrzesień 2011<br>';
//Wiedeń i dolina Wachau 20110805
$podroze1.='<p class="p1">Wyszedłem na pokład pooddychać morskim powietrzem. Wielki prom leniwie rozcinał fale płynąc powoli pomiędzy wysepkami sztokholmskiego archipelagu. Wrześniowe słońce zachodziło za horyzont. Rześkie powietrze odświeżało umysł, a silny wiatr wywiewał resztki wypitego alkoholu z głowy. Jeszcze kilka godzin I będziemy w Talinie, a tam czeka nas całodzienne intensywne zwiedzanie.';
$podroze1.='<p class="p1">Wyruszyliśmy w piątek prosto z pracy. Droga z Linkoping do Sztokhomu minęła pod znakiem towarzyskich rozmów podtrzymywanych przez butelkę polskiej wódki I kierowcę, który na swoją kolejkę musiał czekać aż do wieczora. Przebiliśmy się dość sprawnie przez popołudniowe stołeczne korki I koło osiemnastej zaokrętowaliśmy się na statek.';
$podroze1.='<p class="p1">Baltic Queen, bo tak się on nazywał, jest potężnym promem pływającym na trasie pomiędzy Szwecją I Estonią. Rozkład rejsów zaplanowano tak, aby można było w nocy wyspać się na promie, a potem cały dzień poświęcić na zwiedzanie I wrócić na ten sam statek odpływający do Sztokholmu późnym popołudniem, aby rano obudzić się z powrotem w Szwecji. “Wyspać się” jednak to pojęcie względne. Baltic Queen, podobnie jak wszystkie promy pływające na trasie pomiędzy Szwecją a Estonią, Łotwą czy Finlandią, to typowy prom imprezowy: przez całą noc odbywają się tam występy artystyczne, dyskoteki, dansingi, czynne są kasyna, otwarte do późna są restauracje i sklep bezcłowy, który jest jednym z najbardziej obleganych miejsc na promie. Mimo wszystkich tych atrakcji udało nam się w niezłej kondycji zejść z promu i udać się do miasta. Bez przewodnika - ostatnio jestem zwolennikiem odkrywania świata na nowo zamiast odwiedzania miejsc sugerowanych przez innych - ale ze szczątkowymi informacjami o mieście wydrukowanymi kilka dni wcześniej z Internetu oraz mapą, którą dostaliśmy w pierwszej napotkanej informacji turystycznej skierowalimy się w kierunku widocznych z daleka murów obronnych estońskiej stolicy.';
$podroze1.='<p class="p1">Tallin to miasto wyjęte wprost ze Średniowiecza. Tak można byłoby stwierdzić na pierwszy rzut oka. Promy wpływają praktycznie do samego centrum, skąd do starego miasta jest tylko kilkaset metrów. Dopiero z wysokich murów obronnych można zobaczyć panoramę bardziej współczesnych części tej bałtyckiej stolicy, otoczoną mnóstwem zieleni. Stare miasto jest na tyle małe, że można je przejść wzdłuż i wszerz w ciągu jednego dnia kilka razy, zatrzymując się po drodze w miejscach, gdzie można napić się lokalnego piwa Saku. Cena iście europejska: 4 EUR za kufel, a smak... Szczerze mówiąc Lvivskie we Lwowie bardziej mi smakowało.';
$podroze1.='<p class="p1">Jak w każdym turystycznym mieście turyści nie są tu oszczędzani. Każda, choćby najmniejsza atrakcja kosztuje, i to niemało. Za dwa euro weszliśmy na taras spacerowy nad murami obronnymi, po to tylko, żeby zobaczyć jak stamtąd nic nie widać i napić się SAKU po... 6 EUR za kufel! Sam taras miał długość około dwudziestu metrów. Ale to chyba domena  wszystkich turystycznych miast. No i mimo wszystko i tak jest zdecydowanie taniej niż w Szwecji.';
$podroze1.='<p class="p1">Co do samego zwiedzania, tak jak już pisałem wcześniej - kierowaliśmy się bardziej instynktem niż jakimś formalnym przewodnikiem. Kiedy już obeszliśmy miasto dookoła wzdłuż świetnie zachowanych murów obronnych z malowniczymi basztami robiąc przy okazji miliony zdjęć z szańców widokowych (ach te cyfrowe aparaty...), przeszliśmy do zwiedzania wnętrz. Oczywiście tych, do których dało się wejść. Osobiście polecam prawosławną cerkiew oraz gotycki kościół Św. Mikołaja. Dla Polaków sentymentalne znaczenie może mieć tablica poświęcona internowanym w 1939 roku marynarzom polskiego okrętu podwodnego Orzeł (okręt uciekł mimo wszystko w brawurowy sposób do Wielkiej Brytanii). Napotkaliśmy ją wmurowną w ścianę jednego z budynków włócząc się popołudniową porą po wąskich i malowniczych brukowanych uliczkach starego miasta. W ten sposób doszliśmy do głównej handlowej ulicy zapełnionej straganami z różnymi wyrobami mniej lub bardziej związanymi z Estonią.';
$podroze1.='<p class="p1">Późnym popołudniem szybki obiad w miejscowym McDonaldsie (ciekawe, czy są jeszcze turystyczne miasta, gdzie nie ma McDonalda) i powrót do portu. Po drodze udało nam się zrobić jeszcze zakupy w lokalnym supermarkecie: kupiłem między innymi chleb, którego ciągle mi brakuje w Szwecji I kilka dużych butli kwasu chlebowego, za którego smakiem tęskniłem od czasu mieszkania we Lwowie, a którego w Szwecji kupić się nie da. Jest równie dobry jak na Ukrainie, czego nie można powiedzieć o tym sprzedawanym w Polsce w sklepach z tak zwaną “zdrową żywnością”. Ceny alkoholu w zwykłym sklepie też już są zdecydowanie niższe niż na Starym Mieście. Piwo Saku kosztuje około 1 EUR za butelkę lub puszkę, a różnego rodzaju wódki są w cenach podobnych do polskich. Nie dziwię się, że tego typu wycieczki mają tak duże powodzenie wśród mieszkańców Szwecji.';
$podroze1.='<p class="p1">Na pożegnanie jeszcze rzut oka na port, zapełniony jachtami i wędkarzami, którzy zajęli każdą wolną część nabrzeża. Jachty wkrótce znikną, gdyż jesienne słoty coraz bliżej. Czy znikną wędkarze? Tego nie wiem. Może odwiedzę to miasto jeszcze raz zimą i wtedy się przekonam. Podziwiając w zachodzącym słońcu z pokładu promu oddalającą się panoramę miasta planowałem już kolejny rejs. Tym razem będzie to Ryga.';
$podroze1.= foto_line('tallin2011/tallin',3,27,'_s');

//  $podroze1.= foto_line('ochodzita2007/karczma',3,9,'_s');
include 'podr_sma.php';
//require_once("funkcje.php");
//data_index($podroze1,'meta data próbne ąśćŚ');
?>