<?php
  include 'funkcje.php';
  include 'conf.php';

  $podroze1 = '<p class="p3">Wiedeń i Dolina Wachau, sierpień 2011<br>';
//Wiedeń i dolina Wachau 20110805
$podroze1.='<p class="p1">Dolina Wachau tonęła w sierpniowym słońcu. Ludzie leniwie porozciągani przy pokładowych stolikach rozkoszowali się serwowanymi wprost z okrętowej restauracji przysmakami: drinkami, kawą oraz tortem Sachera, który zarówno pod względem wyglądu jak i smaku przypominał dość mocno znanego w Polsce “murzynka”. Kapitan przez głośniki zapowiadał kolejny port...';
$podroze1.='<p class="p1">Już od około godziny podziwialiśmy uroki tej części Austrii z pokładu statku wycieczkowego płynącego powoli po Dunaju i oglądaliśmy przepiękne wzgórza doliny Wachau pokryte lasami oraz winnicami wystawionymi na letnie promienie słoneczne. Co kilka chwil zza wzgórz ukazywały nam się urokliwe ruiny austriackich zamków obronnych, należących kiedyś zarówno do Habsburgów jak i innych tutejszych rodów szlacheckich. A jeszcze niecałą godzinę wcześniej w miasteczku, w którym wysiedliśmy z autobusu, podziwialiśmy barokowy klasztor benedyktynów z przepięknym dziedzińcem i biblioteką ze ścianami wyłożonymi książkami w identycznie wyglądających okładkach. Podobno to taki zamysł architektów, aby zrobić na oglądających większe wrażenie, a reszta olbrzymiej ilości książek nie jest wystawiona na widok publiczny. Pierwsze wzmianki o tym klasztorze pochodzą z XI wieku i choć był wielokrotnie przebudowany, nadal jest wielką atrakcją turystyczną tej doliny. Miasteczko Melk, bo tak się ono nazywa, znane jest również z tego, że podczas II Wojny Światowej mieściła się filia obozu koncentracyjnego w Mauthausen. My jednak nie zajmując się zbytnio historią i ciągle podziwiając malownicze widoki dotarliśmy do portu rzecznego, gdzie zaokrętowaliśmy się na nasz statek.';
$podroze1.= foto_line('wieden2011/rzeka',3,4,'_s');
$podroze1.='<p class="p1">Obszar ten słynie z win. Winnice widać dosłownie wszędzie. Zagospodarowana jest niemal każda góra. Każde nasłonecznione zbocze, które mijaliśmy naszym stateczkiem, pokryte było równiutkimi rzędami winorośli i aż trudno sobie wyobrazić, ile pracy wymaga utrzymanie tych pól w takim stanie, by gwarantowały jak najlepsze zbiory. Przygotowanie gleby (musi być na tyle przepuszczalna, by nie pozwalała na odkładanie się wody w owocach), a nawet przycinanie liści by cała energia szła w owocowanie, wymaga od właścicieli pól niesamowitego wysiłku. Ale efekty są wyśmienite.';
$podroze1.='<p class="p1">Naszą stacją końcową było liczące niespełna 1.000 mieszkańców miasteczko Dürnstein. Korzystając z wolnego czasu i wylewając przy okazji litry potu wdrapałem się na okoliczną górę z ruinami średniowiecznego zamku, od którego miasto odziedziczyło swoją nazwę: od niemieckiego dürr oznaczającego sucha oraz Stein - skała. Warto było, bo widok stamtąd jest niesamowity: Dunaj wije się między wzgórzami niby wąż, a w doliny porośnięte lasami i wzgórza ze swoimi winnicowymi zboczami tworzą bajkowy krajobraz. Całości obrazu dopełniają kolorowe dachy i wieże kościoła w mieście położonym u stóp zamkowej góry. Dürnstein znane jest z produkcji win i likierów, a przede wszystkim słynie z młodego wina, więc podczas gdy ja fotografowałem z góry okolicę, moje panie wybrały się na zakupy. Pokusiliśmy się na kilka butelek lokalnych trunków, między innymi na likier przypominający na pierwszy rzut oka Advocata, tylko zagęszczony makiem, którego, jak się dowiedzieliśmy od naszej pani przewodnik, uprawa w Austrii jest prawnie dozwolona. Czy ceny są wysokie? Możliwe, że te lokalne specjały można kupić taniej w wielu sklepach w Wiedniu, a może nawet jeszcze taniej w tamtejszych supermarketach, ale cóż to za radość napić się miejscowej nalewki wprost od producenta. Nawet jeżeli czasem kosztuje nas to kilka Euro więcej.';
$podroze1.= foto_line('wieden2011/zamek',3,4,'_s');
$podroze1.='<p class="p1">Wycieczka do Doliny Wachau rozdzielała dwa dni zwiedzania Wiednia - miasta, które wywarło na nas duże wrażenie podczas odbytej kilka lat temu wycieczki, a z którego zwiedzania nie mogliśmy być w żaden sposób zadowoleni. No cóż, wycieczka trwała dwa dni, z czego większość zajmowała podróż i zwiedzanie czeskich Moraw. Teraz mieliśmy nieco więcej czasu, w tym całe dwa dni na sam Wiedeń. Ponownie więc, choć tym razem trochę wolniej, chodziliśmy średniowiecznymi uliczkami pomiędzy kolejnymi budynkami pałacu Hofburg. Po raz pierwszy zwiedzaliśmy cesarskie groby i widzieliśmy aktualną siedzibę Wielkiego Mistrza Zakonu Najświętszej Marii panny znanego u nas jako Zakon Krzyżacki (tak, tak, on ciągle istnieje i ma się całkiem dobrze). Piliśmy kawę w Rosenberger, które co prawda jest bardziej  jadłodajnią skierowaną na turystów niż typową wiedeńską kawiarnią, oraz oglądaliśmy wnętrze Opery Wiedeńskiej i restaurowanego w tym czasie letniego pałacu Habsburgów - Shönbrunn. Na zwiedzanie pałacowych ogrodów tym razem niestety zabrakło czasu. Ale to nic dziwnego, bo żeby zapoznać się z wszystkimi atrakcjami tego pięknego miasta, trzeba byłoby przeprowadzić się tu na jakiś czas i - nawiasem mówiąc - nie byłaby to dla mnie osobiście jakaś wielka przykrość. Wiedeń jest miastem przyjaznym do życia. Podobnie jak w szwedzkim miasteczku Linköping, w którym spędzam w ostatnich latach cieplejsze miesiące roku, jest tu mnóstwo zieleni, parków i ścieżek rowerowych, zdecydowanie mniej natomiast skandynawskiego chłodu i spustoszenia. Bo wiedeńska starówka zawsze jest pełna ludzi. Ulice i kawiarnie zapełnione są nie tylko turystami, ale również mieszkańcami mającymi w tutejszych restauracjach swoje ulubione stoliki, przy których mogą usiąść i w spokoju napić się kawy czytając poranną prasę bądź rozmawiając z przyjaciółmi. A picie kawy tutaj to swoisty rytuał. Jeżeli komuś się bardzo spieszy - nie zajmuje miejsca przy stoliku. Kawę wypija przy barze.';
$podroze1.='<p class="p1">W oddali widać wzgórza. Z jednej strony Karpaty kończą swoją dominację w Europie, a z drugiej zaczyna się już przedgórze alpejskie. Z jednej z tych niewysokich górek - z Kahlenbergu - król Sobieski we wrześniu 1683 roku wyruszał na czele zjednoczonych wojsk w odsiecz oblężonemu przez Turków miastu. Jeżeli ma się trochę szczęścia i trafi się na dobrą pogodę, można stąd podziwiać panoramę całego Wiednia oraz najbliższej okolicy. My to szczęście mieliśmy. Sącząc leniwie lemoniadę w znajdującej się na samym szczycie kawiarni (a tak w ogóle czy jest tu jakieś miejsce, gdzie nie ma kawiarni?) staraliśmy się rozpoznać najbardziej charakterystyczne punkty tego wielkiego miasta. Nie jest to takie trudne: gdy zlokalizuje się wieżę telewizyjną - plan całej miejscowości ułoży się już sam.';
$podroze1.= foto_line('wieden2011/wieden',3,4,'_s');
$podroze1.='<p class="p1">Przed wyjazdem do domu odbyliśmy krótki spacer po Wiener Prater, który to park wraz z niedawno wybudowanym z okazji Mistrzostw Europy w piłce nożnej nowym stadionem i ogromnym wesołym miasteczkiem tworzy miejsce rozrywki i wypoczynku, gdzie wiedeńczycy chętnie spędzają wolne dni.';
$podroze1.='<p class="p1">Podczas naszej krótkiej wycieczki nocowaliśmy nieopodal Wiednia, w malutkim miasteczku Orth nad Dunajem. Z okien poddasza miejscowego hoteliku wpatrywaliśmy się wieczorami w pięknie oświetlony miejscowy średniowieczny zamek i planowaliśmy kolejną wizytę u naszego bardzo gościnnego gospodarza. Kto wie, może następnym razem będzie to już całkiem prywatna wizyta, bo Wiedeń to miasto, które chyba nigdy nam się nie znudzi.';

//  $podroze1.= foto_line('ochodzita2007/karczma',3,9,'_s');
include 'podr_sma.php';
//require_once("funkcje.php");
//data_index($podroze1,'meta data próbne ąśćŚ');
?>