<?php
include 'funkcje.php';
include 'conf.php';

$przygoda1='<p class="p4">Szwedzkie powroty o kiju';
$przygoda1.='<p class="p3">Tak myślą szczupaki (Rzeka Stångån)';
$przygoda1.='<p class="p1">Jadąc do Szwecji po raz pierwszy myślałem, że nałowię szczupaków od groma. Wszyscy tak mówili. Wszyscy dookoła. Znajomi, rodzina, telewizja, wędkarskie gazety, a nawet Internet. Gdyby drzewa nad Pilicą potrafiły gadać, pewnie powiedziałyby to samo: tu szczupaków nie ma, jedź do Szwecji, stamtąd można je wybierać reklamówkami.
<p class="p1">Teraz mówię inaczej. Mówię, że do szczupaków trzeba dojrzeć. Są zarówno i w Polsce jak i w Szwecji. Są w większości naszych i tamtejszych zbiorników. Tylko trzeba je wytropić.
<p class="p1"><b>Tropiciel</b>
<p class="p1">Zrozumiałem to rok temu jesienią, kiedy zacząłem je łowić regularnie. Pomogła mi obserwacja okolicy i rozmowa z pewnym czlowiekiem. Ale zacznijmy od początku.
<p class="p1">Na początku łowiłem białe ryby. Wszyscy wiedzą, że białe ryby nie są białe i do dziś nie wiem, czemu nazywa się je białymi, ale mniejsza z tym. Łowiłem więc białe ryby. Od czasu do czasu wyciągałem tylko mały, składany spinning, zapinałem na przypon z plecionki średnich rozmiarów blachę lub wirówkę i rzucałem w czarną otchłań wody. W większości przypadków jednak na próżno. Kilka razy udało mi sie w ten sposób przełowić stado okoni (wyciągając z niego średnie, czasem prawie trzydziestocentymetrowe sztuki), a raz, a było to w listopadzie 2006 roku, udało mi się w ten sposób na zalewie Brzózki kolo Byczyny złowić szczupaka. Miał 63 centymetry i był moją największą złowioną rybą w życiu. Zaraz potem tata złowił kolejnego, mniejszego o 10 centymetrów i pamiętam, że obnosiłem się z tymi szczupakami przed obiektywem aparatu jak Artur Żmijewski z ludzkimi głowami w "Psach 2". Od tamtej pory szczupaków nie łowiłem. Ale zacząłem na mnie polować. Małe ryby po prostu przestały mnie cieszyć, nawet jeśli bylo ich dużo i brały nieźle. Wiedziałem, że od tej pory wędki gruntowe nie będą używane przeze mnie zbyt często.
<p class="p1">Polowałem tak na te piękne ryby dwa lata z marnym skutkiem. Po pierwsze czas nie pozwalał na częste przebywanie nad wodą, a po drugie jak już tam byłem, to powtarzałem stare błędy, a co za tym idzie łapałem okonie. Po pierwszym szczupaku nauczyłem się jednego: jeśli czujesz, że w wodzie jest szczupak - trzeba założyć odpowiedni przypon.
<p class="p1">Sytuacja zmieniła się diametralnie w 2008 roku, kiedy otrzymałem możliwość półrocznego wyjazdu na kontrakt do Szwecji. - No, teraz się nałowię po pachy - pomyślałem biorąc ze sobą malutki spinning i kilka blaszek. Odwiedziłem miejscową rzekę Stångån kilka razy, bo na więcej nie starczyło czasu - byłem zafascynowany Szwecją i starałem się zwiedzić całą okolicę, nie marnując czasu na siedzenie w domu lub nad rzeką. Ale od czasu do czasu budziła się we mnie przemożna ochota na upolowanie cętkowanego drapieżnika. Półroczny pobyt skończył się złowieniem kilku okoni i płoci, gdy spinning przerabiałem na gruntówkę i zarzucałem koszyczek zanętowy pod drzewo. Rok później było już trochę lepiej, bo nauczyłem się regularnie łapać okonie. Ale szczupaków nadal nie łapałem. Czasem tylko widziałem jak miejscowi "Szwedzi" (później dopiero zauważyłem, że w Stångån ryby łowią w większości imigranci) wyciągają duże szczupaki. Na jaką przynętę - nie zdołałem zauważyć. A głupio mi było iść i się zapytać. 
<p class="p1"><b>Gazety</b> 
<p class="p1">W gazetach naczytałem się, że jeżeli szczupaki to tylko z jezior, albo ze szkierów. I że bez łodzi, przewodnika, który wie, gdzie ryby żerują, wędki za sto tysięcy złotych z kołowrotkiem za jeszcze większą kwotę, oczywiście plecionki, trójwymiarowych przynęt Rapala po 100 złotych każda i oczywiście echosondy, to szczupaka złowić się nie da. Zapragnąłem więc chociaż raz połowić w jeziorze, a dzięki uprzejmości przyjaciół zostaliśmy z kolegą Witkiem zaproszeni do domku letniskowego nad malowniczym Asunden, które słynęło z wielkich zębaczy. Całą wyprawę opisałem w opowiadaniu “Asunden”, a skracając ją do niezbędnego minimum napiszę, że złowiłem jedną... Płoć. A przyjaciele wędkarze, z którymi łowiliśmy - kilkanaście okoni, które zresztą zjedliśmy na obiad ze smakiem. I ani jednego szczupaka. Ani na trolling, ani na spinning, ani... Ani nic. No nie ma szczupaków i już. I nie pomogła nawet łódź i jedno z najsłynniejszych jezior w Szwecji. Przeżyliśmy za to piękny dzień nad wodą i to jest jeszcze jeden powód, drogi czytelniku, dla którego warto jest się oderwać od komputera, spakować wędkę i pojechać nad wodę, albo gdziekolwiek, korzystając z tego, że mamy słońce nad głową i możemy się samodzielnie poruszać. Ale wracajmy do szczupaków.
<p class="p1"><b>Spinning</b> 
<p class="p1">Po tym roku doszedłem do wniosku, że albo szwedzkie wody są przereklamowane i kompletnie przełowione, albo ja nie umiem łowić. Całe szczęście szybko zrozumiałem, że jest to drugie. Następnego roku przyjechałem samochodem, wziąłem wszystkie wędki jakie mam, i... Zacząłem łowić tylko jedną - spinningową. Ale poszedłem po rozum do głowy i wyciągnąłem wnioski z poprzednich lat. Przede wszystkim zacząłem obserwować rzekę. Nie, nie wodę. Raczej nadrzeczny krajobraz. Wodę oczywiście też i teraz mogę powiedzieć, że czytam z niej jak otwartej książki. Co prawda obcojęzycznej, bo ani ukształtowania dna, ani ryb stojących w toni czy przy brzegach w głębinach zobaczyć nie mogę, ale wnikliwa obserwacja uciekającej drobnicy, polujących rybitw i mew oraz - co najważniejsze - ludzi, pozwoliła mi nabrać przekonania, że w tej wodzie są ryby. Dużo ryb!
<p class="p1"><b>Obserwowałem ludzi</b>
<p class="p1">Kiedy ich wczesną wiosną nie było nad rzeką - szanse na ryby były marne. Próbowałem co prawda rzucać, ale z marnym skutkiem. Gdybym popatrzył wtedy na martwą zupełnie wodę i wodne ptaki, które zupełnie w nosie miały polowanie na ryby, spakowałbym się szybko i pojechałbym do domu. A jak nie do domu, to na jakąś wycieczkę krajoznawczą, zamiast tracić czas nad rzeką. Im dni były dłuższe i cieplejsze, tym więcej nad rzeką pojawiało się ludzi. Łowili przede wszystkim okonie na zestaw z dwoma haczykami. Czasami wynosili ich znad rzeki całe wiadra albo reklamówki. Operacja jest szybka: zarzuca się wędkę z dwoma przynętami i ciężarkiem na bocznym troku (coś na wzór naszego "pater noster"), a potem zwija się go powoli. Gdy okonie żerują dobrze, zwykle za każdym rzutem przyciąga się co najmniej jedną sztukę. A nierzadko dwie. Mimo że ja w ten sposób nie łowiłem, to zacząłem łowić okonie w sposób regularny na spinning, zakładając na przynętę twistery w kolorze motor oil, bądź jaskrawo seledynowe z czerwoną główką. W ten sposób cały sezon poświęciłem na łowienie okoni i myślę, że w miarę nauczyłem się ich łowić. Poznałem przy tym nad rzeką wielu ciekawych ludzi, również rodaków. Okoni nałowiłem sporo, większość z nich trafiła z powrotem do wody, gdyż mimo że są bardzo smaczne i były ich tu naprawdę nieprzełowione ilości, to na samą myśl o ich skrobaniu odechciewa mi się jeść. Natura wiedziała, jak się chronić w tym wypadku. Przynajmniej przede mną.
<p class="p1">W kolejnym roku powiedziałem okoniom dość, zmieniłem spinning na lekką 30-gramową dwu-i-półmetrową wklejankę z również lekkim kołowrotkiem o rozmiarze 2500 i zacząłem ponownie
<p class="p1"><b>polować na szczupaki</b>.
<p class="p1">Na początku szło niemrawo. Naczytałem się mistrzów wędkowania, że należy zaczynać od wirówek, obławiać woblerami, a jak już nic nie poskutkuje to wrzucić jakieś gumy w ulubionym przez szczupaki kolorze i... Nadal nic nie łowiłem. A przecież ludzie wyciągają, więc to nie mogło być, do jasnej anielki, takie trudne! No i nie było.
<p class="p1">Zacząłem z powrotem od podstaw. Mocna żyłka, żeby się nie siłować z ewentualną zdobyczą, wolframowy przypon, białe 15-centymetrowe kopyto na końcu zestawu i fruuuuu... Trzy rzuty przeprowadzone klasycznym podbiciem i jest! Potężne uderzenie szarpnęło wędką. Potargowaliśmy się ze szczupakiem jakiś czas, co ja go podciągnąłem, to on mnie troszkę wyciągnął na skraj pomostu, w końcu szarpnął jeszcze raz mocniej i ciężar na wędce zelżał. Wyciągnąłem zestaw i co widzę? Z wolframowego przyponu zostały strzępy! - Nie może być! - Myślę sobie. - Przecież wolframu miały nie przegryzać! - Wróciłem do domu zdruzgotany. Ale już wieczorem układałem kolejny
<p class="p1"><b>chytry plan.</b>
<p class="p1">Kilka dni później nie bawiłem się już w żadne wolframy ani fluorocarbony. Na końcu żyłki przypięta był toporna i prosta stalowa linka z agrafkami w rozmiarze XXL, za którą od biedy można byłoby byka z pastwiska przyprowadzić. Jako przynęta - to samo białe duże kopyto.
<p class="p1">Kilka rzutów i... Łup! Tym razem o mało nie wyrwało mi wędziska z ręki! Kilka, a może kilkanaście minut walki i szczupaczek opisany przeze mnie w opowiadaniu "Pierwszy Metrowiec" zameldował się w podbieraku. To już było coś. Nie dość, że pierwszy wyciągnięty, to jeszcze do tego “pełnowymiarowy”. Teraz wystarczyło tylko je zacząć łapać regularnie.
<p class="p1">Będąc z wizytą u kolegów na pobliskim polu golfowym rozmawiałem z Romkiem, wędkarzem, który niejednego szczupaka już tutaj usmażył. Jak mi pokazał swoje pudełko z przynętami, serce mi zamarło. Pierwsze pudło pełne było obrotówek. Drugie - woblerów jednej znanej firmy, trzecie - drugiej, tym razem rodzimej. Czwarte - rożne rozmiary gum. Łącznie te pudła były warte może komplet nowych opon samochodowych plus duży zbiornik paliwa. Ale co najważniejsze - miały jedną część wspólną: wszystkie przynęty były w kolorze jaskrawej żółtozieleni, a część woblerów była hologramiczna. Okazało się, że w tej części rzeki nic tak nie wkurza szczupaków jak ten kolor. A jak coś wkurza, to wiadomo, trzeba to zniszczyć.
<p class="p1"><b>Przynajmniej tak myślą szczupaki.</b>
<p class="p1">W "mojej" części rzeki te kolory też skutkowały, aczkolwiek nie były tak skuteczne jak białe gumy, czy to czyste, czy z farbowanym na czerwono grzbietem. Czasami zdarzało mi się oglądać, jak jeden zębaty z drugim podpływały za moim woblerem pod sam brzeg i nie zamknęły na nim swojej paszczy. Po czym stanął taki delikwent przy brzegu i patrzył na mnie swoimi wielkimi oczami. A kiedy sięgałem powolutku po aparat, a nawet zdołałem go w jakiś sposób naszykować do zdjęcia, ten odwracał się, machał na pożegnanie ogonem i voila - tyle go widziałem.
<p class="p1">Ano - nie wszystko można mieć. Za to na białe duże gumy szczupaki zacząłem łowić systematycznie. Jesienią zeszłego roku miałem nawet taki okres, że każdy wyjazd nad rzekę kończył się jakimś zębatym. Czasem większym, czasem mniejszym, ale zawsze coś na kiju się trzepotało.
<p class="p1">W tym roku ponownie w maju wyszedłem nad rzekę i pierwszy, niby tylko 70-centymetrowy, ale za to gruby jak beczka drapieżnik, zaczepił się na hak. W czerwcu brania ustały, ale to tutaj normalne. W lipcu wrócą, ale wtedy zapoluję na nie w Polsce. Ze szwedzkimi szczupakami porozmawiam ponownie po wakacjach.
<i><font size=-4>rs, Linköping, czerwiec 2013</font></i>';
$przygoda1.= foto_line('powroty/foto13/szwecja/szczupak',3,9,'_s');
$przygoda1.='<p class="p3">Pierwszy metrowiec (Rzeka Stångån, maj 2012)';
$przygoda1.='<p class="p1">Godziny mijały, komary cięły, a ja oddąłem się myślom. Lubię tak czasem wyłączyć się po pracy i oddać rozmyślaniom na różnie tematy, a do tego wędkarstwo nadaje się wyśmienicie. Ale do diaska, od czasu do czasu mogłaby wziąć jakaś ryba! A tu nic! Koniec maja, co prawda w tym roku zimnego tu w Linköping jak czort, ale w końcu maja, czyli szczupaki powinny być wygłodzone po tarle i polować na co popadnie! Kiedy już prawie podjąłem decyzję o zmianie hobby na filatelistykę, wędką szarpnął potężny ciężar. Wow! Jest! W końcu! Dopiero teraz rozejrzałem się dookoła. Ciężar na wędce spory, a tu w pobliżu ani żywej duszy. Podbierak mam duży, prawie trzy metry, ale pomost też nisko nad wodą nie jest. Ale nie ma co się martwić na zapas - pomyślałem - najpierw trzeba rybkę podholować pod nogi.
<p class="p1">A ta idzie jak kłoda. - Niesamowite, ciekawe kiedy zawróci - nie mogłem się nadziwić. Zawróciła. Hamulec zagrał swoją melodię, a ryba była już po przeciwległej stronie rzeki - jakieś pięćdziesiąt metrów ode mnie. Powolutku przykręciłem hamulec, hamując jej odjazd i zacząłem ją przyciągać z powrotem pompując wędką jakbym wyciągał dorsza ze stumetrowego rowu. Powolutku, pociągnięcie po pociągnięciu i pod nogami pokazał się krokodyli pysk szczupaka. Adrenalina podskoczyła i oczy mi zaświeciły tak, że gdyby była noc, to chyba nie potrzebowałbym latarki. Takiego szczupaka jeszcze nie miałem. Potężny... - Ciekawe jak go wyciągnę - wątpliwości ogarnęły mnie znowu. Dzięki Bogu ryba stała spokojnie tuż pod pomostem. Chyba był za ciężki na to, żeby skakać i odjeżdżać. Sięgnąłem po podbierak, który całe szczęście mam zawsze pod ręką. Zwijając powolutku nadmiar żyłki położyłem się na brzuchu na pomoście i trzymając wędkę lewą ręką starałem się jej nie spłoszyć. Ręce trochę mi się trzęsły, bo w zeszlym roku po jednym z odjazdów wolframowy przypon nie wytrzymał szczupaczych zębów zostawiając przynętę w szczękach uciekiniera. W tym roku zmieniłem przypony na bardziej wytrzymałe i przestałem wierzyć supercienkim, superwytrzymałym i superdrogim wynalazkom reklamowanym przez sprzedawców w sklepach i w kolorowych magazynach wędkarskich. Porządnemu szczupakowi nawet kawał stalowego pręta pewnie by nie przeszkodził. 
<p class="p1">Leżąc ciągle na brzuchu, prawą ręką opuszczałem powoli podbierak. Długi podbierak jest ciężki, niestabilny i trudno nim manewrować, gdy zanurzy się siatkę do wody, ale ma jedną zaletę: jest długi i w pewnych przypadkach niezastąpiony. Ryba chyba zwietrzyła swoją szansę, bo wpłynęła pod pomost i hamulec znowu zagrał ostrzegawczo, a był już dociągnięty prawie do oporu. Bałem się, żeby nie zaplątać jej w pomostowe podporowe pale, bo wtedy mógłbym się pożegnać z dzisiejszą zdobyczą i sesją fotograficzną. Całe szczęście po chwili zrezygnowała całkowicie z oporu. Wyciągnąłem podbierak, ciągle leżąc na brzuchu obiema rękami podholowałem olbrzyma w poprzednie miejsce i rozpocząłem operację podbierania od nowa. Tym razem udało mi się lewą ręką obrócić rybę przodem do zanurzonej siatki. Powoli, bardzo powoli naprowadziłem ją nad zanurzony podbierak i szybko podciągnałem prawą rękę do góry podnosząc szczupaka nad wodę, a przy okazji zamykając go w siatce. No, może nie do końca, bo wystającego ogona zamknąć nie dałem rady. Całe szczęście główny bohater tej historii nie miał już ochoty na wielkie harce, czuł chyba że jest za duży do zjedzenia i niedługo odzyska wolność. Uklęknąłem i wtedy poczułem jak drżą mi kolana. Wyciągnąłem ostrożnie rybę na pomost, rozwarłem szczęki (pierwszy raz w życiu użyłem rozwieracza do szczęk) i usunąłem przynętę. Szczupak leżał na pomoście potulny jak baranek. Wyjąłem z kieszeni metrową miarkę i ups... - Starczy, czy nie - mruknąłem pod nosem. Starczyła! Na styk, bo ryba miała równo sto centymetrów. Mój pierwszy metrowy szczupak!
<p class="p1">Obrałem go z trawy, którą wyciągnąłem z wody razem z nim, obejrzałem dokładnie, i... Zdziwiłem się jeszcze bardziej, gdy na bokach zobaczyłem ślady od jeszcze większych szczęk! Większy szczupak? Czy może wydra? Tego nie wiem, ale wcale bym się nie zdziwił, gdyby w tym miejscu pływały ponadmetrowe osobniki. Podniosłem olbrzyma ostrożnie dwoma rękami i żeby go nie wrzucać z dużej wysokości do wody, zaniosłem kilkanaście metrów dalej za pomost i włożyłem delikatnie do wody. Pomachał na pożegnanie ogonem i zniknął pomiędzy roślinami. Może się jeszcze kiedyś spotkamy? Na pewno go poznam. Po tych śladach wielkich szczęk na bokach.';
$przygoda1.='<p class="p3">Zębacz (Rzeka Stångån, wrzesień 2011)';
$przygoda1.='<p class="p1">- Ale poszedł! - Powiedział Mariusz patrząc na smugę rozbryzganej wody na przeciwległym brzegu rzeki.
<p class="p1">- Taaaak... Nie trafił - mruknąłem w odpowiedzi i zacząłem spokojnie podbijać przynętę. Guma nie zdążyła jeszcze jednak opaść na dno, a szczytówka wędki przygięła się i zaczęła miarowo i mocno pulsować.
<p class="p1">- Chyba a jednak trafił - stwierdziłem z uśmiechem.
<p class="p1">Staliśmy od wczesnego rana na pomoście nad rzeką Stångån* i mąciliśmy wodę. Ja - dużymi gumami, Mariusz dla odmiany - woblerem o nadanej kilka minut wcześniej, aczkolwiek nie popartej jeszcze żadnym szczególnym wyczynem, nazwie “szczupaczy killer”. Woda spokojna, praktycznie prawie bez uciągu, mącona była tylko naszymi przynętami i sporadycznie wyskakującą nad powierzchnię drobnicą, uciekającą przed niewiele większymi okonkami. Poranne słońce świeciło nisko nad ziemią tworząc z okolicy obraz godny największych mistrzów pędzla, a spadające już powoli z drzew liście przypominały o idącej nieuchronnie głębokiej jesieni, na którą w Polsce będziemy musieli poczekać jeszcze przynajmniej miesiąc. Wiatru praktycznie nie było. - Przyjdzie później - powiedziałem. - Tu zawsze wieje. I zawsze w oczy. Szczególnie gdy masz w planach długą rowerową wycieczkę.
<p class="p1">Rzeczywiście, ilekroć wybieraliśmy się ze znajomymi na rowerowe zwiedzanie okolicy, kierunek wiatru tak się zmieniał, że zarówno w jedną stronę jak i z powrotem przewrotnie wiał właśnie z kierunku, w którym zmierzaliśmy. Ale póki co było słonecznie i bezwietrznie, co pozwalało lepiej znieść dość niską jak na koniec września temperaturę.
<p class="p1">- Złapałeś już coś kiedyś w tym miejscu? - Zagaił mój kompan.
<p class="p1">- W tym roku niewiele - odpowiedziałem. - Trzy szczupaki, wszystkie niewymiarowe, oprócz tego kilkanaście patelnianych okoni.
<p class="p1">Zeszłej jesieni do okoni miałem więcej szczęścia. Złapałem ich więcej i do tego zdecydowanie większych. Może dlatego, że używałem małych przynęt i przyponów z plecionki zamiast ze stali. W tym roku nastawiłem się jednak na szczupaki, szczególnie że nie miałem czasu zapolować na nie w kraju.
W Szwecji do dużych szczupaków też nie miałem szczęścia, choć może sporo prawdy jest też w tym co mówią ludzie, że ryb w tutejszych wodach coraz mniej. Skończyły się już dawno czasy, kiedy szczupaki wywożono stąd całymi zamrażarkami, ale trochę czasu musi upłynąć, zanim rzeki znów się zapełnią tak jak kiedyś. Zwłaszcza że jezior tu mnóstwo, a do rzek szczupak wchodzi niechętnie i na krótki czas. A co do popularnych wśród rodaków jezior, to też często słychać opinie, że szczupaki z tygodniowego połowu można policzyć na palcach jednej ręki, a najskuteczniejszą metodą w ostatnich latach jest trolling.
<p class="p1">Zresztą cóż za zdanie można sobie wyrobić o Stångån przyjeżdżając pospiningować na godzinkę od czasu do czasu po pracy. Latem, gdy dzień kończy się koło północy, szczupaki kryją się w co głębszych miejscach w pobliskim Roxen, a jesienią, gdy wygłodniałe wchodzą do rzeki polować na drobnicę, zmrok zapada bardzo szybko. Czasem o złowieniu ryby decyduje pojawienie się wędkarza w odpowiednim miejscu o odpowiedniej godzinie. A nie jest to tutaj łatwe, bo dobre miejsca na miejskim, wolnym od opłat odcinku rzeki mają wielu amatorów i aby takie dostać, trzeba wyskoczyć z łóżka wcześniej niż inni. Co tu dużo mówić - jedynego wymiarowego szczupaka w tym roku złapałem podczas kilku godzin urlopowego wędkowania na Pilicy. No ale teraz wisiał na wędce ten drugi, a po miłym ciężarze czułem, że jest aż nadto wymiarowy.
<p class="p1">- Pomóż Mariusz - krzyknąłem i starałem się przyciągnąć rybę pod nasz pomost. Szło to jak po grudzie, mimo że żyłkę miałem grubą - nie jestem zwolennikiem długiego męczenia silnych ryb na cienkich linkach - i hamulec przykręcony dość mocno. Tak jak myślałem - mruknąłem widząc jak kolega patrzy z dezaprobatą na zbyt krótki podbierak. Kupiłem pierwszy lepszy jaki spotkałem w Biltemie - poprzedni zostawiłem niefortunnie na pomoście kilka miesięcy temu i na drugi dzień już nie było po nim śladu. Jednym okiem patrzyłem na rybę, która właśnie sprawdzała jakość mojego sprzętu efektownym wyskokiem nad wodę, drugim obserwowałem Mariusza usiłującego na skraju pomostu przybrać pozycję leżącą - jedyną pozwalającą mu na skuteczne podebranie ryby. Jeszcze kilka chwil i ryba była pod naszymi nogami.
<p class="p1">Ile może mieć? - Kalkulowałem gorączkowo. Siedemdziesiąt centymetrów... Nie, chyba więcej, może osiemdziesiąt... - Metra nie ma - powiedziałem w końcu na głos. - Ale i tak na Stångån to niezły wynik. Co prawda widziałem już większe sztuki z tej rzeki, ale po pierwsze - nie w tym miejscu, a po drugie - złowione przez człowieka, z którym pod względem umiejętności łowienia szczupaków czy wielkości asortymentu przynęt równać w żaden sposób się nie mogę.
<p class="p1">Podciągnąłem zębacza troszkę bliżej do podbieraka i już po chwili kolejny odjazd przetestował mój kołowrotek. Trudno. Jeszcze raz, spokojnie, siłowo, nie nerwowo, tuż pod nogi. - Spokojnie malutki - powtarzałem w duchu. - Zaraz cię wypuszczę... - Jeszcze jeden zwrot i... Napięcie na żyłce nagle znikło. Nad rzeką też nagle zrobiło się jakby ciszej.
<p class="p1">Długo z niedowierzaniem patrzyłem na przegryzioną stalową plecionkę. - Mam nadzieję, że poradzisz sobie z tą przynętą - pomyślałem i zabrałem się za wiązanie nowego przyponu.
<p class="p1">
<p class="p1"><i>*Stångån to rzeka w Östergotland w południowej Szwecji. Wypływa z wyżyn we wschodniej Småland na południu kraju by po 185 kilometrach biegu poprzez leśno-skalisty skandynawski krajobraz, mijając historyczne miejsca kultu i zabytkowe pałace, skończyć swój bieg w jeziorze Roxen kilka kilometrów na północ od Linköping. Część rzeki w końcu XIX wieku przekształcona została dla celów przemysłowych, szczególnie transportu drewna, w Kinda Kanal. Obecnie przedzielony dziewięcioma zabytkowymi śluzami kanał jest dużą atrakcją turystyczną w tej części Szwecji.</i>';
$przygoda1.='<p class="p3">Rzeka Stångån, kwiecień – wrzesień 2010';
$przygoda1.='<p class="p1">Stångån jest małą rzeką w południowej Szwecji. Ma 185 kilometrów długości, zaczyna swój bieg we wschodniej Småland i kończy wpływając do jeziora Roxen na północ od Linköping. 
<p class="p1">Duży odcinek rzeki został zagospodarowany jako kanał żeglugowy, Kinda Kanal. Jego przemysłowe znaczenie straciło na ważkości krótko po jego oddaniu do użytku na skutek rozwoju kolejnictwa, ale ciągle jest dużą atrakcją turystyczną. Rzeka przepływa przez malownicze lasy liściaste na terenach ściśle związanych z kulturą średniowiecznej Szwecji, przecinając gdzieniegdzie Szlak Królewski i mijając po drodze zameczki i dwory. Dla mnie jako wędkarza najważniejsze jest jednak to, że przepływa przez Linköping, dziesięć minut drogi od miejsca, gdzie mieszkałem.
<p class="p1">Łowienie w Stångån na odcinku miejskim ma też jedną bardzo ważną zaletę: jest darmowe. Dotyczy to całego odcinka od śluz w Sturefors aż do ujścia do jeziora Roxen.
<p class="p1">Poświęciłem tej rzece praktycznie cały sezon, spędzając nad nią każdą wolną chwilę i usiłując rozgryźć co w niej siedzi ciekawego. Chociaż cały sezon to może za dużo powiedziane, bo najciekawsze jesienno-zimowe miesiące, czyli październik, listopad i grudzień, właśnie mnie omijają. 
';
$przygoda1.= foto_line('powroty/foto10/szwecja/stangan',3,4,'_s');
$przygoda1.='<p class="p1">Ale od początku.
<p class="p1">Na Stångån, żeby złapać rybę, trzeba najpierw znaleźć odpowiednie miejsce. A nie jest to łatwe. Odcinek o którym piszę, jak już wspomniałem na początku, został zmieniony w kanał żeglugowy. Powstało na nim osiem wielostopniowych śluz, jedne większe, drugie mniejsze, ale wszystkie mają jedną wadę: blokują wędrówki ryb. Małe elektrownie wodne również nie są sprzymierzeńcami wędkarzy.
<p class="p1">Choć wędkarzom w Linköping nie za bardzo to przeszkadza. W ładną pogodę zajmują każdy odcinek nad swoją rzeką, czasem łowiąc ryby nawet tam, gdzie teoretycznie nie powinno ich być. Jednak największe szanse na rybę są oczywiście w okolicach jezior, czyli w naszym przypadku jest to miejsce pomiędzy ujściem do Roxen na północy miasta, a pierwszą śluzą w Nykvarn. Potwierdza to nadrzeczny krajobraz. Kiedykolwiek nie przyjechałbym nad rzekę, ten odcinek zawsze był oblegany przez wędkarzy. I co ciekawe – ciągle tych samych. Większość z nich to spinningiści biczujący wodę poteżnymi 20- i 30-centymetrowymi woblerami w poszukiwaniu szczupaka życia. Inni próbują wyciągać okonie za pomocą zestawu gruntowego z pęczkami czerwonych robaków za przynętę. Jedni i drudzy sporadycznie odnosili sukcesy.
<p class="p1">Ja natomiast zacząłem od łowienia gruntowego. Wynalazłem sobie drzewo rosnące w nurcie, wokół którego woda wyżłobiła głęboką na prawie trzy metry rynnę i spokojnie, dzień po dniu, łowiłem i nęciłem. Zanętę miałem polską, koszyczki zanętowe - nauczony doświadczeniem z poprzedniego sezonu - również przywiozłem z naszego kraju. W Linköping koszyczków zanętowych kupić nie zdołałem, a zapasy trzeba robić dlatego, że wiosną rzeka jest bardzo zarośnięta i straty w sprzęcie z tego tytułu olbrzymie.';
$przygoda1.= foto_line('powroty/foto10/szwecja/roxen',3,4,'_s');
$przygoda1.='<p class="p1">Co łowiłem? Przede wszystkim płocie. Duże, dorodne, niektóre przekraczały 30 centymetrów. Oczywiście zdarzały się dni, kiedy na haczyku wieszały się same „dziesięciocentymetrówki”, ale to oznaka, że albo woda zmieniła uciąg i poziom (otwarte śluzy), albo zestaw nie leżał w tym miejscu co powinien. Oprócz płoci trafiały się krąpie i czasami, aczkolwiek bardzo rzadko, ładne leszcze. Największego zobaczyłem niestety w koszu. Wyrzucony nie wiadomo z jakiego powodu przez jakiegoś z wędkarzy (czyżby pasożyty?) miał na oko około 40-kilka centymetrów.
Czasami jednak złowić białą rybę było niemożliwością z powodu małych kiełbików, które podjadały z dna wszystko, co tylko im się podało. Rozmiar haczyka był praktycznie bez znaczenia. Przynęta? Tubylcy zalecają kukurydzę, ja natomiast najlepsze efekty miałem na pęczek białych robaków. Miałem wrażenie, że kukurydza swoimi żółtymi ziarnami wręcz odstraszała ryby.
<p class="p1">Lato to niestety komary. Trzeba mieć ze sobą moskitierę na twarz, a oprócz tego pryskać się chemią sprzedawaną w tutejszych aptekach. Polskie przeciwinstektowe specyfiki działają średnio. Lato tutaj bywa gorące i mimo że nie jest duszno, to ciężko wysiedzieć nad rzeką opatulonym od stóp do głów.
<p class="p1">Jesień to dla mnie polowanie na drapieżniki, więc postawiłem wszystko na spinning. I znowu – jak nie chce się w krótkim czasie zostać bankrutem, zapas stalowych przyponów, woblerów i obrotówek lepiej przywieźć z Polski. Oczywiście, jeżeli ma się taką możliwość. Główki i gumy natomiast nie są takie drogie.
<p class="p1">Szczupaka niestety nie udało mi się złapać. Być może za szybko się zniechęcałem, może łowiłem nie na tą przynętę, może nie o tych porach dnia, a może jeszcze nie był czas na szczupaka w Stångån. Tutejsi mówili, że najwięcej szczupaków wchodzi do rzeki z jeziora późną jesienią. Co więcej, pojawiają się również duże sandacze. Nota bene na moich oczach wędkarze wyciągneli dwa szczupaki. Takie około 80 centymetrów każdy. Jak na czas, który spędziłem nad wodą, to niezbyt wiele. 
<p class="p1">Zupełnie inną historię tworzą okonie. Były doskonałą odtrutką na zniechęcenie podczas nieudanych połowów szczupaka. Wystarczylo założyć odpowiednią gumkę, poprowadzić ją w poprzek rzeki sandaczowym sposobem z opadu i już średniej wielkości okoń powoli przygotowywał się na kolację. Zasada jest jedna: większa gumka – większy okoń, ale mniej sztuk. Czasem jedna na wieczór. Mniejsza gumka – mniejszy okoń, ale za to sztuk więcej. Biorąc pod uwagę fakt, że rzadko byłem nad wodą w jednym dniu dłużej niż godzinę, połowy były całkiem niezłe. Oczywiście większość ryb odpływała sobie spokojnie z powrotem, po pierwsze dlatego, że grzech tu jeść okonie, gdy prawie za darmo rozdają w supermarketach norweskie łososie, a po drugie – kto skrobał kiedyś okonia ten wie o co chodzi.
<p class="p1">Co do sandaczy – miałem (albo mi się wydawało) dwa sandaczowe brania, ale zaciąć mi się nie udalo. Równie dobrze mogły być to szczupaki bądź wyrośnięte okonie.
<p class="p1">Podsumowując – rzeka ciekawa, aczkolwiek warto byłoby pospinningować późniejszą jesienią. W przyszłym roku wrócę tu znowu, chociaż tym razem większość wędkarskiego czasu chciałbym poświęcić na pobliską Svårtan. Łowienie jest odpłatne, kosztuje 50 SEK za dzień, ale kupując kartę roczną wychodzi to już bardzo tanio (200 SEK rocznie). A ryby podobno... Podobno jest ich tak dużo, że nawet opalają się topless na brzegu.
<font size=-1>(rs. 2010-11-23)</font>

<p class="p3">Jezioro Åsunden, maj 2009
<p class="p1">To był jeden z niewielu gorących dni tej wiosny w szwedzkim Östergötland. Już wcześniej zostaliśmy zaproszeni na rybobranie
w tym terminie przez naszych znajomych poznanych dzięki portalowi <a href=http://poloniainfo.se>Poloniainfo.se</a>. Długo się nie zastanawialiśmy.
<p class="p1">Jezioro Åsunden jest malowniczo położone pomiędzy wzgórzami około 70 kilometrów na południe od Linköping. Jest ogromne. Ale o
tym nie dane było nam się przekonać naocznie, gdyż żeby zobaczyć jego ogrom, trzeba byłoby płynąć naszą łódką około godziny. A aż
tyle czasu to nie mieliśmy.';
$przygoda1.= foto_line('powroty/foto09/szwecja/asunden',3,4,'_s');
$przygoda1.='<p class="p1">Po wykupieniu obowiązkowych licencji (można je kupić u gospodarza), udaliśmy się łodzią pożyczoną od znajomych na jezioro.
Łódki wyposażone były pięciokonne silniki, co pozwalało na swobodne trolingowanie, a także w miarę szybkie przemieszczanie się z
miejsca na miejsce. Nie było również problemu ze spiningowaniem i łowieniem z gruntu. Pogoda wymarzona. Można powiedzieć, że nawet
ciut za gorąco, bo na łodzi można się było czuć jak ryba na rozgrzanej patelni. Atmosfera zupełnie sielankowa.
<p class="p1">No i ta atmosfera udzieliła się także rybom, bo przez cały dzień od rana do wieczora udało mi się złowić jedną płotkę.
Osławione szczupaki i okonie pochowały się pewnie przed upałem pod skałami.
<p class="p1">Skały są wszędzie. Czasem są ledwo przykryty powierzchnią wody, więc płynąc trzeba wypatrywać oczy, żeby nie uszkodzić łódki.
Na jeziorze jest mnóstwo wysepek, na których, gdy ktoś jest chętny, może poszukać spokoju w gorące letnie dni. Pływa sporo łódek,
a na nich mnóstwo naszych rodaków, z których niestety większość rozpoznawaliśmy po niewyszukanym słownictwie. A głos po wodzie
roznosi się wspaniale. Szczerze mówiąc, poza naszym gospodarzem nie spotkałem tutaj ani jednego Szweda. Może to jezioro już jest tak
odłowione, że Szwedzi tu już nie przyjeżdżają?
<p class="p1">Widoki wzdłuż całej drogi z Linköping do jeziora, a i na samym Åsunden, są iście pocztówkowe. Nam udało się zobaczyć tylko jedną
zatokę, ale i to wystarczyło. Warto tu przyjechać dla tych widoków i przyjemności popływania łodzią po czystej wodzie.
<p class="p1">Jak już wspomniałem wcześniej, głosy po wodzie, a do tego wśród skał, niosą się wyśmienicie, więc nietrudno było odróżnić
najbardziej popularne słowa używane przez wspaniale się bawiących polskich wędkarzy. Jedna grupka nawet wymyśliła oryginalny
sposób na trollingowanie. Żeby nie zawracać łodzi, sczepili dwie ze sobą dziobami w przeciwną stronę i raz płynęli na jednym
silniku w jedną stronę, a raz w drugą. Polak jednak potrafi.
<p class="p1">Mimo braku spektakularnych połowów wycieczka była bardzo miła, szczególnie dzięki naszym znajomym, którzy wynajęli domek od
pana Linderbacka, który pokazał nam przy okazji pięknego, aczkolwiek nieco zniszczonego Spitfire cabrio z lat sześćdziesiątych.
Jego odrestaurowywaniem zajmuje się syn, Fredrik, nota bene pracujący ze mną w Szwecji w jednej firmie.
<p class="p1">Adres internetowy do gospodarstwa Linderback to <a href=http://www.linderback.com>http://www.linderback.com</a>.
Strona jest również w języku polskim.
<p class="p1">Był to ostatni dzień tak ładnej pogody o Östergötland aż do końca czerwca. Lato w Szwecji bywa jednak kapryśne.

<p class="p3">Linköping, rzeka Stångån, maj 2009
<p class="p1">Szwedzi nie łowią ryb...';
$przygoda1.= foto_line('powroty/foto09/szwecja/stanga',3,1,'_s');
$przygoda1.='<p class="p1">Przynajmniej nie na rzece Stångån przechodzącej czasem w Kinda Kanal. Przynajmniej na początku maja. W ogóle, to kto łowi ryby w
Szwecji?
<p class="p1">Naczytałem się w przewodnikach, że to narodowy sport. Czekałem, aż przyjdzie pogoda, będę wiedział, na które łowiska jaka
licencja, kupię zanętę, robaki, może dokupię coś tutejszego do sprzętu. I w końcu przywiozłem dwa kilogramy zanęty z Polski,
kupiłem robaki białe i czerwone, zapłaciłem za nie 80 koron - kwota straszna w porównaniu chociażby z ceną jednodniowej licencji
za łowienie na jeziorze Roxen - i wybrałem się na ryby. Rzeka Stångån jest łowiskiem szczególnym. A dlatego szczególnym, że na odcinku
od jeziora Roxen do śluz Sluttefors można łowić bez licencji, więc idealnym do sprawdzenia, czy tu o tej porze roku w ogóle są ryby.

<p class="p2"><center>***</center>

<p class="p1">Pojechaliśmy we trójkę. Ja, wędkarz z kilkunastoletnim stażem i oni, moi koledzy, z kijami od szczotki i żyłką, za którą można by
byka prowadzić. O haczykach na suma już nie wspomnę. Ale to właśnie jeden z nich złapał pierwszą rybę - około dziesięciocentymetrową
płotkę, podczas gdy ja bezskutecznie usiłowałem zaciąć cokolwiek na zestaw z drgającą szczytówką.
<p class="p1">Poziom wody w rzece jest duży, jest ona częścią Kinda Kanal, turystycznego kanału żeglownego przeciętego siatką śluz, więc
głębokość już nieopodal brzegu sięga dwóch metrów. Nieopodal przystań jachtowa z maszynami o zanurzeniu ponad dwa metry. Zestaw z
drgającą szczytówką i koszyczkiem zanętowym wydawał się więc być idealny. Pogoda również: trochę pochmurno, wietrznie... Tylko ryby
nie ma. Gdy Grzegorz przyniósł pierwszą wspomnianą wyżej rybę frustracja moja sięgnęła zenitu.
<p class="p1">Założyłem czerwonego robaka jako dodatek do białych i w końcu poczułem upragniony ciężar na wędce. Około 25 centymetrowy leszczyk
wprosił się na kolację. Potem już było łatwiej. W krótkim odstępie czasu złapałem jeszcze trzy leszcze i trzy płocie. Niby nic wielkiego,
ale wystarczająco na rozpoczęcie szwedzkiego sezonu i na kolację dla trzech osób. Niby można by nałapać więcej, ale tu nikt nie łowi
więcej, niż potrzebuje.
<p class="p1">W nawiązaniu do tytułu, nad brzegiem rzeki, przynajmniej na tym odcinku, spotkaliśmy mnóstwo imigrantów. Przychodzą, przypatrują
się nie odzywając się ani słowem, odchodzą. Czasami ktoś zapyta, czy jest tu jakaś ryba, usiłują łowić w niedalekim miejscu. Szwedzi
nie łowią tutaj. Pewnie mają swoje miejsca na jeziorach z olbrzymimi szczupakami. Ale i na to przyjdzie czas.

<p class="p2"><center>***</center>

<p class="p1">Cztery dni później nie złowiłem nic.
<p class="p1">Nic, bo tutaj niespełna dwudziestocentymetrowa płotka, to przecież nic. Muszę przeprojektować moje codzienne życie tak, aby rano
przed pracą zdążyć jeszcze rzucić parę razy spinningiem. Oszalałem? Pewnie tak, bo wędkarstwo to szaleństwo, szczególnie gdy się
spojrzy na ceny w tutejszych sklepach ze sprzętem. A jeszcze do tego na pudełkach widzimy napisy, że "made in Poland".
Podczas gdy bezskutecznie biczowałem wodę podjechał samochód, wysiadł człowiek, rozłożył wędkę i rzucił trzy razy. Słownie - trzy razy.
Po czym spakował się i odjechał. Znaczy, że jak w ciągu trzech rzutów nie ma brania, to ryby nie biorą i czas wracać do domu.
<p class="p1">Może to też jest jakaś metoda.

<p class="p2"><center>***</center>

<p class="p1">Przyszedł piątek, a ja znów nad rzeką. Nałóg staje się coraz bardziej wyraźny. Nerwowe spoglądanie na zegarek w pracy, przyjazd
do domu, coś do zjedzenia i pędem na ryby. Bo przecież tu Szwecja, tu są wielkie sztuki, a robaki drogie i nie wiadomo ile jeszcze
w lodówce wytrzymają.
<p class="p1">A tu brania ustały zupełnie. Zdesperowany dosypałem pół pojemnika robaków do zanęty. Bez skutku. Nie wiem, czy to zmiana pogody,
kierunku wiatru, który zaczął wiać z północy przeraźliwym arktycznym zimnem, czy temperatura wody nie przekraczająca jeszcze dziesięciu
stopni, czy może zbyt niski jej poziom. Widać zamknięto śluzy Tannefors.
<p class="p1">Zacząłem obławiać przeciwległy brzeg, ten do którego nie mogę się dostać piechotą, bo prawa do niego zarezerwował sobie zakład
utylizacji odpadów. Tabliczka przy wejściu informuje grzecznie, aczkolwiek stanowczo, że teren ogrodzony i "nie nada". Ryby też wzięły
sobie to do serca. Brań w dalszym ciągu niet. Do tego dwóch nieszwedzkich mężczyzn o nieco ciemniejszej karnacji przyszło nad rzekę
zjeść kolację z dwójką dzieci. Rzeka długa, szeroka, brzeg niezarośnięty, a oni usiedli akurat dziesięć metrów przy mnie. To nic, że
usiedli, ale dzieciaki tak pruły swoje buźki przy wielkim zadowoleniu swoich ojców, że poczułem się podobnie zrezygnowany jak i te
ryby. Zjedli co mieli, wsiedli do samochodu i odjechali w siną dal. Ryb jak nie było tak nie ma.
<p class="p1">W międzyczasie przyjechał Witek i pojechaliśmy wzdłuż rzeki w kierunku jeziora Roxen w poszukiwaniu lepszych miejsc. Smród z
oczyszczalni prowadził nas całą drogę i miejscami był nie do wytrzymania. Kierunek wiatru nie pozwalał dziś przyjemnie łowić nad
Stångån.

<p class="p2"><center>***</center>

<p class="p1">Usiedliśmy przy pięknym rozwidleniu, ptaków mnóstwo. Można godzinami patrzeć, jak rybitwy polują na pokarm. Obserwują z góry
swoje ofiary, a następnie lotem nurkowym spadają na zdobycz z głośnym pluskiem. Nie posiedzieliśmy jednak długo. Okazało się, że jest
również utwardzone miejsce do wodowania łodzi wędkarskich. Wkrótce jedna z takich łodzi przypłynęła i czym prędzej zwinąłem zestaw.
Szwedzi pokazali nam jak się wyciąga łódź motorową z wody za pomocą specjalnego wózka zaprzężonego w czteronapędowe Volvo. Jeden z
nich zapytał mnie po szwedzku, na jaki rodzaj ryby poluję. Dobre sobie. Na jakikolwiek... Oni też wrócili pustą łodzią z Roxen.
Pewnie jeśli nawet coś złowili, to swoim zwyczajem puścili wszystko z powrotem.
<p class="p1">Po ich odjeździe zająłem się spiningowaniem, a raczej badaniem dna za pomocą moich przynęt. Wynik - stracony przypon, wahadłówka
i obrotówka. Następnego dnia dorzuciłem do tego jeszcze jeden wolframowy przypon i dwie przynęty. A ryby nadal nie biorą. Jak dla mnie
wystarczy łowienia w tym miejscu. Obiecałem sobie, że następnym razem dokupię dodatkowy bagaż w liniach lotniczych specjalnie dla
celów wędkarskich.
<p class="p1">Skończywszy łowienie skierowaliśmy się dalej w kierunku jeziora. Okolica malownicza, mijamy port jachtowy, drewniane domki,
pomosty, drogie samochody... Żyć nie umierać. Tylko jak tu żyć, jeżeli jadąc na rowerze boisz się oddychać, by któryś z milionowej
chmary różnej maści owadów nie wpłynął ci do otworów wentylacyjnych. Co by było gdybym usiadł? Wkrótce miałem się o tym przekonać
nad brzegiem Roxen.

<p class="p2"><center>***</center>

<p class="p1">Do jeziora można się dostać tylko drogą wodną - rzeką. Brzegi są gęsto porośnięte roślinnością, w której mnóstwo gniazd wszelkiego
rodzaju ptaków. Wybrały sobie to miejsce na wylęgarnię. Widać w Szwecji każde miejsce jest dobre. Rozśpiewane jest wszystko: krzaki,
drzewa, pobliskie zarośla, szkoda tylko, że ptakom wtóruje autostrada. Mimo wszystko cieszę się, że mam tę rzekę tak blisko. Jak
zasobne są szwedzkie jeziora w ryby przekonam się już pod koniec miesiąca na Åsunden, gdzie pojadę polować na szczupaki. Aczkolwiek
i tutaj, nad Stångån, późnoletnie i jesienne połowy mogą przyprawić o drżenie serca niejednego wędkarza. Ale wczesną wiosną jest
tak sobie. Dobrze, że choć przyjemnie.';
include 'przy_sma.php';
?>
